### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by lekzz** [tomolimo/processmaker#1]
We have interest in running your plugin, but we can't get it to work.

Versions (everything up to date):
Ubuntu: 14.04
GLPI: 0.90
ProcessMaker: 3.0.1.5

Uploading the plugin to glpi/plugins breaks the plugin page. It won't show the processmaker plugin but it also makes all plugins that would alphabetically be after processmaker disappear. 

apache error: "PHP Fatal error:  Cannot make static method CommonDBTM::getTable() non static in class PluginProcessmakerProcessmaker in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php on line 0"

Changing "function getTable()" to "static function getTable()" makes the plugin page work again but the processmaker plugin still can't be installed because "This plugin requires GLPI 0.83.8 or higher".

It seems setup.php doesn't only check to see if it's lower then 0.83.8 but also if it's higher then 0.84: "if (version_compare(GLPI_VERSION,'0.83.8','lt') || version_compare(GLPI_VERSION,'0.84','ge')) {"

Removing the OR will make it installable, but pressing install results in an empty page. More apache non static errors. Fixed a few more of those in the same way as the first only to then run into more/new errors:
"SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost//sysworkflow/nl/classic/services/wsdl2' : failed to load external entity "http://localhost//sysworkflow/nl/classic/services/wsdl2"\n in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php on line 132
PHP Fatal error:  Call to a member function createGroup() on a non-object in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php on line 782"

Uncommenting/changing serverURL in processmaker.class.php and restarting apache still results in errors about http://localhost. I even tried making processmaker available under http://localhost but still same error. The classis part in the url might also have been replaced by neoclassic but that's probably only for the login page and not the url called. So not sure if that needs to be updated.

At this point i decided to give up :P
Please make the plugin workable with the most recent versions of software.

**Comment by tomolimo** [comment]
Hello,
Thank you for your feedback,
Yes, as written in the documentation, this plugin is currently available only for GLPI >= 0.83.8 and < 0.84
The reason is that the Plugin API in GLPI has been changed a lot, forcing every plugin to be review at roots to be compatible with 0.84.
This plugin is going to be ported to 0.85 (and 0.90), it's on my schedule.

Thank you,
Regards,
Tomolimo
