### ISSUE TITLE
Removing the permission error for unassigned users

### ISSUE THREAD

**Issue by momohamed770** [tomolimo/processmaker#101]
Hi,
Is there a way to remove the following message if the current user is not assigned to the next task?

![image](https://user-images.githubusercontent.com/56794498/69940937-242d3000-14ec-11ea-9b21-d9a6e9142d90.png)

**Comment by tomolimo** [comment]
Hello @momohamed770 
Could you give more details?
Thank you,
Regards,
Tomolimo

**Comment by momohamed770** [comment]
I've a process with 2 task Task1 and Task2
User A is assigned to the 1st task and need approval from User B who is assigned to the task2
when user 1 press the submit button the process moves to task2 whom he don't have assignment on it so he can't view it and receive this message which is normal, is there a way to provide anything else instead of this message to the users?
![image](https://user-images.githubusercontent.com/56794498/69945115-93595300-14f1-11ea-9911-ddc8fa85c5ce.png)

**Comment by tomolimo** [comment]
Thank you,
Did respect the wiki about giving view rights for everybody?
Here: https://github.com/tomolimo/processmaker-server/wiki/Roles
and here: https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27

For your information, I don't have this message in any of running processes we are using. 
We currently have 2085 cases (1914 are completed) in our GLPI instance, from 5 processes which are:
1. "Phone request"
1. "ERP account request"
1. "Change and Release management"
1. "Product custom codes" request 
1. "User off-boarding". 

...

regards,
Tomolimo

**Comment by momohamed770** [comment]
Hi,
These solutions are not useful for my process because i assign each task for specific users only not all users .

**Comment by tomolimo** [comment]
Hello,
These solutions are not concerning assignment to tasks, assignment to tasks are managed by the 'Assignment options' per each task.
These are general rights about possibilities of assignment to processes (but not assignments themselves, as they are managed by task properties), and they are possibilities about viewing cases infos.

**Comment by momohamed770** [comment]
Thanks, solved using this URL https://github.com/tomolimo/processmaker-server/wiki/Roles

by adding some missing permissions to the PROCESSMAKER_OPERATOR role.

**Comment by tomolimo** [comment]
cool :)
