### ISSUE TITLE
Sending notifications from case

### ISSUE THREAD

**Issue by momohamed770** [tomolimo/processmaker#102]
Hi,
I followed the below URL to send email notification  but the template didn't translate the variables to its values 
https://github.com/tomolimo/processmaker/wiki/Task-notifications

example template
Hello,

Please find below a Credit Card application to review:

##lang.case.title## ##case.title## 
##lang.CR_requester## ##CR_requester##

##lang.GLPI_ITEM_REQUESTER_PM_ID## ##GLPI_ITEM_REQUESTER_PM_ID##

Email output:
Hello,
Please find below a Credit Card application to review:
 
Case title ';test10000'; 
##lang.CR_requester## ##CR_requester##
##lang.GLPI_ITEM_REQUESTER_PM_ID## ##GLPI_ITEM_REQUESTER_PM_ID##
 
 

Thank you,

**Comment by tomolimo** [comment]
Hello @momohamed770 
Your template is not correct.
For case variables, you must use the var prefix like: `##var.CR_requester##` or `##label.var.CR_requester##`
Regards,
Tomolimo

**Comment by momohamed770** [comment]
I found that this variables i'm using are empty because the notification is fires at start of task so i changed it to send the notification on task update.

But unfortunately the  notification didn't fire after submitting the task as expected.

**Comment by tomolimo** [comment]
Hello @momohamed770 

1. Did you change your template to match the tags?
1. On which task did you try the update task event?

Thank you to give more details, otherwise, I cannot help you :)
Regards,
Tomolimo

**Comment by momohamed770** [comment]
Hi,
I've decided not to use GLPI notifications as it won't provide all my requirements, using PM notifications there are some functions like PMFSendMessage can give you the facility to send emails to specific emails based on your requirement and send each notification based on conditions inside triggers.
You can proceed closing this issue, thanks for your valuable support.

**Comment by tomolimo** [comment]
Did you see this: https://github.com/tomolimo/processmaker/wiki/Notifications#spontaneous-emails?

**Comment by momohamed770** [comment]
Yes i already use some of them but in may case the trigger can check after each dynaform on some PM variables and based on them send emails to specific emails that might change based on the variable value.

**Comment by tomolimo** [comment]
I close then,
regards,
Tomolimo
