### ISSUE TITLE
Can not install ProcessMaker for GLPI 9.1.3

### ISSUE THREAD

**Issue by sofiammm** [tomolimo/processmaker#103]
Hello,

I can not install ProcessMaker for GLPI v. 9.1.3.

How to precede?

I am using: 
- CentOS 7
- MySQL 5.7
- GLPI 9.1.3
Everything is working properly, but can not install the ProcessMaker..

Thank you,

**Comment by tomolimo** [comment]
Hello,

1. Did you read the wiki for [ProcessMaker plugin](https://github.com/tomolimo/processmaker/wiki) and [ProcessMaker server](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation)?
1. ProcessMaker plugin for 9.1.x is no longer supported, latest version for 9.1.x is the [3.3.8](https://github.com/tomolimo/processmaker/tree/3.3.8)

Thank you,
Regards,
Tomolimo

**Comment by sofiammm** [comment]
Hello @tomolimo,

Can you please confirm what is the best combination?: version of GLPI # version of ProcessMaker, as per recommendation I have installed MySql5.7.

Thank you,
Sofia

**Comment by tomolimo** [comment]
Hello @sofiammm 

Here is our own current combination: 
1. GLPI 9.2.4 / PHP 7.2.13 x64 
1. ProcessMaker 3.3.0-community-RE-1.7 / PHP 7.1.24 x64 
1. Windows 2012 R2 x64 
1. IIS 8.5
1. MySQL 5.7.17 x64

Planned for end of year (or begin of next year):
1. GLPI 9.4 / PHP 7.3 x64
1. ProcessMaker 3.3.10-community-RE-1.0 / PHP 7.1.33 x64
1. MySQL 8.0 x64 (will implies fixes in PM server to be compliant).

You may use more recent versions of PHP (but staying with PHP 7.1.x for PM server) and more recent versions of MySQL (but actually staying in 5.7.x for PM server)

You may also check this https://wiki.processmaker.com/3.3/ProcessMaker_Installation_Requirements
And also here: https://github.com/tomolimo/processmaker-server/wiki/PHP-and-MySQL-compatibility 

Thank you,
Regards,
Tomolimo

**Comment by sofiammm** [comment]
Hello @tomolimo,

As I have already Mysql5.7 and GLPI 9.1.3 installed, I opt to install ProcessMaker 3.3.8:
 wget https://sourceforge.net/projects/processmaker/files/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz/download
--2019-12-09 14:13:49--  https://sourceforge.net/projects/processmaker/files/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz/download
A resolver sourceforge.net (sourceforge.net)...216.105.38.13
A conectar sourceforge.net (sourceforge.net)|216.105.38.13|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...302 Found
Localização: https://downloads.sourceforge.net/project/processmaker/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz?r=&ts=1575900830&use_mirror=iweb [a seguir]
--2019-12-09 14:13:50--  https://downloads.sourceforge.net/project/processmaker/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz?r=&ts=1575900830&use_mirror=iweb
A resolver downloads.sourceforge.net (downloads.sourceforge.net)...216.105.38.13
A conectar downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...302 Found
Localização: https://iweb.dl.sourceforge.net/project/processmaker/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz [a seguir]
--2019-12-09 14:13:50--  https://iweb.dl.sourceforge.net/project/processmaker/ProcessMaker/3.3.8/processmaker-3.3.8-community.tar.gz
A resolver iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)...192.175.120.182, 2607:f748:10:12::5f:2
A conectar iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)|192.175.120.182|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...200 OK
Tamanho: 68523775 (65M) [application/x-gzip]
Saving to: ‘download’

100%[=====================================================================================================================================================================>] 68.523.775  1,34MB/s   em 31s

2019-12-09 14:14:22 (2,11 MB/s) - ‘download’ saved [68523775/68523775]


I have error in the next step:

tar -C /opt -xzvf processmaker-3.3.8-community.tar.gz

tar (child): processmaker-3.3.8-community.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Thanks a lot,

**Comment by sofiammm** [comment]
I am working in Linux, CentOS 7

**Comment by tomolimo** [comment]
Hello @sofiammm,

Please read this: https://github.com/tomolimo/processmaker/wiki for the step by step installation of the ProcessMaker plugin
And read this: https://github.com/tomolimo/processmaker-server/wiki for the ProcessMaker server step by step installation and configuration

And then I'll be able to help you,

Thank you
Regards,
Tomolimo

**Comment by sofiammm** [comment]
Hello @Tomolimo,

I have installed:
GLPI 9.2.4
PHP 7.1.33
MySQL 5.7
ProcessMaker: PM 3.3.0- comunity-RE-1.7

The system used is Linux CentOS7.

I have trouble in the last step: can not open the web.

In the vi file: vi /etc/httpd/conf.d/pmos.conf
VirtualHost *:8080>
    ServerName 10.20.221.89

    DocumentRoot /opt/processmaker/workflow/public_html
    DirectoryIndex index.html index.php

    <Directory /opt/processmaker/workflow/public_html>
        Options Indexes FollowSymLinks MultiViews


Thanks a lot if you can help,
S.

**Comment by tomolimo** [comment]
Hello @sofiammm 
What's the error message?
Did you look into the Apache logs?
Did you follow this wiki: https://wiki.processmaker.com/3.0/ProcessMaker_CentOS_RHEL_Installation#VirtualHost_in_Apache_2.4 
Thank you
Regards,
Tomolimo

**Comment by sofiammm** [comment]
Hello,

Yes, I am following exactly:
https://wiki.processmaker.com/3.0/ProcessMaker_CentOS_RHEL_Installation#VirtualHost_in_Apache_2.4

I am inserting the necessary data in the pmos.conf file and after restarting I can not open the web of ProcessMaker: 
"This site can’t be reached glpiserver.cloud.local refused to connect."

Thanks in advice,
S

**Comment by tomolimo** [comment]
Hello,
As I'm not a specialist of Apache, could you check with the official PM server forum?
Here: https://forum.processmaker.com/
thank you
regards,
Tomolimo

**Comment by rohit-ambre** [comment]
Hi ,
happy new year

did you add `glpiserver.cloud.local` in your local machines /etc/hosts ?

did you change `/opt/processmaker` folder's ownership to `apache:apache` ?

change **ServerName** in `pmos.conf` to your processmker's local domain like `pmserver.cloud.local`
you need to use two different domains having same subdomain like
glpiserver.cloud.local   // for GLPI
pmserver.cloud.local   // for Processmaker

**Comment by tomolimo** [comment]
I close this issue as there is no feedback, please feel free to re-open if you want to add something.
