### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Perez18** [tomolimo/processmaker#104]
PHP 7.1.32
MariaDB 10.4-8
Apache 2.4.41

I cannot log in to the Process Maker server, it tells me WARNING: User's account has expired, and I am using the same installation credentials, I have uninstalled and installed again but it does not let me log in

thanks for your help

**Comment by tomolimo** [comment]
Hello @Perez18 ,
What are the versions of GLPI, PM plugin and PM server?
Thank you,
Regards,
Tomolimo

**Comment by Perez18** [comment]
Thanks for your reply

The Versions 
GLPI 9.4.5
PLugin 3.6.5
Server 3.3.0

![image](https://user-images.githubusercontent.com/46699443/73013054-86682a00-3de5-11ea-8541-de4801efa142.png)

**Comment by tomolimo** [comment]
Hello @Perez18 
Could you be more precise about the version of the PM server?
Is it 3.3.0-community-RE-1.8? or else?
Which user login are you using? the one by default "admin / admin"? or else?
Thank you
Regards,
Tomolimo

**Comment by Perez18** [comment]
Yes of course the version
Release 3.3.0-RE-1.7 
I am using the admin user and change the password to admin123

Thank you @tomolimo 
Regards

**Comment by tomolimo** [comment]
Hello @Perez18 

You may check the following tables in wf_workflow DB:
In table USERS search for admin user: 

```
SELECT  `USR_UID`,  `USR_USERNAME`,  `USR_DUE_DATE`,  `USR_STATUS` FROM `WF_WORKFLOW`.`USERS` WHERE `USR_USERNAME` = 'admin'
```

You should get something like:

| USR_UID | USR_USERNAME | USR_DUE_DATE | USR_STATUS | 
| --- | --- | --- | --- | 
| 00000000000000000000000000000001 | admin | 2035-12-31 | ACTIVE | 

If not, please correct accordingly.

Also check the RBAC_USERS table:

```
SELECT  `USR_UID`,  `USR_USERNAME`,  `USR_DUE_DATE`,  `USR_STATUS` FROM `WF_WORKFLOW`.`RBAC_USERS` WHERE `USR_USERNAME` = 'admin'
```

where you should get this:

| USR_UID | USR_USERNAME | USR_DUE_DATE | USR_STATUS | 
| --- | --- | --- | ---: | 
| 00000000000000000000000000000001 | admin | 2035-12-31 | 1 | 

If not, please correct accordingly.

Regards,
Tomolimo

**Comment by Perez18** [comment]
I proceed to performI proceed to perform
and I comment the results


Regards

**Comment by Perez18** [comment]
I proceed to perform
and I comment the results

Regards,

**Comment by Perez18** [comment]
Thank you very much, it was a great help

the problem was the Fields USR_DUE_DATE  was 2020-01-01


Regards
@Perez18

**Comment by Perez18** [comment]
![image](https://user-images.githubusercontent.com/46699443/73024027-b2da7100-3dfa-11ea-9473-6f0dd8f332fd.png)

**Comment by tomolimo** [comment]
Cool, than you for your feedback.
I close the issue.
