### ISSUE TITLE
An unexpected error occurred while searching for your results

### ISSUE THREAD

**Issue by Ammar204** [tomolimo/processmaker#105]
Hello, Iam using process maker 3.4.2 everything is working but when i open participated folder in home i get an error,

>  A Unexpected error occur while searching for your result.Error code 200 and please contact your administration 
![Capture](https://user-images.githubusercontent.com/49533389/79303822-465aa400-7f09-11ea-9f07-34f51c115622.PNG)

**Comment by tomolimo** [comment]
Hello @Ammar204 
Closed it as duplicated in PM server issues :)
Regards,
Tomolimo
