### ISSUE TITLE
Unable to add Case to a ticket

### ISSUE THREAD

**Issue by biznlinks** [tomolimo/processmaker#106]
**Describe the bug**

**To Reproduce**
1. Go to 'Process case for the ticket'
2. Click on 'Select the process, the dropdown shows the process'
2.1 Click on 'Add' nothing happens, page just refreshes
3. I have checked the console log, seeing no errors
4. No errors are received

**Expected behavior**
On selecting 'Add' process is added to the ticket then can be started

**Screenshots**
<img width="1006" alt="Screenshot 2020-04-25 at 2 27 25 PM" src="https://user-images.githubusercontent.com/22963787/80288922-e500b500-8700-11ea-8c43-ce46f219029e.png">

<img width="1226" alt="Screenshot 2020-04-25 at 2 26 21 PM" src="https://user-images.githubusercontent.com/22963787/80288911-bedb1500-8700-11ea-9c7d-f79bf9788002.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
Error from Log file php-errors.log
<img width="1419" alt="Screenshot 2020-04-25 at 10 35 08 PM" src="https://user-images.githubusercontent.com/22963787/80297018-1602d900-8745-11ea-8c6b-73634910d4e4.png">

**Comment by biznlinks** [comment]
Works now...the FQDN have been changed to match.

**Comment by tomolimo** [comment]
Hello @biznlinks,
 
Yes FQDN must be set correctly for the PM server and GLPI server and a common part must exist between GLPI FQDN and PM FQDN, like following:
GLPI: http://glpi.acme.com
PM: http://pm.acme.com
In this exemple, the common part is acme.com
You may refer to this in the wiki to get more info: https://github.com/tomolimo/processmaker/wiki/Plugin-configuration

Thank you
Regards,
Tomolimo
