### ISSUE TITLE
Processmaker plugins release 3.6.6 not compatible with glpi 9.5

### ISSUE THREAD

**Issue by passme1234** [tomolimo/processmaker#107]
**Describe the bug**

**To Reproduce**
1. Go to 'setup'
2. Click on 'Plugins'
4. See error   This plugins requires GLPI >=9.4 and < 9.5

**Expected behavior**

**Screenshots**
![image001](https://user-images.githubusercontent.com/58685577/83154805-25ee4e00-a133-11ea-85fb-5cdd100583b0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tomolimo** [comment]
Hello @passme1234,

As currently, GLPI 9.5 has no official release, see: https://github.com/glpi-project/glpi/releases, I'm not yet working on the plugin release that will be compliant to 9.5
But that will be as soon as the GLPI 9.5 is released.

I keep this issue open as an enhancement.

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @passme1234 ,
As a first "test" you may change the version requirement in the setup.php file and set it to 9.6 instead of 9.5
Regards,
Tomolimo

**Comment by tomolimo** [comment]
fixed by https://github.com/tomolimo/processmaker/releases/tag/4.0.0
