### ISSUE TITLE
Input and Output Documents

### ISSUE THREAD

**Issue by jorge-madrigal** [tomolimo/processmaker#108]
Hello.
You have a great plugin.
I want to ask you. Do you have in mind add input documents and output documents in glpi?

It will be very useful, because if a user (self-service) upload a input file or generate a output file, we can see those documents linked in the ticket in glpi.
When a user creates a process, i want that the user attach a required file. Normaly this file will have a digital signature.

Or the user fills all fields in form and generate a output file. 

This documents link to the ticket. 

Now, we are uploading this documents to glpi, and later linked the documents to the ticket. If this could be automatic, will be the best solution

Thanks

**Comment by tomolimo** [comment]
Hello @jorge-madrigal 
Yes this is in my wish list 😃 
Probably that will be added for the end of the year.
Thank you
Regards
Tomolimo

**Comment by jorge-madrigal** [comment]
Hello:
Now, we have a platform called w-pulpo. This platform has glpi, alfresco,moodle with a cas server. All integrated. We want use your plugin to storage the input and output documents in processmaker and alfresco, and link those documents in a ticket of glpi.

Now, we are studing your plugin to add this options. If we will add this oprtions, i send you the modifications.

Thanks
Jorge Madrigal

**Comment by tomolimo** [comment]
Hello @jorge-madrigal 
Any news about your test?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
See #134
