### ISSUE TITLE
I can't save content  in output documents

### ISSUE THREAD

**Issue by jorge-madrigal** [tomolimo/processmaker#109]
Hello:
I am using processmaker 3.3.0-community-RE-1.7
I am using php 7.1.24 and glpi 9.4.4 and the glpi processmaker plugin 3.6.5

When i create a output document in processmaker, it doesn't save the content of the document. 
If i import your proyect "Remplacement_materiel_non_standard" i can't see the content of the document "Formulaire remplit".

Do you know what is the problem?, Do you give me some idea?
Thank you

**Comment by jorge-madrigal** [comment]
Sorry you can forget this issue. 

Finaly i can add content to output document and save.

**Comment by tomolimo** [comment]
Hello @jorge-madrigal 
Could you share the root cause and the solution to fix this issue?
It can be useful for other to have such info.
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment]
Hello

The problem was that when I typed in ProcessMaker web creator wysiwyg, if I saved the document and re-entered the document again, I didn't see anything.

If you type in wysiwyg web builder and click on the HTML button and then on the update button. The content of the document came and I was able to save the document.

Thank you
Jorge Madrigal
