### ISSUE TITLE
configure glpi / pm

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker#11]
Hello, I can't setup glpi, please could you help me

![image](https://cloud.githubusercontent.com/assets/15144026/25704015/34e16dbc-30d8-11e7-8dfc-353176e8bca0.png)

**Comment by satyan01** [comment]
http://itsm.unigestion.org:8080/ 

Solved

**Comment by tomolimo** [comment]
Hello @satyan01 
The server URL must like http://fully.qualifided.host.name:port/ only. 
And it must match a root domain of the one of GLPI, exp:
GLPI: http://glpi.mydomain.com/
PM: http://pm.mydomain.com/

or

like yours
GLPI: http://itsm.unigestion.org/
PM: http://itsm.unigestion.org:8080/

Also you must select a task category (mandatory field)
And the group for the GLPI users (mandatory field)

Also, as far as I remember, the workspace you chose is not "workflow" but "unigestion"?

regards,
Tomolimo

**Comment by satyan01** [comment]
Thx

How to obtain Group in ProcessMaker which will contain all GLPi users

field is empty.

I have synced glpi users in pm and they are all in GLPI Group in pm

**Comment by tomolimo** [comment]
just follow this: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration#creation-of-default-glpi-user-group
:)

**Comment by tomolimo** [comment]
and if you don't get it in the list, it's because of your DB definition which is not correct

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25706162/e4e7f12a-30df-11e7-858b-b9687d1f4a2d.png)

**Comment by tomolimo** [comment]
Did you create a group in PM server?

**Comment by satyan01** [comment]
yes glpi and all users have been synced from glpi

**Comment by tomolimo** [comment]
But I mean a special group that will contain all GLPI users

**Comment by satyan01** [comment]
I have created glpi

**Comment by tomolimo** [comment]
anyway you should be able to view all the groups that are in PM server DB.
so there is another problem.
could it be a problem of rights of the  user in PM DB?

**Comment by tomolimo** [comment]
I know: it's a problem of language

**Comment by satyan01** [comment]
en on glpi 
en on pm

**Comment by tomolimo** [comment]
but i'm sure that's the problem, let me check the request used to get the groups

**Comment by tomolimo** [comment]
could you do this request on the PM DB?
`SELECT DISTINCT * FROM content WHERE CON_CATEGORY='GRP_TITLE'  ORDER BY CON_VALUE`

**Comment by satyan01** [comment]
0 rows

**Comment by tomolimo** [comment]
then could you go to PM server and check:
![image](https://cloud.githubusercontent.com/assets/7569958/25707490/f5539420-30e3-11e7-94bb-ead6c096761c.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25707599/5918c2e6-30e4-11e7-9909-3ce62042e43b.png)

**Comment by tomolimo** [comment]
Basically, these are the same requests, and one gives 0 records, and the other gives plenty of rows...

**Comment by tomolimo** [comment]
could you check if there is any error in GLPI logs?

**Comment by tomolimo** [comment]
also could post a new screen copy of the PM plugin config?

**Comment by satyan01** [comment]
nothing relevant

**Comment by tomolimo** [comment]
> nothing relevant

to which question?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/25709123/bc7c0c22-30e8-11e7-937e-a174dc6dfab7.png)

**Comment by satyan01** [comment]
error in phplog 

[04-May-2017 17:01:15 Europe/Paris] PHP Notice:  Undefined offset: 2 in C:\inetpub\wwwroot\processmaker\workflow\public_html\glpi\app.php on line 13

**Comment by satyan01** [comment]
[04-May-2017 17:01:15 Europe/Paris] PHP Notice:  Undefined index: HTTP_REFERER in C:\inetpub\wwwroot\processmaker\workflow\public_html\glpi\app.php on line 63

**Comment by tomolimo** [comment]
> [04-May-2017 17:01:15 Europe/Paris] PHP Notice: Undefined index: HTTP_REFERER in C:\inetpub\wwwroot\processmaker\workflow\public_html\glpi\app.php on line 63

Which browser are you using to get this error message?

**Comment by satyan01** [comment]
chrome

**Comment by satyan01** [comment]
fixed, I have fully reinstalled and it works

**Comment by tomolimo** [comment]
thank you for your feedback.
by the way, did you use the latest versions?

**Comment by satyan01** [comment]
Hello Olivier

Oui derniere version

Bonne journée

Yannick
