### ISSUE TITLE
Plugin processmaker not work

### ISSUE THREAD

**Issue by mndoye17** [tomolimo/processmaker#112]
**Describe the bug**
After enable the processmaker plugin i have a 500 error.

**To Reproduce**
1. Install Gpli 9.2.2
2. Extract to your GLPI/plugins folder
3. Install and enable the plugin processmaker
4. Got the error 500

**Expected behavior**
The plugin is proprely enable on GLPI.

**Screenshots**
![image](https://user-images.githubusercontent.com/77067139/103796374-057a6080-503f-11eb-8df3-bc6c39c9ed44.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Comment by tomolimo** [comment]
Hello @mndoye17 

Did you follow the wiki?
Did you install ProcessMaker server?

Thank you
Regards,

Tomolimo

**Comment by mndoye17** [comment]
Hello tomolimo, 

Thanks for your answer. 

Yes for your two questions. I try it again but i have the same issue. 

Thank you, 
Regards
Moussa

**Comment by tomolimo** [comment]
Hello @mndoye17 

Could you post:
1. the GLPI logs
2. the PHP logs.
Thank you
Regards,
Tomolimo

**Comment by mndoye17** [comment]
Hello @tomolimo 

Yes!
Here the php logs:
[15-Jan-2021 13:13:17 UTC] PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in C:\laragon\www\glpi_v2\plugins\processmaker\inc\processmaker.class.php:201
Stack trace:
#0 C:\laragon\www\glpi_v2\plugins\processmaker\inc\processmaker.class.php(233): PluginProcessmakerProcessmaker->openSoap()
#1 C:\laragon\www\glpi_v2\plugins\processmaker\hook.php(234): PluginProcessmakerProcessmaker->login()
#2 C:\laragon\www\glpi_v2\inc\plugin.class.php(1272): plugin_processmaker_post_init(Array)
#3 C:\laragon\www\glpi_v2\inc\includes.php(123): Plugin::doHook('post_init')
#4 C:\laragon\www\glpi_v2\front\central.php(39): include('C:\\laragon\\www\\...')
#5 {main}
  thrown in C:\laragon\www\glpi_v2\plugins\processmaker\inc\processmaker.class.php on line 201



2021-01-05 16:43:35] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\laragon\www\glpi\inc\toolbox.class.php line 659
  *** PHP Warning(2): Use of undefined constant SOAP_COMPRESSION_GZIP - assumed 'SOAP_COMPRESSION_GZIP' (this will throw an Error in a future version of PHP)
  Backtrace :
  ...ins\processmaker\inc\processmaker.class.php:203 
  ...ins\processmaker\inc\processmaker.class.php:243 PluginProcessmakerProcessmaker->openSoap()
  plugins\processmaker\hook.php:234                  PluginProcessmakerProcessmaker->login()
  inc\plugin.class.php:1057                          plugin_processmaker_post_init()
  inc\includes.php:109                               Plugin::doHook()
  front\plugin.php:36                                include()



Cordialement, 
Moussa

**Comment by tomolimo** [comment]
Helllo @mndoye17 

Could you also post the GLPI configuration?
It's in the Setup > General > System:
![image](https://user-images.githubusercontent.com/7569958/104732694-e3b76280-573d-11eb-8063-20018da5e2f6.png)
Could you copy/paste text from [code] tag to [/code] tag?
Thank you,
Regards,
Tomolimo

**Comment by mndoye17** [comment]
Here! 


[code]   GLPI 9.2.2 (/glpi_V2 => C:\laragon\www\glpi_v2) Installation mode: TARBALL
--

Operating system: Windows NT DESKTOP-U6OSBH0 10.0 build 19041 (Windows 10) AMD64 PHP 7.2.19 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, calendar, ctype, curl, date, 	dom, fileinfo, filter, gd, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, readline, 	session, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="36000" memory_limit="512M" post_max_size="2G" safe_mode="" session.save_handler="files" 	upload_max_filesize="2G"  Software: Apache/2.4.35 (Win64) OpenSSL/1.1.1b PHP/7.2.19 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.24 	Server SQL Mode:  	Parameters: root@localhost/glpi_V2 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is not present imap extension is not present Zend OPcache extension is not present APCu extension is not present xmlrpc extension is not present C:\laragon\www\glpi_v2/config : OK C:\laragon\www\glpi_v2/files : OK C:\laragon\www\glpi_v2/files/_dumps : OK C:\laragon\www\glpi_v2/files/_sessions : OK C:\laragon\www\glpi_v2/files/_cron : OK C:\laragon\www\glpi_v2/files/_graphs : OK C:\laragon\www\glpi_v2/files/_lock : OK C:\laragon\www\glpi_v2/files/_plugins : OK C:\laragon\www\glpi_v2/files/_tmp : OK C:\laragon\www\glpi_v2/files/_cache : OK C:\laragon\www\glpi_v2/files/_rss : OK C:\laragon\www\glpi_v2/files/_uploads : OK C:\laragon\www\glpi_v2/files/_pictures : OK C:\laragon\www\glpi_v2/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (C:\laragon\www\glpi_v2\lib\htmlawed) phpCas version 1.3.5 in (C:\laragon\www\glpi_v2\vendor\jasig\phpcas\source) PHPMailer version 5.2.26 in (C:\laragon\www\glpi_v2\vendor\phpmailer\phpmailer) SimplePie version 1.5.1 in (C:\laragon\www\glpi_v2\vendor\simplepie\simplepie\library) TCPDF version 6.2.16 in (C:\laragon\www\glpi_v2\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\laragon\www\glpi_v2\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\laragon\www\glpi_v2\vendor\true\punycode\src) iacaml/autolink in (C:\laragon\www\glpi_v2\vendor\iamcal\lib_autolink) sabre/vobject in (C:\laragon\www\glpi_v2\vendor\sabre\vobject\lib)

Not active

Way of sending emails: PHP

 

processmaker         Name: Process Maker                  Version: 3.4.25     State: To be cleaned
[/code]

**Comment by tomolimo** [comment]
Hello @mndoye17 
Soap PHP module is missing.
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I've added this requirement in the Wiki,
Thank you
