### ISSUE TITLE
Cannot access to Task in GLPI

### ISSUE THREAD

**Issue by sakiliba** [tomolimo/processmaker#113]
Hi ,

I finish the Process Maker installation but i cannot login into.  I don't change the admin password yet ; when i click the button Login the login page reload with a new form. I don't have an error message.
![image](https://user-images.githubusercontent.com/22523921/107226456-12112080-6a12-11eb-9445-b7d948fc1c69.png)

**Comment by sakiliba** [comment]
Hi ,
Thanks you for answering
I change the value for the USR_DUE_DATE in the two tables but i still have the same  issue

**Comment by tomolimo** [comment]
Hello @sakiliba 
Did you check in the PHP logs?
Thank you,
Regards,
Tomolimo

**Comment by sakiliba** [comment]
Where can i find the PHP logs?

**Comment by tomolimo** [comment]
https://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php5-apache-fastcgi-cpanel

**Comment by sakiliba** [comment]
I 've checked the logs but i didn't see any error

**Comment by sakiliba** [comment]
Hi Tomolimo, 

I have changed Maria DB to MY SQL after that i log successfully in Process Maker. 

I am following the Tutorial 1; but after add a case i cannot see the task in GLPI;

![image](https://user-images.githubusercontent.com/22523921/107639558-efc51000-6c68-11eb-98d9-aa029d3b5f94.png)

**Comment by tomolimo** [comment]
Hello @sakiliba 
Could you post screencopies of the PM server configuration? and of the PM plugin configuration?
Could you check in the PHP logs?
Thank you
Regards,
Tomolimo

**Comment by sakiliba** [comment]
Hello , i can check the PHP logs and there are no errors . 
![PM](https://user-images.githubusercontent.com/22523921/107684036-32eba700-6c9a-11eb-9964-d4c654fb9639.PNG)
![pm2](https://user-images.githubusercontent.com/22523921/107684064-3b43e200-6c9a-11eb-9610-82b8eae587a2.PNG)
![GLPI 1](https://user-images.githubusercontent.com/22523921/107684087-40a12c80-6c9a-11eb-81b3-bc113c5d8084.PNG)
![pm2](https://user-images.githubusercontent.com/22523921/107684102-47c83a80-6c9a-11eb-836a-c1b8366862ff.PNG)

**Comment by tomolimo** [comment]
Hello @sakiliba 

I can see that PM server is not in the same domain than GLPI: localhost cannot be used, nor 127.0.0.1, you must use a host name, like for example:
1. for GLPI: glpi.local.com
2. for PM server: pm.local.com
This mandatory, you must define virtual host in you web server. See: [PM server installation](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation#as-a-global-instruction-list-you-may-follow-these) and [PM plugin configuration](https://github.com/tomolimo/processmaker/wiki/Plugin-configuration#pm-server-setup)

Questions:
1. Post the phpinfo() for PM server like below:
![image](https://user-images.githubusercontent.com/7569958/107741706-fa85b080-6d0d-11eb-91a8-a95cfe72155a.png)
2. Post the GLPI config. This info is in GLPI in the Setup menu > General > System tab, copy the text between [code] [/code] tags


Thank you,
Regards,
Tomolimo

**Comment by sakiliba** [comment]
![image](https://user-images.githubusercontent.com/22523921/107749991-47b85100-6d13-11eb-915a-df7c689af1c8.png)
[code]

GLPI 9.4.5 (/GLPI => C:\xampp\htdocs\GLPI) Installation mode: TARBALL
--

Operating system: Windows NT DESKTOP-HMUQSVN 6.2 build 9200 (Windows 8 Professional Edition) i586 PHP 5.6.12 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, 	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, libxml, mbstring, mcrypt, mhash, 	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets, sqlite3, standard, tokenizer, wddx, 	xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12 (Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12 Server at localhost 	Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.26 	Server SQL Mode:  	Parameters: root@localhost/GLPI_processmaker 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed imap extension is installed xmlrpc extension is installed exif extension is installed ldap extension is not present Zend OPcache extension is not present APCu extension is not present CAS extension is not present Database version seems correct (5.6.26) - Perfect! C:\xampp\htdocs\GLPI/files/_log : OK C:\xampp\htdocs\GLPI/config : OK C:\xampp\htdocs\GLPI/files : OK C:\xampp\htdocs\GLPI/files/_dumps : OK C:\xampp\htdocs\GLPI/files/_sessions : OK C:\xampp\htdocs\GLPI/files/_cron : OK C:\xampp\htdocs\GLPI/files/_graphs : OK C:\xampp\htdocs\GLPI/files/_lock : OK C:\xampp\htdocs\GLPI/files/_plugins : OK C:\xampp\htdocs\GLPI/files/_tmp : OK C:\xampp\htdocs\GLPI/files/_cache : OK C:\xampp\htdocs\GLPI/files/_rss : OK C:\xampp\htdocs\GLPI/files/_uploads : OK C:\xampp\htdocs\GLPI/files/_pictures : OK Web access to files directory is protected : OK

[/code]

**Comment by tomolimo** [comment]
Hello @sakiliba 

1. The plugins list is missing the copy/paste 😃. Could you also post this list?
2. Could you specifically look in the phpinfo(): check the error file location, like below: 
![image](https://user-images.githubusercontent.com/7569958/107754945-7b4ea780-6d22-11eb-9c27-e1f16a908b04.png)

By the way: did you add the FQDN for GLPI and PM server like I explained in may last post?

Thank you
Regards,
Tomolimo

**Comment by sakiliba** [comment]
Hi Tomolimo,
I add the  FQDN for GLPI and PM server like you explained. It resolve my issue and i can see the task and do the tutorial successfully. 
 
Thanks for your help

**Comment by tomolimo** [comment]
Hello @sakiliba 
Thank you for your feedback.
Regards,
Tomolimo
