### ISSUE TITLE
Cannot view Dynaforms

### ISSUE THREAD

**Issue by sakiliba** [tomolimo/processmaker#114]
Hi Tomolimo,

I redo the integration in a debian environment but i cannot view the task .
![image](https://user-images.githubusercontent.com/22523921/109681034-fa423d80-7b74-11eb-8b35-c9eb44de9ba8.png)

[code]   GLPI 9.4.5 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux YAWIZE02 4.19.0-14-cloud-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 PHP 7.1.33-34+0~20210228.54+debian10~1.gbpb1fb69 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, 	libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib) Setup: max_execution_time="300" memory_limit="256M" post_max_size="64M" safe_mode="" session.save_handler="files" 	upload_max_filesize="64M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at glpi.yawizeitsm.com Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.33 	Server SQL Mode:  	Parameters: root@localhost/glpiProcessMaker 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed Zend OPcache extension is installed exif extension is installed imap extension is not present APCu extension is not present xmlrpc extension is not present CAS extension is not present Database version seems correct (5.7.33) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Not active

Way of sending emails: PHP

 

processmaker         Name: Process Maker                  Version: 3.6.16     State: Enabled
[/code]

![image](https://user-images.githubusercontent.com/22523921/109681372-4e4d2200-7b75-11eb-82ac-76da1689fbfa.png)

**Comment by sakiliba** [comment]
![image](https://user-images.githubusercontent.com/22523921/109683106-f1eb0200-7b76-11eb-97b4-6f05081b975a.png)

**Comment by tomolimo** [comment]
Hello @sakiliba 
Could you send screenshot of the ProcessMaker plugin configuration in Setup > General > ProcessMaker?
Could you send screenshot of the GLPI Setup in Setup > General > General setup screen ?
Thank you
Regards,
Tomolimo

**Comment by sakiliba** [comment]
Hello, 
![image](https://user-images.githubusercontent.com/22523921/109782556-ee03c200-7c00-11eb-8f0d-87f3a895129b.png)
![image](https://user-images.githubusercontent.com/22523921/109782706-14c1f880-7c01-11eb-8839-a13d32ee5f53.png)
![image](https://user-images.githubusercontent.com/22523921/109782821-391dd500-7c01-11eb-9b1c-4f161fabba8e.png)
Thanks you in advance

**Comment by tomolimo** [comment]
Hello @sakiliba 
Could you check the browser console? To get into the console F12 (or CTRL+Shift+i) and reload the faulty page.
Thank you
Regards,
Tomolimo

**Comment by sakiliba** [comment]
Hi, I re install and i can see the dynaforms. Now i want to know how to use cases variables in process maker. Do you have any example i want to create validtation in GLPI using a task in PM.

**Comment by tomolimo** [comment]
Hello @sakiliba 
As the initial issue is solved, I close the issue.
Feel free to create a new one if you have other questions/issues.
Thank you,
Regards,
Tomolimo
