### ISSUE TITLE
glpi processmaker PHP version

### ISSUE THREAD

**Issue by waaalex** [tomolimo/processmaker#118]
Hello,
When i try to install processmaker-server with php 7.2, install says that it require php 7.1.
But Glpi needs php7.2 and i can't install processmaker on other server.
Any advice?
Regards.
Alex.

**Comment by tomolimo** [comment]
Hello @waaalex 

You can install php7.1 and php7.2 on the same machine.
I can help for Windows and IIS, but for Linux machines you'll have to search for help with Google...
I know it's possible on Linux: I did it one time, but I don't remember how I did it, so I cannot help more.

Another solution could be to wait for the next update of PM server I'm going to provide in the next weeks. This version can run php7.4

Thank you,
Regards,
Tomolimo

**Comment by waaalex** [comment]
Thanks Tomolino :) I will wait. Thank you for you answer.
