### ISSUE TITLE
Groups are imported in ProcessMaker but not the users

### ISSUE THREAD

**Issue by khalidochi** [tomolimo/processmaker#120]
Hey,
I have GLPI 9.5.5 installed on a ubuntu 20 LTS. I managed to install and configure processmaker-server-3.3.0-RE-1.7 and Processmaker plugin 4.0.2 based on wiki and tutorials. The issue is: 
![image](https://user-images.githubusercontent.com/83222177/116083148-d2121f00-a68b-11eb-87e4-3bc729183d1f.png)
The groups are displayed at PM server screen but do not contain any users. pmusers automatic action executes partialy mentionning PM password's length error:
![image](https://user-images.githubusercontent.com/83222177/116082708-40a2ad00-a68b-11eb-8579-bf727abbf8b0.png)
Here is my configuration:
![image](https://user-images.githubusercontent.com/83222177/116082992-9c6d3600-a68b-11eb-9a69-38edaacf389f.png)

![image](https://user-images.githubusercontent.com/83222177/116082846-65972000-a68b-11eb-9890-94ec1fcd083e.png)

Thank you, Merci beaucoup

**Comment by tomolimo** [comment]
Hello @khalidochi 
There is a new version 4.0.3 that fixes this issue :)
Thank you
Regards,
Tomolimo

**Comment by khalidochi** [comment]
Sorry sir,
The new version fails with stdClass Object ( )  issue.
![image](https://user-images.githubusercontent.com/83222177/116098939-fe816780-a69a-11eb-90e5-c0b4824265f6.png)

**Comment by tomolimo** [comment]
Hello @khalidochi 
That's probably because you have a user named admin in GLPI... And then you have corrupted the admin in PM DB...
That's the reason why I proposed to name the PM admin as pm_admin, to be sure that it will not be corrupted with GLPI admin user.
What I propose is to:
1. stop pm_users automatic actions
2. go to PM tables 'rbac_users' and 'users',
3. Change password of the admin user (in both tables), using the following queries:
```
REPLACE INTO `rbac_users` (`USR_UID`, `USR_USERNAME`, `USR_PASSWORD`, `USR_FIRSTNAME`, `USR_LASTNAME`, `USR_EMAIL`, `USR_DUE_DATE`, `USR_CREATE_DATE`, `USR_UPDATE_DATE`, `USR_STATUS`, `USR_AUTH_TYPE`, `UID_AUTH_SOURCE`, `USR_AUTH_USER_DN`, `USR_AUTH_SUPERVISOR_DN`) VALUES ('00000000000000000000000000000001', 'admin', '21232f297a57a5a743894a0e4a801fc3', 'Admin', 'Account', 'admin@processmaker.com', '2035-12-31', '2007-08-03 12:24:36', '2018-07-19 13:49:32', 1, 'MYSQL', '00000000000000000000000000000000', '', '');
REPLACE INTO `users` (`USR_UID`, `USR_USERNAME`, `USR_PASSWORD`, `USR_FIRSTNAME`, `USR_LASTNAME`, `USR_EMAIL`, `USR_DUE_DATE`, `USR_CREATE_DATE`, `USR_UPDATE_DATE`, `USR_STATUS`, `USR_COUNTRY`, `USR_CITY`, `USR_LOCATION`, `USR_ADDRESS`, `USR_PHONE`, `USR_FAX`, `USR_CELLULAR`, `USR_ZIP_CODE`, `DEP_UID`, `USR_POSITION`, `USR_RESUME`, `USR_BIRTHDAY`, `USR_ROLE`, `USR_REPORTS_TO`, `USR_REPLACED_BY`, `USR_UX`, `USR_COST_BY_HOUR`, `USR_UNIT_COST`, `USR_PMDRIVE_FOLDER_UID`, `USR_BOOKMARK_START_CASES`, `USR_TIME_ZONE`, `USR_DEFAULT_LANG`, `USR_LAST_LOGIN`) VALUES ('00000000000000000000000000000001', 'admin', '21232f297a57a5a743894a0e4a801fc3', 'Admin', 'Account', 'admin@processmaker.com', '2035-12-31', '1999-11-30 00:00:00', '2018-07-19 13:49:32', 'ACTIVE', 'US', 'FL', 'MMK', '', '', '1-305-402-0282', '1-305-675-1400', '', '', 'Administrator', '', '1999-02-25', 'PROCESSMAKER_ADMIN', '', '', 'NORMAL', 0.00, '', '', NULL, 'Europe/Paris', '', '2020-11-17 14:28:05');

```
4. go to PM with user/password admin/admin: and then add a new pm_admin user (like proposed in the wiki)
5. change the plugin settings to reflect the new user
6. restart the pm_users automatic action.

thank you
regards,
Tomolimo

**Comment by khalidochi** [comment]
Thank you SIR. I'll test and give my feed-back ASAP.

**Comment by khalidochi** [comment]
IT WORKS NOW. Merci beaucoup

**Comment by tomolimo** [comment]
Hello @khalidochi 
You're welcome
Regards,
Tomolimo
