### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by duckwc** [tomolimo/processmaker#121]
**Describe the bug**
Some of the iframe features are not working correctly in GLPI:
I noticed
- iframe auto resize
- dynaforms are not displaying at all
The error is related to cross-origin requests since my sites are not sharing the same complete domain: one is glpi.mydomain.com and the other pmaker.mydomain.com

**To Reproduce**
1. assign a new process to a ticket
2. Dynaform iframe is empty (only showing the headers)

**Expected behavior**
Dynaform should display the form and resize the iframe to the size of that form

**Workaround
I workaround that issue by editing /processmaker/workflow/engine/js/cases/core/pmDynaform.js and /processmaker/workflow/engine/methods/cases/cases_Step.php and avoiding calls to parent DOM like `parent.showCaseNavigatorPanel`

**Screenshots**

![2021-06-09 17_22_38-GLPI - Setup — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121382899-545a5800-c947-11eb-92ad-f2b9a1efdd99.png)

**Desktop (please complete the following information):**
 - OS: windows 
 - Browser firefox 89 and chrome 91

**Server:
- OS centos 7.6
- Apache 2.4.6
- GLPI 3.5.5 on php 7.2.34
- PM 3.3.0-community-RE-1.7 on php-fpm 7.1.33

***Additional context**

**Comment by tomolimo** [comment]
Hello @duckwc 
Usually this trouble comes from the the fact that GLPI and ProcessMaker server do not share the same domain root.
Good exp: GLPI url: http://glpi.acme.com and PM url: http://pm.acme.com, in this case the shared domain is acme.com
Could you check that?
Thank you,
Regards,
Tomolimo

**Comment by duckwc** [comment]
Hello @tomolimo ,

Sorry I didn't mention it in the issue, but yes they do, both in https:
one is https://glpi.mydomain.com and the other https://
pmaker.mydomain.com

![2021-06-09 17_41_15-GLPI - Setup — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121671012-5854ba00-caae-11eb-98ce-506983398530.png)

Thank you,
Cyril

**Comment by tomolimo** [comment]
Hello @duckwc 
Ok, thank you,
Another question: what URL is currently used for GLPI by your browser?
Thank you
Regards,
Tomolimo

**Comment by duckwc** [comment]
Hello @tomolimo 

The URL is https://glpi.mydomain.com

![2021-06-11 16_44_02-GLPI - Setup — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121704759-543b9300-cad4-11eb-875c-20f81c980a7b.png)

Regards,
Cyril

**Comment by tomolimo** [comment]
Hello @duckwc 

Then we should go to debug in the javascript console in your Browser to get the real error messages.

Could you press F12 (or activate the development tools), tand try to replay the issue?

Then you should have some errors in the javascript console.

Thank you
Regards,

Tomolimo

**Comment by duckwc** [comment]
Hello @tomolimo 

The errors I have are the form

`Uncaught DOMException: Permission denied to access property "xxx" on cross-origin object`

xxx vary from one page to the other. In the dynaforms page, its showCaseNavigatorPanel.
JS file involved is js/cases/core/pmDynaform.js

Thank you,
Regards,
Cyril

**Comment by tomolimo** [comment]
Hello @duckwc 
Could we continue to discuss with discord?
Regards,
Tomolimo

**Comment by duckwc** [comment]
sure  @tomolimo  here is my account id : duckwc#7400

**Comment by tomolimo** [comment]
and mine is: Tomolimo#1077

**Comment by tomolimo** [comment]
Hello @duckwc 
Could you check if the PM server URL is correctly rewritten like explained here: https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Solved after applying https://github.com/tomolimo/processmaker/issues/121#issuecomment-861400044
