### ISSUE TITLE
GLPI tasks are not updating

### ISSUE THREAD

**Issue by duckwc** [tomolimo/processmaker#122]
**Describe the bug**
When filling a dynaform and going to next step, the process is updated in PM, but not in GLPI.
An error is displayed in GLPI showing "At least one 'Process case' is running!Adding a solution is currently disabled!", even if the process has ended.

**To Reproduce**
1. Create a new process
2. Fill the case dynaform and submit to next step
3. go to GLPI "processing ticket"

**Expected behavior**
I'm not sure, but I guess, the task should be set as "done" and a new task created for the next case.

**Screenshots**
![2021-06-09 17_36_25-GLPI - Process cases - 18 — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121385354-52919400-c949-11eb-81cb-6cb69beec7d6.png)
![2021-06-09 17_37_41-GLPI - Tickets - 3155 — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121385557-810f6f00-c949-11eb-8d72-3ec0573de961.png)
![2021-06-09 17_38_51-GLPI - Process cases - 18 — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121385756-adc38680-c949-11eb-89f9-fedfeb49aea6.png)
![2021-06-09 17_41_15-GLPI - Setup — Mozilla Firefox](https://user-images.githubusercontent.com/4290516/121387475-fc255500-c94a-11eb-8745-16c010e9add6.png)

Desktop (please complete the following information):

    OS: windows
    Browser firefox 89 and chrome 91

**Server:
    OS centos 7.6
    Apache 2.4.6
    GLPI 3.5.5 on php 7.2.34
    PM 3.3.0-community-RE-1.7 on php-fpm 7.1.33

**Comment by tomolimo** [comment]
Hello @duckwc 
This issue is linked to #121, solving #121 will solve also this one.
Thank you,
Regards,
Tomolimo
