### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by jojude05** [tomolimo/processmaker#123]
Hello Team,

Is this code includes email notifications when any event occurs (process notifications to the assigned user) , user will be notified?

regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05 
You'll find all the answers about Notifications (and more 😃) to your questions here: https://github.com/tomolimo/processmaker/wiki/Notifications
If not, ask me.
Thank you
Regards,
Tomolimo

**Comment by jojude05** [comment]
Thanks a lot tom..

regards,
Jude

**Comment by jojude05** [comment]
Hello Tom,
How can we achieve the below stack installation and its compatible with windows server 2016 R2?
Can you advise,

version 4.0.x is compatible with GLPI 9.5 and needs ProcessMaker 3.3.0-RE-1.x 
(https://github.com/tomolimo/processmaker-server/releases/latest)

regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05 
Could you post new topics in new issues?
Thank you
Regards,
Tomolimo
