### ISSUE TITLE
ProcessMaker stack Installation

### ISSUE THREAD

**Issue by jojude05** [tomolimo/processmaker#124]
Hello Tom,
How can we achieve the below stack installation and its compatible with windows server 2016 R2?
Can you advise,

version 4.0.x is compatible with GLPI 9.5 and needs ProcessMaker 3.3.0-RE-1.x
(https://github.com/tomolimo/processmaker-server/releases/latest)

regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05 
You may follow the wiki here: https://github.com/tomolimo/processmaker-server/wiki
And if you have any question, I'll be happy to answer.

Thank you
Regards,
Tomolimo

**Comment by jojude05** [comment]
Thanks Tom, let me try .


regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05,

As an advice: follow step by step the wiki for the PM server and for the PM plugin.

As an information, here is our hosting configuration  for PM server and GLPI:

- Windows 2012 R2
- IIS 8
- GLPI 9.5 with PHP 7.4
- PM 3.3.0-RE-1.7 with PHP 7.1
- MySQL 5.7


Thank you
Regards,
Tomolimo

**Comment by jojude05** [comment]
Hello Tom,

Thanks , let me follow the steps you provided.

regards,
Jude
