### ISSUE TITLE
WARNING: User's account has expired

### ISSUE THREAD

**Issue by jojude05** [tomolimo/processmaker#125]
Hello Tom,

After the installation, first time logging to processmaker admin account , i cant signin successfully.
Throwing the below warning on the login screen,

WARNING: User's account has expired

kinldy assist.

regards,
Joseph Jude

**Comment by jojude05** [comment]
Thanks issue solved,
I tried the below steps to update the due date directly in the users and rbac_users table,
UPDATE rbac_users SET USR_DUE_DATE = '2030-01-01' WHERE USR_UID = '00000000000000000000000000000001';
update users set USR_DUE_DATE = '2030-01-01' where USR_UID ='00000000000000000000000000000001';

Worked..

regards,
jUDE

**Comment by tomolimo** [comment]
Hello @jojude05 
Yes, this is the way to solve this.
Thank you,
Regards,
Tomolimo
