### ISSUE TITLE
PHP error when using self service assignment

### ISSUE THREAD

**Issue by duckwc** [tomolimo/processmaker#126]
Hello,

When I'm trying to use the self service assignment rule in a process, I get the following php error before the tasks are generated:

```
Notice: Undefined variable: queryname in /var/www/html/glpi95/plugins/processmaker/inc/processmaker.class.php on line 3507

Fatal error: Missing table name in /var/www/html/glpi95/inc/dbmysqliterator.class.php on line 277
```

This error disappears if I switch back to cyclical assignment

**Comment by tomolimo** [comment]
Hello @duckwc 

It seems there is a problem in the group settings between GLPI and PM...
Did you activate the PM user&group synchro? It's in the automatic action list: https://github.com/tomolimo/processmaker/wiki/Automatic-actions

Thank you,
Regards,
Tomolimo

**Comment by duckwc** [comment]
issue fixed by updating the processmaker.class.php file (line 3468):
from 
`      $query = ['SELECT' => '*',
                'FROM'   => 'TASK',
                'WHERE'  => ['TAS_UID'         => '$pmTaskId',
                             'TAS_ASSIGN_TYPE' => 'SELF_SERVICE']];
`
to 
`      $query = ['SELECT' => '*',
                'FROM'   => 'TASK',
                'WHERE'  => ['TAS_UID'         => $pmTaskId,
                             'TAS_ASSIGN_TYPE' => 'SELF_SERVICE']];
`
