### ISSUE TITLE
Process Maker 4.0.3 installation

### ISSUE THREAD

**Issue by jojude05** [tomolimo/processmaker#128]
Hello Tom,

I successfully installed ProcessMaker 3.3.0-RE-1.7 in my machine.
How can i upgrade with 4.0.3 version?
In 4.0.3 , we can use all the features like email notifications , languages and so on....

version 4.0.x is compatible with GLPI 9.5 and needs ProcessMaker 3.3.0-RE-1.x  --  what will be the final processmaker version once we achive this installation...

pls advise.

regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05 

> version 4.0.x is compatible with GLPI 9.5 and needs ProcessMaker 3.3.0-RE-1.x -- what will be the final processmaker version once we achive this installation...

This sentence is about the ProcessMaker plugin version, and not about the ProcessMaker server version: ProcessMaker plugin version 4.0.x is compatible with ProcessMaker server version 3.3.0-RE-1.x

So You need to install ProcessMaker server and in GLPI you need to install ProcessMaker plugin (which will do the integration of the ProcessMaker server in GLPI).

Regards,
Tomolimo
