### ISSUE TITLE
ProcessMaker Database user passwd issue

### ISSUE THREAD

**Issue by jojude05** [tomolimo/processmaker#130]
Hello Tom,

Good Day.
We are facing an issue,

wf_60cb4a064e8b0 -- Processmaker application database user , unfortunately we changed the password for this user while application is up and running.
Now can't access the application, while logging getting the below error,

Warning: mysqli_connect(): (HY000/1045): Access denied for user 'wf_60cb4a064e8b0'@'localhost' (using password: YES) in C:\inetpub\wwwroot\processmaker\thirdparty\creole\drivers\mysqli\MySQLiConnection.php on line 80 Warning: mysqli_connect(): (HY000/1045): Access denied for user 'wf_60cb4a064e8b0'@'localhost' (using password: YES) in C:\inetpub\wwwroot\processmaker\thirdparty\creole\drivers\mysqli\MySQLiConnection.php on line 80 Warning: mysqli_connect(): (HY000/1045): Access denied for user 'wf_60cb4a064e8b0'@'localhost' (using password: YES) in C:\inetpub\wwwroot\processmaker\thirdparty\creole\drivers\mysqli\MySQLiConnection.php on line 80

Is there any possibility to update the new password in the database connection config files? or how can we handle this issue without rebuliding the application?

Kindly assist.

regards,
Jude

**Comment by tomolimo** [comment]
Hello @jojude05 
Do you have access to the PM server web interface?
I beleive yes.
Then go to this page:
![image](https://user-images.githubusercontent.com/7569958/124583606-84681e80-de53-11eb-8a40-49c35fac7813.png)
Here you may redefine the host, the user name and password of the DB access.
Input the security code, and press 'Setup Password'.
It should fix the issue.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @jojude05 
If you do not have access to the web interface, then you can go to the file here: C:\inetpub\wwwroot\processmaker\shared\sites\workflow\db.php, and you'll find the password of your user on line 7, you may copy this password and use it to redefine the password of mySQL user (I use HeidiSQL to manage mySQL DB).
Don't change the password in this file.
It's better to reset the good password in mySQL, and to define another user in mySQL, and then to use the procedure I've provided above.

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
HeidiSQL : https://www.heidisql.com/

**Comment by jojude05** [comment]
Hello Tom,

If you do not have access to the web interface, then you can go to the file here: C:\inetpub\wwwroot\processmaker\shared\sites\workflow\db.php, and you'll find the password of your user on line 7, you may copy this password and use it to redefine the password of mySQL user (I use HeidiSQL to manage mySQL DB).
Don't change the password in this file.
It's better to reset the good password in mySQL, and to define another user in mySQL, and then to use the procedure I've provided above.

Above steps solved my issue.

Thanks for your prompt support.

regards,
Jude

**Comment by tomolimo** [comment]
you're welcome :)
