### ISSUE TITLE
Office 365 Email Configuration for sending emails

### ISSUE THREAD

**Issue by umair-mlk** [tomolimo/processmaker#131]
Hi, hope you are doing well. Please guide me how we can configure smtp settings for domain email or office 365 email instead of using gmail.

**Comment by tomolimo** [comment]
Hello @umair-mlk 
This question is not in the scope of the ProcessMake plugin, or there is something that you should explain ....
Thank you,
Regards,
Tomolimo

**Comment by umair-mlk** [comment]
In Email Server settings, gmail smtp configuration working fine but PHPMAILER not working with exchange server smtp settings.

**Comment by tomolimo** [comment]
Hello @umair-mlk 
I'm sorry, but I really don't understand what you are trying to do.
Could you post screen copies of the steps?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue as there is no answer to my question.
If you want, you can re-open it with new details.
