### ISSUE TITLE
How can i modify content of task?

### ISSUE THREAD

**Issue by jorge-madrigal** [tomolimo/processmaker#133]
Hello:

We want to add/modify the content of the tasks. 

In each task I am modifying the variable GLPI_ITEM_APPEND_TO_TASK

But the same text always appears, it does not update the content of each task

We want diferrent content in each task.

Is it possible?

Thank you 

![image](https://user-images.githubusercontent.com/66475507/128513198-fe1dbdfd-7cde-4141-ac2e-6964591e662f.png)

![image](https://user-images.githubusercontent.com/66475507/128513434-29cbfd2d-408a-4b92-9c71-638b36e58b14.png)

**Comment by tomolimo** [comment]
Hello @jorge-madrigal 
Could you show me (with screen copies in English) what you are expecting?
And I'll explain you how to do it.
Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment]
Hello.

Don't worry, we've already done it. 
Thanks
