### ISSUE TITLE
Editing the description of the Ticket (request / incident).

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#135]
Hello. When creating a new Ticket, for example, from self-service, there is no possibility to manually correct the description of the Ticket, if the Dynoform is the first. 
GLPI_ITEM_TITLE allows you to change the Ticket header. 
But GLPI_ITEM_DESCRIPTION does not allow you to change the description of the Ticket. 
Is it possible to somehow add to the application description what the user entered in the dinoform?
Step-1
![image](https://user-images.githubusercontent.com/16879167/132305484-096af628-fc21-4afe-9acf-e4d4d9ca17fb.png)
Step-2
![image](https://user-images.githubusercontent.com/16879167/132305698-22123759-f561-46e3-b05f-c8f151a2767e.png)
Step-3
![image](https://user-images.githubusercontent.com/16879167/132305825-cf48a1f4-22ef-4228-98b8-5b762d3c6976.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
Yes, see the wiki here: [https://github.com/tomolimo/processmaker/wiki/Tutorial-2](https://github.com/tomolimo/processmaker/wiki/Tutorial-2)
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> Yes, see the wiki here: https://github.com/tomolimo/processmaker/wiki/Tutorial-2
> Thank you
> Regards,
> Tomolimo
Apparently I asked the question incorrectly. In the screenshot below step 3, the green field is the title and description of the Ticket, the title changes to GLPI_ITEM_TITLE, but GLPI_ITEM_DESCRIPTION cannot be changed, it is read-only. How can I write in the ticket description what was introduced into the dуnoform at the stage of ticket creation?

**Comment by tomolimo** [comment]
Hello @kofe88 
The question was clear, but may be my answer was not :)
In fact, the answer to your question is written in the Tutorial 2: if you follow this tutorial, you'll have the explanations you need to get what you want to be in the ticket description.
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> The question was clear, but may be my answer was not :)
> In fact, the answer to your question is written in the Tutorial 2: if you follow this tutorial, you'll have the explanations you need to get what you want to be in the ticket description.
> Thank you
> Regards,
> Tomolimo
So I don't understand) I did the whole tutorial, but there is only an output to the dino form - UserRequestSumUp, I don't see an output to the description of the ticket itself there. Am I looking the wrong way?

**Comment by tomolimo** [comment]
Hello @kofe88 
The UserRequestSumUp field is the one that must contain the text that you want to have in the ticket description.
Like explained, if you create a trigger with the below content, you'll get a ticket description that will contain:
![image](https://user-images.githubusercontent.com/7569958/132356369-3a302a92-c6a6-4290-bede-2ed6f91638cf.png)

> Reminder of the request
> Last name: xxxxx
> First name: yyyyy
> Age: zzzz

Thank you,
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> The UserRequestSumUp field is the one that must contain the text that you want to have in the ticket description.
> Like explained, if you create a trigger with the below content, you'll get a ticket description that will contain:
> ![image](https://user-images.githubusercontent.com/7569958/132356369-3a302a92-c6a6-4290-bede-2ed6f91638cf.png)
> 
> > Reminder of the request
> > Last name: xxxxx
> > First name: yyyyy
> > Age: zzzz
> 
> Thank you,
> Regards,
> Tomolimo

Such a trigger was created, just like in the tutorial, but only the " - " sign is written in the ticket description (without quotes).

**Comment by tomolimo** [comment]
One question: did you follow the complete Tutorial 2 and what is the result for it?

**Comment by kofe88** [comment]
> One question: did you follow the complete Tutorial 2 and what is the result for it?

Tutorial 2 is working. As I understood, it only works if you insert a trigger between two dynaforms. I found another problem, these are empty tabs Change Log and Dynaforms.
![image](https://user-images.githubusercontent.com/16879167/132382769-1d5623fe-a9d6-431a-970d-5b6f34e52386.png)
![image](https://user-images.githubusercontent.com/16879167/132382811-5225c026-0537-4e65-8ad8-e8ee5418824c.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
Did you follow the wiki here: https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27?
Thank you
Regards
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> Did you follow the wiki here: https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27?
> Thank you
> Regards
> Tomolimo
Hello. I didn't pay attention to it in the wiki, added permissions, everything worked, thank you!
Can I ask you another question?
![image](https://user-images.githubusercontent.com/16879167/132472738-309ec56a-c14f-4490-bcde-0460ee453b5e.png)
Where can I change this window so that there are not 10 words, but less and not in English, but in another language?

**Comment by tomolimo** [comment]
Hello @kofe88 
Currently this not configurable....
Could you post on another issue as soon as you have solved one?
Thank you
Regards,
Tomolimo
