### ISSUE TITLE
Changing the task reassignment window-changing the language of the entered words and their number.

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#137]
Hello. It would be just great if it was possible to change this window.
Namely, to change the language (or even without binding to the language) of the entered words and their number.
![image](https://user-images.githubusercontent.com/16879167/132472738-309ec56a-c14f-4490-bcde-0460ee453b5e.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
Curently the only way is to change the code of the file /plugins/processmaker/ajax/task_users.php line 100 and below.
But I take not of your suggestion, and I think in a next release I will render this part configurable.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @kofe88 
This has been partially implemented into the 4.40 for GLPI 9.5 (or in 5.0.0 for GLPI 10.0)
Thank you
Regards,
Tomolimo
