### ISSUE TITLE
Synchronization of GLPI and ProcessMaker user fields.

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#138]
Hello. 
Is it possible to implement additional synchronization of user fields between the GLPI and PM databases? For example: 
1.field from the GLPI database glpi.glpi_useremails.email in the PM database field wf_workflow.USERS.USR_EMAIL 
2.field from the GLPI database glpi.glpi_users.registration_number in the PM database field wf_workflow.USERS.USR_ZIP_CODE 
Is it possible to expect the implementation of such synchronization? Or maybe you can tell me how I can add it myself?

**Comment by tomolimo** [comment]
Hello @kofe88,

It's not planned to add such info in the case variable list, which is already very long...
But it's always possible to request the needed info from the GLPI DB: For this you need to create a new Database connection in the process definition, and you can use it eveyrwhere in dynaforms, or in triggers.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Question: for what do you need the email info?

**Comment by kofe88** [comment]
> Question: for what do you need the email info?
I asked because DB connections for some reason do not work, even to their own database through 127.0.0.1, although he writes that all connections are successful.
![image](https://user-images.githubusercontent.com/16879167/132645579-e1f018b2-aff7-42ee-9beb-34b798e0c59d.png)
![image](https://user-images.githubusercontent.com/16879167/132645611-6a8ae4d9-9527-47c4-874d-38877090215b.png)
Then create Dropdown in Dynaform:
![image](https://user-images.githubusercontent.com/16879167/132645783-80b80f79-579f-4846-9357-786e90561c51.png)
With this sql code:
SELECT USR_UID, USR_FIRSTNAME FROM USERS;
and getting null result without errors
![image](https://user-images.githubusercontent.com/16879167/132645959-4b2dc801-2d16-4d7f-bcfe-598067b62189.png)
But with databese PM Database this sql code is working:
![image](https://user-images.githubusercontent.com/16879167/132646154-c83a7c00-8ed0-4068-b8fb-c70747047fab.png)
![image](https://user-images.githubusercontent.com/16879167/132646214-0c3bdff8-26f7-4a42-bbdf-cf8c88346e42.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
If you need to access the PM database, then you have to use the already defined DB connection named 'PM Database'.
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> If you need to access the PM database, then you have to use the already defined DB connection named 'PM Database'.
> Thank you
> Regards,
> Tomolimo

I found what the problem was. 
In the user's password for connecting to the database. 
Here was the same problem here https://forum.processmaker.com/viewtopic.php?t=708638  
I changed the password from (for example) "password#" to "password" and now requests are being executed.
