### ISSUE TITLE
GLPI plugin doesn't get PM groups

### ISSUE THREAD

**Issue by lekzz** [tomolimo/processmaker#14]
Hi,

I opened a new ticket for the issue described in issues 11 and 13.

In the GLPI plugin config the option "Group in ProcessMaker which will contain all GLPi users" shows no groups.

In issue 11 the solution reported is "fixed, I have fully reinstalled and it works" but i have tried a full reinstall again by removing /opt/processmaker and the wf_workflow database, and this time also dropping all glpi_plugin_processmaker_* tables in the glpi database.

However even after all this the group fields still shows no groups to select.

glpi screenshot:
![image](https://cloud.githubusercontent.com/assets/3193350/25753537/37e6629e-31bc-11e7-94c6-88b89a87e0ed.png)

pm screenshot:
![image](https://cloud.githubusercontent.com/assets/3193350/25753524/2943f968-31bc-11e7-8327-ca9e08327aa5.png)

db query asked in issue 11:
`mysql> SELECT DISTINCT * FROM CONTENT WHERE CON_CATEGORY='GRP_TITLE' ORDER BY CON_VALUE;
+--------------+------------+----------------------------------+----------+------------+
| CON_CATEGORY | CON_PARENT | CON_ID                           | CON_LANG | CON_VALUE  |
+--------------+------------+----------------------------------+----------+------------+
| GRP_TITLE    |            | 575002986590c9e2371eb42013344305 | en       | GLPI Users |
+--------------+------------+----------------------------------+----------+------------+
1 row in set (0.00 sec)`

language also set to EN in glpi:
![image](https://cloud.githubusercontent.com/assets/3193350/25753609/7917ccee-31bc-11e7-9263-3059003304ca.png)

**Comment by tomolimo** [comment]
Hello,
Could it be a problem of collation?
The query I use is 

> SELECT DISTINCT * FROM CONTENT WHERE CON_CATEGORY='GRP_TITLE'  AND CON_LANG='en' ORDER BY CON_VALUE


Could you try this query?
Regards,
Tomolimo

**Comment by zidex** [comment]
I also had because of the PM table names in lower case.
https://github.com/tomolimo/processmaker/issues/8

**Comment by lekzz** [comment]
Result of the query:
`
mysql> SELECT DISTINCT * FROM CONTENT WHERE CON_CATEGORY='GRP_TITLE' AND CON_LANG='en' ORDER BY CON_VALUE;
+--------------+------------+----------------------------------+----------+------------+
| CON_CATEGORY | CON_PARENT | CON_ID                           | CON_LANG | CON_VALUE  |
+--------------+------------+----------------------------------+----------+------------+
| GRP_TITLE    |            | 575002986590c9e2371eb42013344305 | en       | GLPI Users |
+--------------+------------+----------------------------------+----------+------------+
1 row in set (0.00 sec)
`

Case might be an issue, i noticed in issue 11 the SQL statement asked was with the table name "content" in lower case, which didn't work because in my case the wf_workflow tables are all uppercase. The glpi db tables are all lowercase tho so i'll check #8.

**Comment by lekzz** [comment]
Case is the problem.

PM creates the tables with uppercase tables.
First i tried with lower_case_table_names=2 which according to the mysql docs should keep it as stored but convert it to lowercase on use, if i understand correctly. But that still didn't work and "show tables;" still showed them all as uppercase.

Then i set lower_case_table_names=1 and once again dropped the db and restarted, with lower_case_table_names=1 the tables are forced to lowercase on creation and bingo!

**Comment by tomolimo** [comment]
Thank you very much for your time and your feedback. 
Regards
Tomolimo

**Comment by lekzz** [comment]
Yeah and you too for the fast help! You can close my issues and have a great weekend.
