### ISSUE TITLE
DynaForms are not visible in GLPI’s interface (via Ticket Form)

### ISSUE THREAD

**Issue by alogez** [tomolimo/processmaker#141]
Hi,

DynaForms are not visible in GLPI’s interface (via Ticket Form).
Everything else seem to appear correctly.

**PM server settings**
Local machine : pm.groupe.dom (Windows 10)
Wamp Server : 3.2.3
MySql : 5.7.31 / Php : 5.6.40 / Apache 2.4.46
ProcessMaker : 3.3.0-community-RE-1.7

**GLPI settings**
Another machine : glpi.groupe.dom Windows Server 2019 Standard
Wamp Server : 3.2.3
MySql : 5.7.31 / Php : 7.3.21 / Apache 2.4.46
GLPI : 9.5.6
Plugin ProcessMaker : 4.0.8

**Setting of the case** 
https://github.com/tomolimo/processmaker/wiki/Tutorial-1
https://github.com/tomolimo/processmaker-server/wiki/Skins
https://github.com/tomolimo/processmaker/wiki/Automatic-actions

**Setting of the plugin / process** 
https://github.com/tomolimo/processmaker/wiki/Plugin-configuration
https://github.com/tomolimo/processmaker/wiki/Process-configuration

**Result**

![image](https://user-images.githubusercontent.com/13637446/141074796-bf8d956c-d038-4f24-b54d-3bf3ad53ec14.png)

 

Have you got an idea ?

Thanks in advance,
alogez

**Comment by tomolimo** [comment]
Hello @alogez 

Please see: https://github.com/tomolimo/processmaker/wiki/How-to-view-the-%27Change-log%27-and-the-%27Dynaforms%27

Thank you
Regards,
Tomolimo

**Comment by alogez** [comment]
Hi,
I thank you for your answer.

![image](https://user-images.githubusercontent.com/13637446/141730915-23d6b1d4-845e-4852-893d-f080c0b01c07.png)

Have you got an idea ?

Thanks in advance,
alogez

**Comment by alogez** [comment]
Hi, 
Additional information : 

![image](https://user-images.githubusercontent.com/13637446/141747652-86b458b2-6c31-4e7a-8b9b-dfe6379ca199.png)
Thanks.
alogez

**Comment by alogez** [comment]
Hi,
Thanks for the answer. 
After restarting the services, DynaForm is now displayed.

alogez
