### ISSUE TITLE
Update plugin to GLPI 10.x

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#142]
Hello. Are there plans to update the plugin for GLPI version 10.x?
![image](https://user-images.githubusercontent.com/16879167/146322592-9d734b8a-7ad0-4303-9b7f-2988c57b06de.png)
Thank you!

**Comment by tomolimo** [comment]
Hello @kofe88 
Yes we have, but not before mid 2022
Thank you,
Regards,
Tomolimo

**Comment by kofe88** [comment]
Hi, today released GLPI 10 https://github.com/glpi-project/glpi/releases/tag/10.0.0 , we are looking forward to the new version, thank you so much for your work!)

**Comment by tb-killa** [comment]
Hello,
we are acutally in Plan to migrate to glpi10 and want to ask if something already in Pipeline to bring up the compatibility?

Thank you.

**Comment by tomolimo** [comment]
Hello @tb-killa 
Yes, it's in the pipeline :)
Thank you
Regards,
Tomolimo

**Comment by tb-killa** [comment]
@tomolimo thanks for the answer :)
Are there any timelines? Does we could test with some Code maybe ;)?

**Comment by tomolimo** [comment]
Hello @tomolimo 
Currently, we hope to deliver new release before march 2023.
Thank you,
Regards,
Tomolimo

**Comment by Pival81** [comment]
Are there any updates? We're very interested in this if it works with the latest version.

**Comment by tomolimo** [comment]
Hello @Pival81 
Not yet
Is late
Thank you
Regards,
Tomolimo

**Comment by tb-killa** [comment]
Hi @tomolimo
Are there any news available?
Do you know some Date where new Version will be available?
We need to move to GPLI 10.
Regards,

**Comment by tomolimo** [comment]
Hello @tb-killa 
I hope to be able to deliver for end of June 2023.
Thank you for your patience,
Regards,
Tomolimo

**Comment by mams78** [comment]
Hello @tomolimo 
Are there some news about the glpi10 version?
Mant thanks

**Comment by tomolimo** [comment]
Hello,

Release is almost ready, so be patient 😃 
There is one last bug to be fixed before...

Thank you,
Regards,
Tomolimo

**Comment by wessrafamessi** [comment]
Hello,
Thank you for your assistance.
Regards,

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/processmaker/releases/tag/5.0.0
