### ISSUE TITLE
When the ticket is automatically resolved, no template is assigned.

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#143]
**Describe the bug**
Hello!

When the ticket is automatically resolved, no template is assigned.

There is a solution template "Template 1"  with id 1:

![image](https://user-images.githubusercontent.com/16879167/147730334-08b4e898-ccc6-4025-9b22-649edcd3cd72.png)

There is a solution type "Type 2"  with id 2:

![image](https://user-images.githubusercontent.com/16879167/147730407-d7871be9-09c1-47c6-8de9-f78c55e33350.png)

A trigger has been created in PM with the following content:

![image](https://user-images.githubusercontent.com/16879167/147730488-4bd0d8c6-c981-4bd5-a5a1-1804c60301f2.png)

Assigned in the last Task in the "After routing" section

![image](https://user-images.githubusercontent.com/16879167/147730584-a66d2274-a845-41e0-8504-2ab83b9a7cd4.png)

When the last Task is executed, the ticket is closed with the solution type "Type 2", but without a template.

![image](https://user-images.githubusercontent.com/16879167/147730659-7a754591-969d-4d27-b593-4765d3fc57b2.png)

![image](https://user-images.githubusercontent.com/16879167/147730696-c0877309-3f3d-4913-99d3-a529e66db528.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
Could you  post the version of GLPI and of PM server, and of PM plugin?
Could post the pmx file (process export) so that I can try to reproduce this issue?
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88 Could you post the version of GLPI and of PM server, and of PM plugin? Could post the pmx file (process export) so that I can try to reproduce this issue? At least I need the minimal process that reproduce this issue, I don't need the complete process. Thank you Regards, Tomolimo

Hi!
GLPI 9.5.6

processmaker         Name: Process Maker                  Version: 4.0.8      State: Enabled

ProcessMaker Ver.  3.3.0-community-RE-1.7

[Тестовый_процесс_2-9.zip](https://github.com/tomolimo/processmaker/files/7800851/_._2-9.zip)

**Comment by kofe88** [comment]
@tomolimo Hello! Сongratulations on the past holidays!) 
Do you have any ideas?

**Comment by tomolimo** [comment]
Hello @kofe88 
I've traced the issue till the root cause: in GLPI 9.5 the solutions are no longer in the items, They are in a separate tables :)
That's the root cause.
I'm going to prepare a new release for today.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @kofe88 
The 4.0.11 release is fixing this issue.

To add a solution to a Ticket, you need to set either GLPI_ITEM_SET_SOLUTION_TEMPLATE_ID or GLPI_ITEM_SET_SOLUTION_TYPE_ID, and you may optionnaly set the GLPI_ITEM_APPEND_TO_SOLUTION_DESCRIPTION

To solve a Ticket, you must use the GLPI_ITEM_STATUS and the GLPI_ITEM_CAN_BE_SOLVED

Example of a PM trigger to solve a Ticket:

```
@@GLPI_ITEM_SET_SOLUTION_TEMPLATE_ID = 16; // to define the template to be used
@@GLPI_ITEM_STATUS = 5; // = solved
@@GLPI_ITEM_CAN_BE_SOLVED = 1; // to authorize solving even if the current PM case is not completed
```

Thank you
Regards,
Tomolimo
