### ISSUE TITLE
have lost your session and you have to login again

### ISSUE THREAD

**Issue by mamina16** [tomolimo/processmaker#145]
{"error":"You have lost your session and you have to login again.","success":true,"lostSession":true}

**Comment by mamina16** [comment]
![image](https://user-images.githubusercontent.com/97764003/150135002-5dd58c87-815c-4b5c-813f-5a6de3858b94.png)
 please help me

**Comment by mamina16** [comment]
![image](https://user-images.githubusercontent.com/97764003/150134402-cd982593-2b6c-4769-a3f0-e46ffd78b9d6.png)

**Comment by tomolimo** [comment]
Hello @mamina16 

I'm sorry, but I've no clue for this error which happens also from time to time in my company...
So, if you may check the logs, and post them here?
And also check if there is no error in the javascript console?
And also post here your configuration: GLPI version, PHP version (for GLPI and for PM), and also DB version, etc.. Any information that can be of any help.

Thank you
Regards,
Tomolimo

**Comment by jxchinaquanfu** [comment]
same issue

**Comment by tomolimo** [comment]
Hello
Do you have any errors in log files?
Thank you,
Regards,
Tomolimo

**Comment by anassaoud1** [comment]
pls can u recommand a stable linux version to install glpi and proccess maker because i use ubuntu and evry time i enable the process maker plugin the glpi bug in a white page and he dosnt work until i remove it
