### ISSUE TITLE
Issue when activating Processmaker plugin 4.0.8 or 4.0.11 on Glpi 9.5.6

### ISSUE THREAD

**Issue by Olivier-7** [tomolimo/processmaker#147]
**Describe the bug**
A white screen on Glpi browser after activating on of processmaker 4.0.8 or processmaker 4.0.11 plugins 

**To Reproduce**
1. Install manually processmaker plugins 4.0.8 or processmaker 4.0.11 into www/glpi/plugins or www/glpi/marketplace folder
2. Go to 'Configuration' 'Plugins' menu on Glpi
3. Click on 'Install%' icon
4. Click on 'Activate%' icon
5. See white screen

**Expected behavior**
I expected to see configuration menu of processmaker plugin with fields to inform...

**Screenshots** Yes

**Desktop (please complete the following information):** N/A

**Smartphone (please complete the following information):** N/A

** Server : Glpi**
debian 11 server core
mysql 8.0
apache 2.4.52
php 7.4.25
glpi 9.5.6
processmaker plugins 4.0.8 or 4.0.11

** Server : Processmaker**
debian 11 server core
mysql 8.0
apache 2.4.52
php 7.1
processmaker-server 3.3.0-RE-1.7

**Additional context**

Issue when activating Processmaker plugin 4.0.8 or 4.0.11 on Glpi 9.5.6

Hi all,
so i try to do a lab with 2 stacks :
1st stack with Glpi
debian 11 server core with mysql 8.0, apache 2.4.52, php 7.4.25, glpi 9.5.6, processmaker plugins 4.0.8 or 4.0.11
2nd stack with Processmaker-server
debian 11 server core with mysql 8.0, apache 2.4.52, php 7.1 processmaker-server 3.3.0-RE-1.7

both server are up.
![2022 0125 01 processmaker server](https://user-images.githubusercontent.com/98385511/150986103-5458cffa-6ae3-4de9-b328-2616167af731.png)
![2022 0125 02 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986235-d594fb8f-9900-4fff-8e32-4038f2d1a0a9.png)

On Glpi server i download and extract 4.0.8.tar.gz or 4.0.11.tar.gz on www/glpi/plugins folder.
Afer that i have to rename processmaker-4.0.8 or processmaker-4.0.11 folder to processmaker folder so Glpi can see the plugin.
(it’s the same if i download and extract the archive on www/glpi/marketplace folder ;-) )

I can do the install process on Glpi menu ‘Configuration’ ‘Plugins’ with the icon ‘Installer’

![2022 0125 03 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986251-01858f5d-a20d-4a36-bb29-18ebd92b409e.png)

![2022 0125 07 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986367-c93edb38-5546-4850-a989-b6269b02d6a0.png)

I have an issue when i try to activate the processmaker plugin on Glpi ‘Configuration’ ‘Plugins’ with the icon ‘Activer’.
After a bit the Glpi browser window is white.
If i go to the root folder of Glpi the browser window is still white.

![2022 0125 04 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986276-50c2b7d0-a69a-40b5-875c-16c8d3e7b863.png)

![2022 0125 05 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986319-b44d4b7b-92e8-4c9b-9e8d-8f42c6a6de4a.png)

I can break that issue by renaming processmaker folder into processmaker.old for example.
After that the Glpi browser window is back.

On the Glpi menu ‘Configuration’ ‘Plugins’ for ‘processmaker’ plugin i have an icon ‘Nettoyer’

![2022 0125 06 glpi server plugins](https://user-images.githubusercontent.com/98385511/150986386-1b319e69-30dd-4a71-8c31-da4f458518a1.png)

So i need helps and advices from the community please.
Regards
Olivier

A white screen on Glpi browser after activating on of processmaker 4.0.8 or processmaker 4.0.11 plugins

**Comment by tomolimo** [comment]
Hello @Olivier-7 

I've got two questions:
1. Could you have a look in the log files of php7.1 and php7.4 and glpi?
2. Where did you install the PM plugin? In GLPI/plugins folder or in GLPI/marketplace folder?

And an information for you
1. PM server 3.3.0 is NOT currently compatible with mySQL8.0, but only 5.7.x releases. I'm preparing a PM server which will be compliant to mySQL 8.x, but currently, you have to use the 5.7.x version

Thank you,
Regards,
Tomolimo

**Comment by kofe88** [comment]
@Olivier-7 , Hi!
Is the `php-soap` and `php-intl` extensions installed and enabled on the server with glpi?

I can also suggest adding the line `display_errors = on` (not for production) in `php.ini`, it helped me with a white screen in glpi.

I have the following setup:

```

Server GLPI

GLPI 9.5.6 ( => /var/www/html/glpi) Installation mode: TARBALL
Operating system: Linux support 5.4.0-97-generic #110~18.04.1-Ubuntu SMP Mon Jan 17 20:50:31 UTC 2022 x86_64 
PHP 7.4.27 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, 	sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 
Setup: max_execution_time="30" memory_limit="256M" post_max_size="256M" safe_mode="" session.save_handler="files" 	upload_max_filesize="256M"  
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) ) 	
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36 
Server Software: mariadb.org binary distribution 	Server Version: 10.6.5-MariaDB-1:10.6.5+maria~bionic

Server PM:

Version | 3.3.0-community-RE-1.7
Web server | Apache/2.4.29 (Ubuntu)
PHP version | 7.1.33-44+ubuntu18.04.1+deb.sury.org+1
DB version | MySql (Version 10.6.5 MariaDB)
DB name | wf_workflow
User browser | PHP-SOAP/7.4.27

```

---

There is also a second test installation with glpi 9.5.7:

```

Server GLPI

GLPI 9.5.7 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:ru_RU
Operating system: Linux test-glpi 5.4.0-97-generic #110~18.04.1-Ubuntu SMP Mon Jan 17 20:50:31 UTC 2022 x86_64 PHP 7.4.27 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, 	sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) ) 	
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36 Server Software: mariadb.org binary distribution 	
Server Version: 10.6.5-MariaDB-1:10.6.5+maria~bionic 	

Server PM:

Version | 3.3.0-community-RE-1.7
Web server | Apache/2.4.29 (Ubuntu)
PHP version | 7.1.33-40+ubuntu18.04.1+deb.sury.org+1
DB version | MySql (Version 10.1.48 MariaDB)
DB name | wf_workflow
User browser | PHP-SOAP/7.4.27

```

**Comment by Olivier-7** [comment]
> Hello @Olivier-7
> 
> I've got two questions:
> 
>     1. Could you have a look in the log files of php7.1 and php7.4 and glpi?
> 
>     2. Where did you install the PM plugin? In GLPI/plugins folder or in GLPI/marketplace folder?
> 
> 
> And an information for you
> 
>     1. PM server 3.3.0 is NOT currently compatible with mySQL8.0, but only 5.7.x releases. I'm preparing a PM server which will be compliant to mySQL 8.x, but currently, you have to use the 5.7.x version
> 
> 
> Thank you, Regards, Tomolimo

hi guys,
sorry a little bit busy.

answers
1.
-on glpi side
php7.4
![Capture du 2022-02-22 17-25-35](https://user-images.githubusercontent.com/98385511/155183786-aef2ba1e-4b26-40a1-8692-b5daebd98614.png)

![Capture du 2022-02-22 18-05-15](https://user-images.githubusercontent.com/98385511/155183671-dbed4b10-930d-4c78-bd27-a550853d35b2.png)

perhaps i don't have catched the right file ?

glpi
![Capture du 2022-02-22 18-10-16](https://user-images.githubusercontent.com/98385511/155183738-62342dbc-c526-4a95-ba6b-d878e5ea8f31.png)



-on processmaker side (still the same configuration)
php7.1
![Capture du 2022-02-22 17-30-17](https://user-images.githubusercontent.com/98385511/155183817-a3728f5a-fb9d-4d3e-b419-f123fc384e01.png)

perhaps i don't have catched the right file ?

![Capture du 2022-02-22 18-06-03](https://user-images.githubusercontent.com/98385511/155183705-914389d0-7c34-4969-a188-b16e2264e266.png)


2.
first i have tried to install "pm plugin" on glpi in glpi/plugins folder
and for testing i have tried to install in glpi/marketplace folder (but after uninstalling, removing and cleaning in the plugins folder)

Regards
Olivier

**Comment by Olivier-7** [comment]
> 

Hi @kofe88 

i have checked on glpi-server 
php-soap isn't installed
![pmos info 001](https://user-images.githubusercontent.com/98385511/155329776-64be1eec-4a17-4aa8-ae50-bf164ab45856.jpg)

php-intel is installed
![pmos info 002](https://user-images.githubusercontent.com/98385511/155329806-b452d498-f608-477d-a8a6-f99dda5dd2f3.jpg)

in php.ini (/etc/php/7.4/apache2/php.ini)
display_errors is off
![pmos info 003](https://user-images.githubusercontent.com/98385511/155330156-c371342b-6093-491a-8c14-20d21e2a68c7.jpg)

glpi-server configuration 
![pmos info 004](https://user-images.githubusercontent.com/98385511/155330647-45154fdd-0060-44de-8579-98db9879eb5f.jpg)


pm-server configuration
![pmos info 005](https://user-images.githubusercontent.com/98385511/155330819-426dd38a-4a41-4c9b-bbcd-e9681e51cc8b.jpg)

![pmos info 006](https://user-images.githubusercontent.com/98385511/155330841-2a2fa232-2cad-41df-aaf5-5e79d0c67832.jpg)

Thanks for your help
Regards
Olivier

**Comment by Olivier-7** [comment]
> Hello @Olivier-7
> 
> I've got two questions:
> 
>     1. Could you have a look in the log files of php7.1 and php7.4 and glpi?
> 
>     2. Where did you install the PM plugin? In GLPI/plugins folder or in GLPI/marketplace folder?
> 
> 
> And an information for you
> 
>     1. PM server 3.3.0 is NOT currently compatible with mySQL8.0, but only 5.7.x releases. I'm preparing a PM server which will be compliant to mySQL 8.x, but currently, you have to use the 5.7.x version
> 
> 
> Thank you, Regards, Tomolimo

Hi  @tomolimo & @kofe88 ,
i think the solution is to do on glpi-server
# apt install php-soap
# systemctl restart apache2.service


cause i have redone this
- activating "processmaker 4.0.11 plugins" on glpi plugins server
![pmos info bis 001](https://user-images.githubusercontent.com/98385511/155336813-4007cb3c-6097-45cc-aeb0-85debe053ef5.jpg)

but the icons in the plugin column show off during install process
![pmos info bis 002](https://user-images.githubusercontent.com/98385511/155336926-787ac23e-ee04-443f-8a67-a09d79c9a9f1.jpg)

and if i refresh the page i have a blank page
![pmos info bis 003](https://user-images.githubusercontent.com/98385511/155337039-0a492da7-2da2-4ebd-939c-3ac3194aebd9.jpg)

so i done these commands in my debian terminal where glpi is installed
# apt install php-soap
# systemctl restart apache2.service

and after that i have refreshed glpi page on firefox browser
![pmos info bis 004](https://user-images.githubusercontent.com/98385511/155337338-d1bfec28-47f5-4ab2-988e-22e92cc7e65d.jpg)

icons in the plugins column are back
![pmos info bis 005](https://user-images.githubusercontent.com/98385511/155337573-99798d51-c914-4950-bc5a-4d0b0db2c706.jpg)

and i can access the plugins configuration tab
![pmos info bis 006](https://user-images.githubusercontent.com/98385511/155337670-8ab50bda-8596-4d16-bb6f-d578746ebea6.jpg)

the only bug i had during processmaker install steps is a "WARNING : User's account expired" message for the first login...
![pmos info bis 007](https://user-images.githubusercontent.com/98385511/155338518-ef3f94b2-7425-475b-8bee-e4efd5e76406.jpg)

for that issue i have done these commands on processmaker-server by terminal
# mysql
# UPDATE `wf_workflow`.`RBAC_USERS` SET `USR_DUE_DATE` = '2030-01-01' WHERE `USR_UID` = '00000000000000000000000000000001';
# UPDATE `wf_workflow`.`USERS` SET `USR_DUE_DATE` = '2030-01-01' WHERE `USR_UID` = '00000000000000000000000000000001';
# exit

;-/


thanks guys
regards
Olivier

**Comment by tomolimo** [comment]
@Olivier-7 
Thank you for your feedback, I'll add this requirments in the PM wiki. 
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Please note that it was already in the requirements: https://github.com/tomolimo/processmaker/wiki/Requirements
