### ISSUE TITLE
[help needed] Script task

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#149]
Can i run script task?
I make script task, make ascript, 
![image](https://user-images.githubusercontent.com/16879167/164383848-a3f91d8a-4782-44f1-afd7-7307bd381511.png)
![image](https://user-images.githubusercontent.com/16879167/164384190-10b1309f-dae8-404f-a8ad-1b3d37ae4080.png)
![image](https://user-images.githubusercontent.com/16879167/164384447-95c8171d-f737-4772-a173-c82311b025f2.png)
![image](https://user-images.githubusercontent.com/16879167/164384659-08ca16e0-3057-4dcb-b05d-145ee5cd8079.png)
How can i run this task?

**Comment by tomolimo** [comment]
Hello @kofe88 
Script tasks are not currently supported by the PM plugin, sorry. This is planned to implement them into the plugin, but I've no schedule to give you.
You must use triggers to emulate such tasks.
Regards,
Tomolimo
