### ISSUE TITLE
Loading Failed

### ISSUE THREAD

**Issue by grvy** [tomolimo/processmaker#15]
Hello, 

We have just installed processmaker, and I imported the sample pm file from the wiki. 
I just.. dont actually have any clue of how to configure GLPI to actually show the processes. 

When I try to select a case I get "Loading failed" i presume because im missing some settings, I know the wiki is under construction but I would like some general pointers, I can use to work it out. 

In return I' can write a small entry for the wiki once I figure it out, which you can use to build upon.

thnx.

**Comment by grvy** [comment]
Hello, 

I have tried the steps in the improved wiki (thanks it helps alot) did the PHP sync import script. But im still getting loading failed on the dropdown. I followed the tutorial you put up aswell. 

Is there anyway we can troubleshoot the loading failed dropdown?

**Comment by tomolimo** [comment]
Hello 
Did you try the tutorial? 
Which gives an basic sample of what to do. 
Don't you have any error in the logs? 
Regards 
Tomolimo 
By the way: in which timezone are you?

**Comment by grvy** [comment]
I did try the tutorial yes. That didnt make a difference versus the credit card example PM file I used earlier.

No errors in the log after installing the locale php plugin. Just getting "loading failed" on dropdown.
Timezone is GMT+1

**Comment by tomolimo** [comment]
Mine is GMT+2
Could it be possible to work on this tomorrow morning?

**Comment by tomolimo** [comment]
In the meantime could you prepare screen copies of the plug-in configuration, of the process list, of the process settings?

**Comment by grvy** [comment]
sure. 

Plug-in config:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25868739/175504aa-34fe-11e7-8205-08bb6ff8088e.png)
Process list:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25868749/25bfb3dc-34fe-11e7-90c0-9cecc0ba87cd.png)
Process settings:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25868760/33306336-34fe-11e7-974c-853751c96ab5.png)
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25868766/3c321bb4-34fe-11e7-91ed-303763c6efd6.png)
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25868781/45ed022c-34fe-11e7-9880-ff91f7be7990.png)
{ps also tried under root entity]

**Comment by tomolimo** [comment]
When you try to start the case, are you with a glpi user who is in the Administrator profile? I believe yes, tell me. 
Does this glpi user also added in PM server process as authorized on the first task?

**Comment by grvy** [comment]
I have the admin profile yes. Yes also authorized.

**Comment by tomolimo** [comment]
Tomorrow I'll test the script. 
Could you also give your glpi  configuration?

**Comment by grvy** [comment]
what do you need of the GLPI config?

**Comment by tomolimo** [comment]
In setup > general > system, there is a section for the glpi settings. Could you copy paste it to me?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25870667/2f7789b6-3505-11e7-91fb-7d50e21383de.png)

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25871038/6e2840be-3506-11e7-81cf-d84d2b33d76c.png)
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25871061/7d38434c-3506-11e7-86f9-ca47d56c89dd.png)

**Comment by tomolimo** [comment]
Hello 
Could you please screen copy the 'load failed' message? 
Thank you

**Comment by tomolimo** [comment]
Could you please try with the latest releases of PM server and of PM plugin?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25887095/ee84be90-3560-11e7-9a3b-c1cc1cb02b20.png)
Trying the new PM and plugin asap will let you know.

**Comment by tomolimo** [comment]
Ok, thank you, don't try new versions yet, it's not a problem with versions.
it's a browser/network/rights issue with the web site
The way to troubleshoot is: in your browser could you activate developer tools (generally it's the F12 key)
And activate the Network traces?
And try to find any errors?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25887327/02f67a2a-3562-11e7-945e-78b02d42feda.png)

**Comment by grvy** [comment]
this is the dropdownprocess details:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25887381/39ce901e-3562-11e7-8406-2ee62d47272c.png)

**Comment by tomolimo** [comment]
404 means: not found

**Comment by tomolimo** [comment]
Could you check that the file is really present in processmaker/ajax folder?

**Comment by tomolimo** [comment]
or you may have a problem with the uppercase in the name of the file?

**Comment by tomolimo** [comment]
on your last screen copy, the URL is strange, seems like the letter h from http://ticket.intra/... is missing, could you check?

**Comment by grvy** [comment]
the h isnt missing, its just a scroll. 

We did notice that we dont have a ajax folder even. It's missing in the older zip we used to install. 3.1.2
Installing tar.gz of 3.1.3 now.

**Comment by tomolimo** [comment]
Yes, exactly the ajax folder is missing in the 3.1.2. I didn't see that before :disappointed: : it's my fault.

**Comment by grvy** [comment]
That's okay the dropdown works now, but now we get a login screen on the cases. Could it be that becuz we use GLPI with AD authentication it cant authenticate? we used the import scrip aswell.. but I cant login as my user in PMOS becuz it probably doesnt know the PW?

**Comment by tomolimo** [comment]
screen copy?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25888756/a9a25eb6-3567-11e7-98d5-46aff6a24e78.png)

**Comment by tomolimo** [comment]
still http 404 error,
network trace?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25888942/652ea9d2-3568-11e7-836f-a0efb8b10ba0.png)
URL = http://pmos.intra/errors/error404.php?url=/sysworkflow/nl/glpi_neoclassic/cases/cases_open?sid=4746610875912c9f4671390051560009&APP_UID=8968825665912c9f2bc0775064385581&DEL_INDEX=1&action=TO_DO&rand=749747083

**Comment by tomolimo** [comment]
That's a problem of uppercases and lowercases the file should be in **processmaker-server-folder**/workflow/engine/methods/cases and is named cases_Open.php
so I'm going to fix this in the plugin

**Comment by grvy** [comment]
Manually changing the url doesnt do anything tho.

**Comment by tomolimo** [comment]
where did you change it? in plugin code? or in folder?

**Comment by grvy** [comment]
in the url I wrote above. I changed it to uppercase.

**Comment by tomolimo** [comment]
did you check if the file is present in the given folder?

**Comment by tomolimo** [comment]
Could you also check the network trace?

**Comment by grvy** [comment]
You already have the network trace; the file is present. It's the same error 404.

**Comment by tomolimo** [comment]
how did you change the name of the URL to be sure that it will be called with uppercase?

**Comment by grvy** [comment]
just in the browser?

**Comment by tomolimo** [comment]
sorry I don't understand, could you show me a screen copy?

**Comment by grvy** [comment]
I just copied and pasted the URL i put in above (this one): 
http://pmos.intra/errors/error404.php?url=/sysworkflow/nl/glpi_neoclassic/cases/cases_open?sid=4746610875912c9f4671390051560009&APP_UID=8968825665912c9f2bc0775064385581&DEL_INDEX=1&action=TO_DO&rand=749747083

and changed the casesopen to cases_Open and then put it in Firefox.

**Comment by tomolimo** [comment]
ok, then it's normal you got again http 404, as it's the goal of the page you've called (http://pmos.intra/errors/error404.php),

try this one:
http://pmos.intra/sysworkflow/nl/glpi_neoclassic/cases/cases_Open?sid=4746610875912c9f4671390051560009&APP_UID=8968825665912c9f2bc0775064385581&DEL_INDEX=1&action=TO_DO&rand=749747083

**Comment by grvy** [comment]
redirects to login page.

**Comment by tomolimo** [comment]
then try to login, and then replay the URL

**Comment by grvy** [comment]
i did that ofcourse. I guess becuz its not called in GLPI it cant push the authentication. Will wait for the fix to the upper/lowercase.

**Comment by tomolimo** [comment]
it's coming :smile:

**Comment by tomolimo** [comment]
here you are: https://github.com/tomolimo/processmaker/releases/latest

**Comment by grvy** [comment]
2017-05-10 13:44:40 [8@glpi01]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  ...ns/processmaker/inc/processmaker.class.php:2410
  ...ins/processmaker/front/processmaker.form.php:14 PluginProcessmakerProcessmaker->startNewCase()
2017-05-10 13:44:40 [8@glpi01]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  ...ins/processmaker/front/processmaker.form.php:16

**Comment by tomolimo** [comment]
means either the PM login is wrong (the login in GLPI doesn't match the login in PM), or the GLPI login you are using has no rights on the first task of the PM process.    

Check logins:    
Your login in GLPI is ID 8, could you check if in GLPI DB the id 8 is in table glpi_plugin_processmaker_users and give back the pm_users_id, and check that this user has a password <> NULL?    
Then you may check if in PM DB (wf_workflow) in table users, you should have a row with USR_UID= the pm_users_id got previously. Then you may check if passwords are equals.

Check rights on process first task:    
1. open process with designer
1. right click on the first task of the process, and select 'Assignment Rules' in the pop-up menu
1. Check that on the right side of the 'Assignment Rules' dialog box, you GLPI login is correctly appearing. Be careful that PM server a default 'admin' user, that doesn't match any GLPI 'admin'. To be sure you should rename the PM admin account to something like pm_admin.

**Comment by grvy** [comment]
Thank you! that works. Just one more thing. When I click on dynaforms it shows this:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/25898268/b852583e-358b-11e7-98e4-da2fbe23c067.png)
Is this correct? I would assume it would show the dynaform? the rest seems to work. I just need some proper processes in PM.

**Comment by tomolimo** [comment]
Sorry for being long before answer to your post, 
To see Change log and dynaforms, you need to define 'Process permissions': see <https://github.com/tomolimo/processmaker/wiki/FAQ/_edit#when-in-a-glpi-ticket-how-to-get-the-change-log-and-the-dynaforms>

**Comment by tomolimo** [comment]
Seems fixed?
if not re-open a new issue, thank you
