### ISSUE TITLE
Can't refresh task list from my first process

### ISSUE THREAD

**Issue by SneakyNuke** [tomolimo/processmaker#150]
Hello tomolimo,

I have followed all the wikis, gone through a good part of the issues but I still cannot refresh the list of tasks on GLPIon my first process (Tutorial 1)
![image](https://user-images.githubusercontent.com/51399245/166871603-6c347947-67fa-42d4-997f-51e4301978ed.png)

No errors in logs 
![image](https://user-images.githubusercontent.com/51399245/166871811-4c4ac1cd-ffac-4009-bddd-26ab9525440f.png)

Here my GLPI config
![image](https://user-images.githubusercontent.com/51399245/166871850-b15082ee-ba19-452d-a3a6-3fad8f05aa0c.png)

Here my PM system information
![image](https://user-images.githubusercontent.com/51399245/166871890-ea206707-a81f-4fbe-8dc6-10ccc5910e39.png)

Requirement check
![image](https://user-images.githubusercontent.com/51399245/166871919-48d68944-5cf8-459d-b5c6-599084cc7a4a.png)

Case List Cache Builder
![image](https://user-images.githubusercontent.com/51399245/166872317-d34b6fc4-923e-4647-bc34-399d1b0663e2.png)

**Comment by tomolimo** [comment]
Hello @SneakyNuke 
I'll try to spend time to help you today :)
But as a quick try, could you set the SSL verification to 'No'?
Thank you
Regards,
Tomolimo

**Comment by SneakyNuke** [comment]
Thanks for your answer, I tried but it didn't solve the problem
![image](https://user-images.githubusercontent.com/51399245/166887355-3ac17a7a-e362-451a-84ee-63b57fd96f46.png)

**Comment by tomolimo** [comment]
Hello @SneakyNuke,
Then could you check the php error logs for the PM server (it must be PHP 7.1 error log)?
To know where this file is, you  must check in phpinfo() of the php 7.1
If not defined could you define it, and then retry the task synchro?
Thank you
Regards,
Tomolimo

**Comment by SneakyNuke** [comment]
![image](https://user-images.githubusercontent.com/51399245/166891735-30747f60-45e5-480b-b8b4-9bab057223db.png)

I do --> tail -f /var/log/php_fpm_7.1_errors.log when clicking on refresh task but nothing is writing in the error log

**Comment by tomolimo** [comment]
Hello @SneakyNuke 
Several questions: 
1. what's the version of GLPI?
2. version of PM plugin?
3. Configuration of GLPI?
Thank you
Regards,
Tomolimo

**Comment by SneakyNuke** [comment]
![image](https://user-images.githubusercontent.com/51399245/166893597-3ac408e3-650f-4b68-86ee-5ddcfae59b91.png)
![image](https://user-images.githubusercontent.com/51399245/166893649-4487beff-fb1c-4207-9fbd-bfd126bb0514.png)
![image](https://user-images.githubusercontent.com/51399245/166893730-91403f91-02b0-4fb6-97c5-d30ccf9f8556.png)

**Comment by tomolimo** [comment]
in fact I wanted the content of the 'system' tab 
you may copy/paste what's between [code] and [/code]

**Comment by SneakyNuke** [comment]
OK ! 
[code]   GLPI 9.5.3 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux vsl-intranetsi 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 PHP 7.4.23 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Stomp, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, geoip, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="200M" safe_mode="" session.save_handler="files" 	upload_max_filesize="200M"  Software: nginx/1.14.2 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Server Software: Debian 9.12 	Server Version: 10.1.45-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.1.45) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 0 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.3 GLPI_SCHEMA_VERSION: 9.5.3 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)

Server: '172.16.200.15', Port: '389', BaseDN: 'DC=it-gdh, DC=local', Connection filter: none, RootDN: 'ldap it-gdh', Use TLS: 		none

Not active

Way of sending emails: PHP

 

formcreator          Name: Form Creator                   Version: 2.10.4     State: Enabled 	processmaker         Name: Process Maker                  Version: 4.0.11     State: Enabled
[/code]

**Comment by SneakyNuke** [comment]
![sys](https://user-images.githubusercontent.com/51399245/166898086-80d9a1ce-6534-4a78-bcbb-01a2958518ad.png)

**Comment by tomolimo** [comment]
Thank you,
The issue may come fro an incompatibility of languages between PM server languages and GLPI languages.
Could you paste a screen shot of the languages settings of PM server and of GLPI?

**Comment by tomolimo** [comment]
Thank you,
The issue may come fro an incompatibility of languages between PM server languages and GLPI languages.
Could you paste a screen shot of the languages settings of PM server and of GLPI?

**Comment by SneakyNuke** [comment]
For PM
![image](https://user-images.githubusercontent.com/51399245/166901759-88474cb3-55ba-4944-917c-c07085d444fb.png)

I'm not sure about the GLPI languages param screen
![image](https://user-images.githubusercontent.com/51399245/166902650-19d90450-db1e-422f-a67f-0419c1317b80.png)

**Comment by tomolimo** [comment]
Ok for PM server
but for GLPI, it's in the 'Setup' > 'Default values', not in your own settings...

**Comment by SneakyNuke** [comment]
![image](https://user-images.githubusercontent.com/51399245/166918863-c320e7ca-fda6-4f65-99cc-50f2c5dfb738.png)

**Comment by tomolimo** [comment]
Hello @SneakyNuke 

I suggest you to switch GLPI to English for the **default** language, and to change to French for your own personnal settings.
And be sure that PM server **default** language is also English.
And retry the task import.

By the way could you post a screen copy of the process design?

Thank you,
Regards,
Tomolimo

**Comment by SneakyNuke** [comment]
GLPI
![image](https://user-images.githubusercontent.com/51399245/166922065-def92995-0cb6-4041-b8c0-0923350824e1.png)

PM
![image](https://user-images.githubusercontent.com/51399245/166922591-8f6bfdc5-4597-461d-824a-b2bd84c6e644.png)

Tasks are on GLPI !
![image](https://user-images.githubusercontent.com/51399245/166922288-b37775d4-e95c-4a2f-b606-d175eb1f9649.png)

Thank you very much for your help and your responsiveness !

I will try to put in French language by default on both applications

**Comment by tomolimo** [comment]
Hello @SneakyNuke 
You don't need to set default language to French, you can keep English, as users in GLPI can define their own settings, they may switch to french at any time, and the language used in PM server will be switched to french also for them. PM language used for visualization is the one set in the GLPI user's settings
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
In my company GLPI is in English and most of the users have set their language (more than 13 different languages)...

**Comment by SneakyNuke** [comment]
OK, thanks a lot for your help, on the other hand, I will open a new case about the assignment of a ticket to a process
