### ISSUE TITLE
Unable to assign a ticket to a case

### ISSUE THREAD

**Issue by SneakyNuke** [tomolimo/processmaker#151]
Hello again @tomolimo,

Impossible to assign a ticket to my case, there is nothing in the list
![image](https://user-images.githubusercontent.com/51399245/167087732-423628e7-4d70-43d3-a31e-29dd4260252c.png)

- No php-erros / sql-errors in files/_log
- No erros in console (F12)
- No php error

![image](https://user-images.githubusercontent.com/51399245/167087991-02ebdf34-d4dd-433f-ae0f-2ba711d75e3f.png)
![image](https://user-images.githubusercontent.com/51399245/167088078-7665bafd-fff8-44f7-890b-58fa0b4036c0.png)
![image](https://user-images.githubusercontent.com/51399245/167088019-996fa743-3ea4-46d9-bcb2-84cbd5c336b0.png)
![image](https://user-images.githubusercontent.com/51399245/167088135-837a3fea-36b2-4747-ad2b-fad21aa8ea03.png)

**Comment by tomolimo** [comment]
Hello @SneakyNuke 

Did you define the rights like described here: https://github.com/tomolimo/processmaker/wiki/Process-configuration#authorizations

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @SneakyNuke 
Got no news after last question.
Fill free to re-open if you have news for me.
Thank you,
Regards,
Tomolimo
