### ISSUE TITLE
Unable to connect from plugin to processmaker server on the same host

### ISSUE THREAD

**Issue by Wolvverine** [tomolimo/processmaker#152]
GLPI address: http://docker.some.wew:6080/
Processmaker server address: http://docker.some.wew:8090/

From glpi to Processmaker server telnet connection - work
From external network to Processmaker server connection - work
From glpi to Processmaker plugin to  Processmaker server - failed

![image](https://user-images.githubusercontent.com/5873929/167838373-328ce653-5e53-4ca5-a10a-d8286eeb4248.png)

Connections log on procesmaker-server:
from external:
10.0.1.254 - - [11/May/2022:15:18:21 +0000] "GET /skins/neoclassic/images/ext/gray/grid/refresh.gif HTTP/1.1" 499 0 "http://docker.domain.local:8090/css/neoclassic-extJs.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"

10.0.1.254 - - [11/May/2022:13:48:12 +0000] "GET /images/favicon.ico HTTP/1.1" 200 1162 "http://processmaker_test_pm.domain.local:8090/sys/en/neoclassic/login/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"

from Plugin with another hostname than glpi (alias in dns):

172.20.0.1 - - [11/May/2022:13:49:45 +0000] "GET /sysworkflow/en/glpi_classic/services/wsdl2 HTTP/1.1" 200 65959 "-" "-"
172.20.0.1 - - [11/May/2022:13:51:17 +0000] "GET /sysworkflow/en/glpi_classic/services/wsdl2 HTTP/1.1" 200 65959 "-" "-"

172.20.0.1 - internal docker host address

**Comment by Wolvverine** [comment]
PM server configuration is default - new instalation.

I completed above with logs.

![image](https://user-images.githubusercontent.com/5873929/167889323-66fa9895-9cc5-4eb7-8153-85a482d56687.png)
![image](https://user-images.githubusercontent.com/5873929/167889690-1d6c9fd7-a1d7-494b-8430-ef5c6ace3d1d.png)
![image](https://user-images.githubusercontent.com/5873929/167890328-54b12fe7-836a-46ae-aa82-29e290740b72.png)

**Comment by tomolimo** [comment]
Hello @Wolvverine 
When you wrote "default installation": did you follow the wiki for the configuration of the PM server (https://github.com/tomolimo/processmaker-server/wiki)?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
So you've got an error with the mysql connection...

**Comment by Wolvverine** [comment]
![image](https://user-images.githubusercontent.com/5873929/167909272-8b7a2bd7-60b4-4621-a7e9-07f68bf89a92.png)
![image](https://user-images.githubusercontent.com/5873929/167909490-9552f279-dbe6-4c2c-95e2-9b5547af5540.png)
![image](https://user-images.githubusercontent.com/5873929/167909777-389510d8-907e-4b80-a345-599dacccd056.png)

**Comment by Wolvverine** [comment]
Does the plugin have a problem if the processmaker server address is the same as the glpi server address and they only differ in port?

**Comment by Wolvverine** [comment]
Which file is that?

**Comment by tomolimo** [comment]
Seems like there is a bug in Pm serve when SQL user password has special chars. Try changing the password of your SQL user to a more simple one (just letters and digits), see reference here: https://forum.processmaker.com/viewtopic.php?t=708638

**Comment by Wolvverine** [comment]
After changing the password, the error disappeared, unfortunately, the connection from GLPI to ProcessMaker server is still missing.

When tcpdump is connected, I can see traffic between base and GLPI, but there is no outgoing connection to the processmaker server from GLPI.

**Comment by tomolimo** [comment]
On GLPI side did you add the PHP soap module?

**Comment by Wolvverine** [comment]
Yes:
 
```
Operating system: Linux f1d5d758dc0f 4.18.0-365.el8.x86_64 #1 SMP Thu Feb 10 16:11:23 UTC 2022 x86_64
PHP 7.4.28 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, cgi-fcgi, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_sqlite, posix, readline, session, snmp, soap, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip,
	zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.20.2
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Server Software: mariadb.org binary distribution
	Server Version: 10.7.3-MariaDB-1:10.7.3+maria~focal
	Server SQL Mode: 
	Parameters: root@mariadb_test_pm/glpi_test_pm
	Host info: mariadb_test_pm via TCP/IP
```

Dump for config variable:

`object(PluginProcessmakerConfig)#53 (15) { ["fields"]=> array(21) { ["id"]=> int(1) ["name"]=> string(12) "ProcessMaker" ["pm_server_URL"]=> string(28) "http://docker.6domainname.wew:8090" ["pm_workspace"]=> string(8) "workflow" ["pm_admin_user"]=> string(5) "admin" ["pm_admin_passwd"]=> string(72) "xxxxx" ["pm_theme"]=> string(12) "glpi_classic" ["date_mod"]=> string(19) "2022-05-13 11:23:30" ["taskcategories_id"]=> NULL ["users_id"]=> int(2) ["pm_group_guid"]=> string(1) "0" ["comment"]=> NULL ["pm_dbserver_name"]=> string(20) "mariadb_test_pm:3306" ["pm_dbname"]=> string(11) "wf_workflow" ["pm_dbserver_user"]=> string(5) "admin" ["pm_dbserver_passwd"]=> string(72) "xxxxxxx" ["domain"]=> string(16) "docker.6domainname.wew" ["maintenance"]=> int(0) ["ssl_verify"]=> int(0) ["db_version"]=> string(5) "4.0.0" ["max_cases_per_item"]=> int(0) } ["dohistory"]=> bool(false) ["history_blacklist"]=> array(0) { } ["auto_message_on_action"]=> bool(true) ["no_form_page"]=> bool(false) ["additional_fields_for_dictionnary"]=> array(0) { } ["fkfield":protected]=> string(0) "" ["searchopt":protected]=> bool(false) ["taborientation"]=> string(8) "vertical" ["get_item_to_display_tab"]=> bool(true) ["usenotepad":protected]=> bool(false) ["notificationqueueonaction"]=> bool(false) ["type":protected]=> int(-1) ["displaylist":protected]=> bool(true) ["showdebug"]=> bool(false) }`

**Comment by tomolimo** [comment]
Questions:
1. Does the host name known via DNS? If you do a ping to it, how is it answering?
2. I can propose to add some logs into the PM plugin source code, are you ready for that?

**Comment by tomolimo** [comment]
It behaves like if something was preventing SOAP calls from GLPI source code to PM server

**Comment by Wolvverine** [comment]
1. Yes, Ping answers correctly.
2. Yes

**Comment by tomolimo** [comment]
First: there is a small SOAP tester in PM server (but not sure that I've packaged it with the custom release): could you check if you have the following files in the `workflow/engine/methods/setup/` folder (on PM server)?
1. webServices.php
2. webServicesAjax.php
3. webServicesList.php

if not, I'll send them to you

**Comment by Wolvverine** [comment]
I do not have them.

**Comment by tomolimo** [comment]
here they are:
[webServices.zip](https://github.com/tomolimo/processmaker/files/8686148/webServices.zip)

**Comment by tomolimo** [comment]
these files were available in the PM 2.x releases but no more in the 3.x releases as the SOAP interface (even is still available) is no longuer maintained in the 3.x releases.

**Comment by tomolimo** [comment]
as soon as you have put these files into the PM folders, then we can start a small test
goto http://pm host name/sysworkflow/en/neoclassic/setup/webServices 
it will request your PM login, enter any PM user with PROCESSMAKER_ADMIN rights
and then you should land on this page:
![image](https://user-images.githubusercontent.com/7569958/168263924-f67ab3fb-32ab-40ac-9985-572082522898.png)
I'm running https, but it's not neccessary

**Comment by tomolimo** [comment]
From here, if needed, you may change the Setup, but probably you don't need to.
1. click on the Login [Test], enter the credentials you used in the PM plugin configuration in GLPI (admin/xxxxx), And then you should get: 
![image](https://user-images.githubusercontent.com/7569958/168264568-7336cf2f-504b-46ed-b2cb-15df073feb60.png)
This means that your PM admin user is correctly logged into PM server via SOAP
2. then you  may test the RoleList and you should get: 
![image](https://user-images.githubusercontent.com/7569958/168264836-3bf40e2f-abc2-4e5e-83a3-1ea798b1135e.png)


You cannot test all the functions as for some, there is no data, as your PM server instances is new.
But at least with the login and the role list, it shows if the SOAP interface is correctly set on the PM server

**Comment by Wolvverine** [comment]
![image](https://user-images.githubusercontent.com/5873929/168265340-3b7288fd-3a40-4b2c-991e-79b042ac7a96.png)

**Comment by tomolimo** [comment]
you may change the Setup by a click the Setup

**Comment by tomolimo** [comment]
but I'm pretty sure that there is something wrong in the nginx confiiguration

**Comment by tomolimo** [comment]
did you follow this: https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules?

**Comment by Wolvverine** [comment]
open setup:
![image](https://user-images.githubusercontent.com/5873929/168265861-2e1e55cf-bc27-4118-9d60-2364c298ab14.png)
Change:
![image](https://user-images.githubusercontent.com/5873929/168266096-fa4cb2ca-a8d9-4543-9aa6-dcab0507cd38.png)
efect:
![image](https://user-images.githubusercontent.com/5873929/168266262-8b4bda72-d71e-4319-844e-64f61ad72c8a.png)

**Comment by Wolvverine** [comment]
after login test:
![image](https://user-images.githubusercontent.com/5873929/168266489-bcf09011-d613-44cc-b223-6c873e483a0a.png)

**Comment by tomolimo** [comment]
did you follow this: https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules?

**Comment by Wolvverine** [comment]
This:
https://github.com/tomolimo/processmaker-server/wiki/Nginx

Server_name declaration was lost. Now is ok.

![image](https://user-images.githubusercontent.com/5873929/168269247-36ffaef3-014d-43fb-acc8-f9b3e4cbbc87.png)
![image](https://user-images.githubusercontent.com/5873929/168269448-8d53f503-ca3f-434a-8b24-847f0fef8be7.png)

**Comment by Wolvverine** [comment]
It seems there was a problem here.
Now they see each other at GLPI.

**Comment by Wolvverine** [comment]
The question is whether it is possible to replace this declaration with a universal entry for different servers and domains?

**Comment by tomolimo** [comment]
which declaration?
