### ISSUE TITLE
Private comment

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#153]
**Describe the bug**
@tomolimo , Hi! 

@@GLPI_ITEM_FOLLOWUP_IS_PRIVATE = 1;

Is doesn't work or am I doing something wrong?

**Screenshots**

![image](https://user-images.githubusercontent.com/16879167/168055969-4b4e5c05-06aa-4450-bb3c-5d6ce08fd208.png)
![image](https://user-images.githubusercontent.com/16879167/168056054-dc678530-7d37-423d-b84e-9747640387a5.png)
![image](https://user-images.githubusercontent.com/16879167/168056140-bc96f236-5350-42d6-9c03-f0e61521f597.png)
![image](https://user-images.githubusercontent.com/16879167/168056289-a02b01e2-e1f0-4a62-9fa2-6063912bae48.png)

**Desktop (please complete the following information):**

GLPI 9.5.7

processmaker Name: Process Maker Version: 4.0.11 State: Enabled

ProcessMaker Ver. 3.3.0-community-RE-1.7

[Копия_Tutorial_1_2022_04_13_19_03_28-1.zip](https://github.com/tomolimo/processmaker/files/8677422/_Tutorial_1_2022_04_13_19_03_28-1.zip)

**Comment by tomolimo** [comment]
Hello @kofe88 
I beleive there is a bug (a wrong copy/paste) in the code.
Could you check in processmaker.class.php line 157?
There is the line:
`      if (isset( $txtForFollowup['GLPI_ITEM_FOLLOWUP_IS_PRIVATE'] ) && $txtForFollowup['GLPI_TICKET_FOLLOWUP_IS_PRIVATE'] != "") {
`
But it should be:
`      if (isset($txtForFollowup['GLPI_ITEM_FOLLOWUP_IS_PRIVATE']) && $txtForFollowup['GLPI_ITEM_FOLLOWUP_IS_PRIVATE'] != "") {
`
Could you change it on your system and test again ?

Thank you,
Regards,
Tomolimo

**Comment by kofe88** [comment]
@tomolimo Hello! I change this line, now work correct, thank you!)
![image](https://user-images.githubusercontent.com/16879167/168231347-115587d6-46fe-492b-80f3-093534b491e2.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
I will do a new release with this fix :)
Thank you for the test.
Regards,
Tomolimo
