### ISSUE TITLE
link glpi with processmaker (processmaker plugin configuration )

### ISSUE THREAD

**Issue by anassaoud1** [tomolimo/processmaker#156]
what should i do next

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/233790755-437a4c78-f215-4209-a1b7-2bd35a18a873.png)

**Comment by anassaoud1** [comment]
i m using the right info but he can t deteect it

**Comment by anassaoud1** [comment]
processmakeer system information didn't show up

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234249340-466237a8-fb33-4555-b428-4d1c7ac3a2e4.png)

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234249689-75ed6bcb-94d6-44d1-b6a7-cbed92de2935.png)

**Comment by anassaoud1** [comment]
what should i do in the setting i need to create it in glpi or on processmaker

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234278641-c32c366a-0bc6-4fbd-a70b-53e92b54a9c4.png)

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234278760-45a4f798-420b-47bf-a2fe-62929c281b95.png)

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234281637-c2f8dabd-30ee-4034-88cb-26563457ae40.png)

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234281921-d524a7f2-470a-447d-b0ca-fecbac2075b4.png)

**Comment by anassaoud1** [comment]
![image](https://user-images.githubusercontent.com/130109126/234282011-a9881780-bdb5-4064-9046-4ec5408c1547.png)

**Comment by tomolimo** [comment]
Hello @anassaoud1 
I was pretty sure of that: you didn't respect the installation wiki: [https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation)...
Could you review it and do only what is shown in it?
Thank you
regards,
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
ur proceesmaker-server doesn t work and the wiki doesn t contien all the information we need a processmaker instalation for not missing any thing a part of that i just apply all that i see in the wiki

**Comment by tomolimo** [comment]
Hello @anassaoud1,

Sorry for being late to answer (I was in holidays these last days).

Just for your information: this customized PM server, PM plugin and GLPI have been running on a lot of GLPI installations around the world for at least 7 years...

Sorry to hear that you were not able to setup a running PM server: tell me what's wrong, and I'll help you.

Post here your configuration for server system, and for PM server itself?
At least, did you check the PHP error files? Could post here the error messages?

Thank you,
Regards,
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
my glpi lag so hard wheen i activvate processmaker plugin my glpi dosnt work any more 
unti i delete the processmaker plugin

**Comment by anassaoud1** [comment]
@tomolimo 
PHP Warning (2): SoapClient::SoapClient(): I/O warning : failed to load external entity "http://192.168.250/7/sysworkflow/fr/glpi_neoclassic/services/wsdl2" in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php at line 211

**Comment by tomolimo** [comment]
Hello @anassaoud1 
Could you post the configuration of PM server, PM plugin and GLPI, and also installed versions?
Thank you,
Regards
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
the pm server not ye linked with glpi 
i just have issues with the activation of pm plugin in glpi 
the proceess maker plugin is the last version 4.0.11
and glpi is 9.5.7

**Comment by anassaoud1** [comment]
@tomolimo 
wich configuration

**Comment by tomolimo** [comment]
> @tomolimo
wich configuration

Hello @anassaoud1 
Configuration of GLPI, PM server, and PM plugin
Thank you,
Regards,
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
![image](https://github.com/tomolimo/processmaker/assets/130109126/640c3c2e-4df0-4768-b7bc-3d4e738ed4a8)

**Comment by anassaoud1** [comment]
![image](https://github.com/tomolimo/processmaker/assets/130109126/1063c237-fcb5-472b-8fe9-bb93bf1b0ea0)

**Comment by anassaoud1** [comment]
![image](https://github.com/tomolimo/processmaker/assets/130109126/31749fde-b328-4e73-84b0-6053dc186526)

**Comment by anassaoud1** [comment]
![image](https://github.com/tomolimo/processmaker/assets/130109126/2083aeaf-966b-4bc9-8432-7e1ad708f46b)

**Comment by anassaoud1** [comment]
![Capture d’écran (31)](https://github.com/tomolimo/processmaker/assets/130109126/72cd31a5-7b2e-4fc6-bf12-54271619ae94)

**Comment by anassaoud1** [comment]
@tomolimo 
i don t think we need this the problem is betwen glpi and processmaker plugin the pmserver still away 
it s compatibility problem or what ?
i have this error msg when i active processmaker plugin for thee first time
PHP Warning (2): SoapClient::SoapClient(): I/O warning : failed to load external entity "[http://192.168.250/7/sysworkflow/fr/glpi_neoclassic/services/wsdl2](http://192.168.0.250/7/sysworkflow/fr/glpi_neoclassic/services/wsdl2)" in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php at line 211

**Comment by tomolimo** [comment]
Hello @anassaoud1,

**You have a problem with the PM server version you've installed.**
The only version that is compatible with GLPI is the 3.3.0-Community-RE-1.10

The release that **MUST** be installed **MUST** be downloaded from here: https://github.com/tomolimo/processmaker-server/releases/tag/3.3.0-RE-1.10
And you **MUST** follow the wiki here: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation

By the way, I'm preparing a 3.8.2-community-RE1.0 release that will be available in several months.

If you need help, I can help for the setup of the PM server, and PM plugin. If neccessary I can also do it remotely, just tell me.

Thank you,
Regards,
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
 tanks but glpi dnt know the processmaker server yet i have an issues with the processmaker plugin

**Comment by anassaoud1** [comment]
@tomolimo 
Trying to access array offset on value of type bool in /opt/processmaker/workflow/public_html/sysGeneric.php on line 483
thats what happen when i install pm server 3.3.0

**Comment by tomolimo** [comment]
Hello @anassaoud1 
Could you post the PM server configuration screencopies?
Thank you
Regards,
Tomolimo

**Comment by anassaoud1** [comment]
@tomolimo 
should i use the same user in both glpi and processmaker or use a differents

**Comment by anassaoud1** [comment]
![image](https://github.com/tomolimo/processmaker/assets/130109126/efff67d3-6e18-4caa-a8ab-e6f37fe9c118)

**Comment by anassaoud1** [comment]
@tomolimo 
and what should i do here in this step

**Comment by tomolimo** [comment]
Hello @anassaoud1 
Juste press "Finish" ...

**Comment by tomolimo** [comment]
BUT did you respect the following steps?
https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation#as-a-global-instruction-list-you-may-follow-these

**Comment by anassaoud1** [comment]
@tomolimo 

what choises should i take

**Comment by anassaoud1** [comment]
@tomolimo  
i m stuck in this 
i can give u in remote access to check

**Comment by tomolimo** [comment]
> @tomolimo i m stuck in this i can give u in remote access to check

Hello @anassaoud1, you may contact me on Discord: Tomolimo#1077

**Comment by tomolimo** [comment]
Hello @anassaoud1 
Close, as ther eis no more post on it.
You may feel free to open a new one.
Thank you,
Regards,
Tomolimo
