### ISSUE TITLE
ProcessMaker GLPI

### ISSUE THREAD

**Issue by wessrafamessi** [tomolimo/processmaker#162]
Hello,

I want to initiate my workflow using ProcessMaker integrated with GLPI, using the leave request as an example (where a user can initiate their request, which then goes through their hierarchical superior before reaching the Director of Human Resources).

Can you confirm if ProcessMaker integrated with GLPI can meet my requirements? If so, is the interface presented to the requester within ProcessMaker, or does the process begin with the creation of a ticket in GLPI by the user , followed by the initiation of the process configured on the ProcessMaker server?

Best regards

**Comment by tomolimo** [comment]
Hello @wessrafamessi 
Yes, PM + GLPI can answer your requirements.
Yes, a case (= a process instance) has to be hosted by a Ticket (can also be or a Change, or a Problem)
So there are two possibilities:

1. either create a ticket, and then add to it a process case (via central interface)
2. or either directly create a ticket with a process case already initiated (via simplified interface)

You may check the wiki here: for central interface: https://github.com/tomolimo/processmaker/wiki/Tutorial-1 (see from step 5)
And for simplified interface: https://github.com/tomolimo/processmaker/wiki/Tutorial-2 (from step 5 also)

Thank you,
Regards,
Tomolimo

**Comment by wessrafamessi** [comment]
Hello,

Thank you for your response to the previous questions.

 Does ProcessMaker allow us to generate a report of the actions performed in the workflow?

Best regards

**Comment by tomolimo** [comment]
Hello @wessrafamessi 
It can be done via GLPI, as the tasks in PM are reflected with tasks in GLPI (in a ticket, a change or a problem), so you don'"t need to generate a report. See: https://github.com/tomolimo/processmaker/wiki
Thank you
Regards,
Tomolimo

**Comment by wessrafamessi** [comment]
Here are the questions I would like you to help me understand:

 ### 1) Could you demonstrate the ProcessMaker workflow, if you have an example? (For instance, a report or the creation of a new ticket to trigger the workflow.)

### 2) How can the user trigger the workflow? (Specifically, how the process will be added during ticket creation.)

I apologize if my request may come across as intrusive, but this is my first project in this field, and I want to ensure that I have a good grasp of these crucial aspects for the project launch. Your expertise would be of great value to me, and I would be extremely grateful if you could assist me in clearing these uncertainties.

I am open to any form of communication that works best for you, whether it be an in-person meeting, a phone conversation, or an email response.

**Comment by tomolimo** [comment]
Hello @wessrafamessi 
Did you take a deep look into the wiki?
If yes, and if you still have questions, we may plan a video meeting.
Thank you,
Regards,
Tomolimo

**Comment by wessrafamessi** [comment]
Bonjour,

Est-ce que on peut planifier une conférence teams si vous êtes disponible !?
Cordialement

**Comment by wessrafamessi** [comment]
Hello

Can we may plan a video meeting.!

Best regards

**Comment by tomolimo** [comment]
Hello @wessrafamessi 
Please join me on Discord (Tomolimo). We'll plan a meeting from there.
Thank you
