### ISSUE TITLE
TICKET-PROCESSMAKER

### ISSUE THREAD

**Issue by wessrafamessi** [tomolimo/processmaker#164]
Hello 
### "How can a user initiate a ticket using the ProcessMaker workflow? What are the steps for opening the ticket in which the workflow is integrated?"

Regards

**Comment by tomolimo** [comment]
Please read the tutorial: https://github.com/tomolimo/processmaker/wiki/Tutorials

**Comment by tomolimo** [comment]
Hello @wessrafamessi 
I close the issue, as there is no post since a long time, but feel free to re-open if you have questions.
Thank you
Regards,
Tomolimo
