### ISSUE TITLE
fail installation on GLPI 10.0.10 Ubuntu Server

### ISSUE THREAD

**Issue by ofprieto** [tomolimo/processmaker#166]
the documentation have a problem:
![imagen](https://github.com/tomolimo/processmaker/assets/4383194/1a33cabe-a3a4-44c9-8a0e-5c02dde3a6a9)

what is the correct form to new versions?

**Comment by tomolimo** [comment]
Hello @ofprieto 
Could you explain the issue?
For me there is no problem when accessing the latest release...
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
I closed this issue as I got no answer.
Feel free to re-open it providing the requested answers.
Thank you,
Regards
Tomolimo
