### ISSUE TITLE
GLPI plugin doesn't get PM groups

### ISSUE THREAD

**Issue by jsamaniegog** [tomolimo/processmaker#17]
PM Server: 3.0.1.8-RE-1.6
PM Plugin: 3.1.3

Hello,

i get the same error of this issue: https://github.com/tomolimo/processmaker/issues/14
i've locate the error debbuging the code, the problem is the lang in the line 294

`$query = "SELECT DISTINCT CON_ID, CON_VALUE FROM CONTENT WHERE CON_CATEGORY='GRP_TITLE' AND CON_LANG='".$pm->lang."' ORDER BY CON_VALUE;";`

i get this: ... CON_LANG='**es**' ...
instead of: ... CON_LANG='**en**' ...

Regards.

**Comment by tomolimo** [comment]
Hello,
Currently there is fallback language implemented in the plugin, but it doesn't work for the group choice.
You need to use English for the configuration of this group.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
And your trouble is not the same than #14 as it was not a problem of languages, but of table names that were uppercase in the DB and lowercase in my code (which is no longer the issue)

**Comment by tomolimo** [comment]
I'm going to check this issue of fallback language and I'll provide a fix asap.

**Comment by jsamaniegog** [comment]
You're right.

Also when I try to synchronize the tasks I get this error:
PHP Fatal error:  Call to undefined function locale_get_primary_language() in /var/www/html/glpi/plugins/processmaker/inc/process.class.php on line 67

**Comment by tomolimo** [comment]
could you check if any error are present in the log files?

**Comment by jsamaniegog** [comment]
[Tue May 09 08:59:53.212956 2017] [:error] [pid 15143] [client 10.40.84.206:36280] PHP Fatal error:  Call to undefined function locale_get_primary_language() in /var/www/html/glpi/plugins/processmaker/inc/process.class.php on line 67
[Tue May 09 08:59:53.212956 2017] [:error] [pid 15143] [client 10.40.84.206:36280] PHP Stack trace:
[Tue May 09 08:59:53.212956 2017] [:error] [pid 15143] [client 10.40.84.206:36280] PHP   1. {main}() /var/www/html/glpi/plugins/processmaker/front/process.form.php:0
[Tue May 09 08:59:53.212956 2017] [:error] [pid 15143] [client 10.40.84.206:36280] PHP   2. PluginProcessmakerProcess->refreshTasks($post = *uninitialized*) /var/www/html/glpi/plugins/processmaker/front/process.form.php:20

that is all

**Comment by tomolimo** [comment]
Which version of PH do you use?

**Comment by jsamaniegog** [comment]
PHP 5.6.29

**Comment by tomolimo** [comment]
I found the root cause: you are missing the "intl" PHP module (see: http://php.net/manual/en/locale.getprimarylanguage.php)
I'll add this in the wiki,

**Comment by tomolimo** [comment]
wiki updated: https://github.com/tomolimo/processmaker/wiki/Requirements
thank you for your participation
regards,
Tomolimo

**Comment by tomolimo** [comment]
And for the issue of the group,
use this query:
`$query = "SELECT DISTINCT CON_ID, CON_VALUE FROM CONTENT WHERE CON_CATEGORY='GRP_TITLE'  ORDER BY CON_VALUE;";`
it will be ok, and I'll fix it in the next release of plugin,
thank you again for your participation,
regards,
Tomolimo

**Comment by jsamaniegog** [comment]
Thank you very much!

To synchronize the tasks I had to force the language, in process.class.php line 70:
`$lang = "en";`

**Comment by tomolimo** [comment]
You just need to change your language in GLPI interface, no need to modify any code :)

**Comment by jsamaniegog** [comment]
I had to change the default language to work, in Default values -> Personalization

**Comment by tomolimo** [comment]
You also need to set the translation for the dropdowns: see https://github.com/tomolimo/processmaker/wiki/Requirements

**Comment by tomolimo** [comment]
> I had to change the default language to work, in Default values -> Personalization

Exact you don't need to change your own language settings BUT the GLPI default one

**Comment by tomolimo** [comment]
>  Exact you don't need to change your own language settings BUT the GLPI default one

In fact it should not be mandatory if the GLPI default language was installed in PM server.
See: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration#localization-internationalization-languages

**Comment by jsamaniegog** [comment]
Ok, thank you tomolimo
