### ISSUE TITLE
error when creating glpi_plugin_processmaker_documents tableYou have an error in your SQL syntax

### ISSUE THREAD

**Issue by HamzaG-ui** [tomolimo/processmaker#174]
I am currently facing an issue while attempting to install the ProcessMaker plugin 5.03 for GLPI. The error I encounter is as follows:

"Error when creating glpi_plugin_processmaker_documents table: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 15."

Here are the details of my environment:

GLPI Version: 10.0.6
PHP Version: 8.2.2
MySQL Version: 8.2 (upgraded from 5.7 )

I recently upgraded MySQL from version 5.7 to 8.2, suspecting that the issue might be related to the outdated MySQL version. However, the problem persists even after the upgrade.

Could you please assist me in resolving this issue?

**Comment by HamzaG-ui** [comment]
I'm installing the ProcessMaker plugin from scratch, not upgrading.

**Comment by tomolimo** [comment]
Hello @HamzaG-ui 

I beleive, I found the root cause: in the `plugins/processmaker/install/update_4_0_0_to_4_0_1.php` file could you delete the `DEFAULT` string on line 46, and try again?

Thank you
Regards,
Tomolimo

**Comment by HamzaG-ui** [comment]
Issue resolved! Deleting the DEFAULT string on line 46 did the trick. Thanks for your quick help!

**Comment by tomolimo** [comment]
You're welcome
