### ISSUE TITLE
Database Connection Issue in ProcessMaker Server

### ISSUE THREAD

**Issue by Monta94** [tomolimo/processmaker#176]
I am currently facing a database connectivity issue while configuring ProcessMaker Server running on IIS . Despite confirming the correctness of the username and password by successfully connecting through MySQL Workbench, I encounter the following error during the ProcessMaker pre-installation database configuration:

"Connection Error: unable to connect to MySQL using provided credentials."

![11](https://github.com/tomolimo/processmaker/assets/108869659/f46e5737-01b6-4274-9969-89a8d4292d65)

I have attempted the configuration on both MySQL versions 5.7 and 8.2 without success.

Here are the details of my environment:

-GLPI 10.0.6
-PHP Version 7.1
-MYSQL Version 8.2
-Process maker Release 3.3.0-community-RE-2.3

 Your assistance in resolving this matter would be greatly appreciated.

**Comment by tomolimo** [comment]
Hello @Monta94 
As emplained in the wiki (here: https://github.com/tomolimo/processmaker-server/wiki/PHP-and-MySQL-compatibility and here: https://wiki.processmaker.com/3.3/ProcessMaker_Installation_Requirements) , PM 3.3.0 is only compatible with MySQL 5.7, and not yet with MySQL 8.x
You must use a MySQL 5.x (or equivalent MariaDB version)

Thank you
Regards,
Tomolimo
