### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jorge-madrigal** [tomolimo/processmaker#177]
Hello @tomolimo:

A question, not a issue. Is it possible to open a process with an anonymous user?
Or open a process with a default user when the user is not logged into GLPI.

How would it be done?

We use processmaker with formcreator. Formcreator allows public forms, without the user having logged in to GLPI.

For example: a person external to the organization who does not have a GLPI user, who could open a process without logging into GLPI.

Thank you
Jorge Madrigal

**Comment by tomolimo** [comment]
Hello @jorge-madrigal 

In fact you always need a user to start a process case, but if you combine this feature (https://github.com/tomolimo/processmaker/wiki/Automatic-start-of-cases) with the use of a dedicated ticket writer then you should be able to start a process at ticket creation even if the requester is anonymous.

You just need to have a dedicated user who's going to be used as ticket writer (this is not he ticket "Requester", but the ticket "By"). This user must be existing in PM server (GLPI<->PM synchro, see automatic cron pmusers), and this user must have the right (depending on profile + entities) to start the needed process, and it must be in the "Assignment Rules" of the process first task.

Thank you,
Regards,
Tomolimo

**Comment by jorge-madrigal** [comment]
Hello @tomolimo:

I use formcreator in the following way. I create a form with a hidden section called processmaker. In the processmaker section I introduce 4 hidden fields; type, itilcategories_id,_from_helpdesk,entities_id. Shown in the image:

![image](https://github.com/tomolimo/processmaker/assets/66475507/5ef2e4e3-8b21-44f1-8fb0-f2ed3c920d10)

I have modified formcreator (file userform.html.twig) so that, if it detects a section called processesmaker, the submitredirects to processmaker/front/tracking.inyector.php. Then processmaker plugin comes into action.

The above works perfectly.

My idea is to launch a public form without a user having logged in to GLPI. As you say, I want to use  a dedicated user who will be used as a ticket writer.

I will try what you say, entering ##TicketProcess: #xxxxxxxxxxxxxxxx## in the description of the template associated with the process of the processmaker plugin.

Thank you
Jorge

**Comment by jorge-madrigal** [comment]
Hello @tomolimo:

It's not as easy as I thought. I will continue testing, if at any time I find a solution, I will publish it in this section.

Thank you
Regards,
