### ISSUE TITLE
hi. Is there an installation instruction?

### ISSUE THREAD

**Issue by alekseyengfas** [tomolimo/processmaker#178]
Is there an instruction for installing and operating the plugin? Is there a usage example?

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
Please read the wiki https://github.com/tomolimo/processmaker/wiki
Thank you,
Regards,
Tomolimo

**Comment by alekseyengfas** [comment]
Thank you.
I have a GLPI server (nginx+php 8.1)
1. Unpacked the archive with the server.
2. Created a configuration file in Nginx according to the instructions. (https://github.com/tomolimo/processmaker-server/wiki/Nginx)
3. changed the configuration to PHP 8.1
4. Corrected a couple of errors with parentheses.

An empty page opens for me at http://my_erver:8090/sysworkflow/en/neoclassic/login/login:

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
Did you read this in the wiki?
https://github.com/tomolimo/processmaker-server/wiki/PHP-and-MySQL-compatibility
Thank you
Regards,
Tomolimo

**Comment by alekseyengfas** [comment]
started, thank you.
the page has now opened: Step 1 of 5: Pre-installation check
but everything is shifted

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
What do you mean by "shifted"?
You may post a screen copy?
Thank you,
Regards,
Tomolimo

**Comment by alekseyengfas** [comment]
![image](https://github.com/tomolimo/processmaker/assets/134517557/5b2c4a4f-3dd0-4668-85b4-da3d7a314b60)

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
This is an issue with CSS...
What's your browser?
Could you try to pruge your browser cache?
...
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
PS: are you sure that it is using PHP7.1?

**Comment by alekseyengfas** [comment]
cleared cache, doesn't help

**Comment by tomolimo** [comment]
Could you also check thePHP error logs?

**Comment by alekseyengfas** [comment]
my conf nginx:
__________________
server {
    listen 80;
    listen [::]:80;

    server_name glpi-test.local;

    root /var/www/glpi/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php$ {
        # the following line needs to be adapted, as it changes depending on OS distributions and PHP versions
        fastcgi_pass unix:/run/php/php-fpm.sock;

        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

server {
    listen       8090;
    server_name  glpi-test.local;
    root         /opt/processmaker/workflow/public_html;


    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    rewrite ^/.*/(.*)$ /glpi/app.php last;

    location ~ [^/]\.php(/|$) {
            # regex to split $uri to $fastcgi_script_name and $fastcgi_path
            fastcgi_split_path_info ^(.+\.php)(/.+)$;

            # Check that the PHP script exists before passing it
            try_files $fastcgi_script_name =404;

            fastcgi_pass unix:/run/php/php7.1-fpm.sock;

            include fastcgi.conf;

            # Bypass the fact that try_files resets $fastcgi_path_info
            # # see: http://trac.nginx.org/nginx/ticket/321
            set $path_info $fastcgi_path_info;
            fastcgi_param PATH_INFO $path_info;

            # allow directory index
            fastcgi_index index.php;
     }

**Comment by alekseyengfas** [comment]
There is no error in the logs.
I use Edge in Mozilla.
Edge shows an error (press F12):
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.

**Comment by alekseyengfas** [comment]
I sorved problem : apt-get install php7.1-mysql php7.1-gd php7.1-ldap php7.1-curl php7.1-cli php7.1-mcrypt

**Comment by alekseyengfas** [comment]
I launched the PM server, but when I turn on the plugin in GLPI, GLPI itself does not work. Shows white page

**Comment by alekseyengfas** [comment]
I sorved problem: apt-install php8.1-soap.
Thank you ^)
