### ISSUE TITLE
not install plugin for GLPI

### ISSUE THREAD

**Issue by alekseyengfas** [tomolimo/processmaker#179]
Hello,
help me please, I have:

GLPI version: 10.0.11
PHP for GLPI: 8.1
DB: MangoDB
Web: Nginx

input logging nginx:
[error] 28221#28221: *231 FastCGI sent in stderr: "PHP message: PHP Warning:  plugin_version_processmaker-5.0.3 method must be defined! in /var/www/glpi/src/Plugin.php on line 1810" while reading response header from

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
The issue is from the folder name you have used to copy the processmaker plugin...
It must be named like other plugins:
_glpi_folder_/plugins/processmaker/...
You probably named it like 
_glpi_folder_/plugins/processmaker-5.0.3/...
Thank you,
Regards,
Tomolimo

**Comment by alekseyengfas** [comment]
yes, working. Thank you

**Comment by alekseyengfas** [comment]
a plugin appeared, I installed it, but when I turned on the plugin, glpi stopped working. White page.
If you remove the plugin, GLPI will work again

**Comment by alekseyengfas** [comment]
*203 FastCGI sent in stderr: "PHP message: PHP Warning:  Unable to load plugin "processmaker" information. in /var/www/glpi/src/Plugin.php on line 626" while reading response header from upstream

**Comment by tomolimo** [comment]
Did you install the PM server first?
Did you configure it as it is explained in the wikis?

**Comment by alekseyengfas** [comment]
oh, sorry. I think the plug is inserted independently.
I can’t deploy the server, the installation page is displayed incorrectly
