### ISSUE TITLE
template

### ISSUE THREAD

**Issue by alekseyengfas** [tomolimo/processmaker#180]
is there a ready-made template for the sequential ticket approval process?

maybe there are ready-made templates for tickets?

**Comment by tomolimo** [comment]
Hello @alekseyengfas 
The answer is no.
There is an example which is provided with the plugin itself in the _samples_ folder (Credit_Card_Application.pmx).
There are 2 tutorials in the wiki, one for central interface and one for simplified interface (helpdesk).
Thank you
Regards,
Tomolimo

**Comment by Jish-FM** [comment]
Hello @tomolimo ,
Firstly, thank you very much for this plugin.
Is it possible to create sequential approval processes using this plugin? . How can we achieve this if yes.

**Comment by tomolimo** [comment]
Hello @Jish-FM,
Yes, it is possible (this is one of the goals for using ProcessMaker).
Everything is explained in the wiki, see: https://github.com/tomolimo/processmaker/wiki
If you need more support, please contact me on Discord: tomolimo
Thank you
Regards,
Tomolimo
