### ISSUE TITLE
WHITE PAGE PROBLEM WITH ACTIVATION OF processmaker-5.0.3 ON GLPI 10 

### ISSUE THREAD

**Issue by nonymous01** [tomolimo/processmaker#181]
hi everyone please help me i just installed glpi 10 on my computer and i downloaded the processmaker-5.0.3 , i configure it to have access to my glpi interface , i manage to install it , after the installation if i activate it all my page becomes white , please help me. here are the captures
![Arc 2024-05-23 12_53_02](https://github.com/tomolimo/processmaker/assets/141040978/3604e62b-71e6-4d41-a7c4-a647d2cfc6f7)

when I activate the page, it goes blank here's the capture too

![Arc 2024-05-23 12_55_42](https://github.com/tomolimo/processmaker/assets/141040978/f3452492-7df7-4d16-9609-ca1f1806b7b7)

**Comment by tomolimo** [comment]
Double post with, see: https://github.com/tomolimo/processmaker-server/issues/28
