### ISSUE TITLE
mon glpi plante apres installation du plugin

### ISSUE THREAD

**Issue by SABIBadr** [tomolimo/processmaker#182]
Bonjour tomolimo,

j'éspére que vous allez bien, petite question svp, je suis sous glpi version 10.0.15 (la derniére version du glpi), lorsque je télécharge votre plugin pour le tester dans mon environement et aprés un unzip du plugin dans le dossier /var/www/html/glpi/plugin. mon glpi plante et j'ai seulement une page blanche, est ce que j'ai raté quelque chose? 

Merci d'avance pour votre réponse.
Bien à vous

**Comment by tomolimo** [comment]
Hello @SABIBadr 
Please write in English, so that everybody can benefit of your question.
By the way, did you check the wiki of the PM plugin and the wiki of the PM server?
See: https://github.com/tomolimo/processmaker-server/issues/28
Thank you,
Regards,
Tomolimo
