### ISSUE TITLE
Can't sync tasks list

### ISSUE THREAD

**Issue by adilbouazzaoui** [tomolimo/processmaker#186]
Hello @tomolimo 

Now i'm at the Tutorial 1, i created the process and the task, and i can synchronize the process to glpi, but i'm not able to synchronize the tasks!
please help

Note: users are synchronised between glpi and processmaker.

thanks for the usuall support.

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
no errors in PM. but i see an error in GLPI logs :
<img width="947" alt="1" src="https://github.com/user-attachments/assets/36cdd4ce-d6db-4829-b36e-7bceccc4cff1">
<img width="338" alt="2" src="https://github.com/user-attachments/assets/bf1be4b1-04c9-4fc8-83de-0e560309d18a">

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
where can i find this setting? on GLPI or PM?

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
it is already de-activated:
<img width="590" alt="image" src="https://github.com/user-attachments/assets/0808f4ca-59a6-4005-a11c-339948088b7c">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Question: do you have this error if you disable the PM plugin?
I suspect the the MySQL version is too old for GLPI or for PM server: which MySQL version did you use?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I'm running MySQL 5.7.44 for PM server, and MySQL 8.0.37 for GLPI 10.0, and I don't have this issue...

**Comment by adilbouazzaoui** [comment]
I'm running MySQL 5.7.44 for PM server, and for GLPI 10.0.15 i think it's Mariadb, can you check this:

<img width="640" alt="1" src="https://github.com/user-attachments/assets/d7580a8f-50b6-495d-ad1a-1fae4f327f0a">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Question: do you have this error if you disable the PM plugin?
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
yes i still get these errors even if i disable the PM plugin
<img width="947" alt="image" src="https://github.com/user-attachments/assets/84c8093e-d894-4550-a14d-2bbefb48ef2d">

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
question 1: can you confirm that there is no replication issue between PM Mysql and GLPI Mariadb?
question 2: where can i post the issue? and what should i mention as an issue?

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
question 1: no replication issue as the the databases are not the same
question 2: on github GLPI issue list
