### ISSUE TITLE
Can't sync tasks list (issue persistent)

### ISSUE THREAD

**Issue by adilbouazzaoui** [tomolimo/processmaker#187]
Hello @tomolimo 
i posted the GLPI errors on github, and the issue was fixed, check below:
<img width="482" alt="image" src="https://github.com/user-attachments/assets/181df7fc-fa40-4dce-b81b-90480c2f70b1">

but i still can't Sync PM tasks!!!

please help

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
can you please help on this? we really need to make it work in order to make a decision about the solution.
you suppor is highly appreciated

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Could you check the PHP error logs: the one for GLPI and the one for PM?
Thank you,
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hello @tomolimo 
for PM there is no error:
<img width="367" alt="image" src="https://github.com/user-attachments/assets/61f85dfa-1686-4591-adf8-8a898e5bcef5">

and for GLPI also there is no error, just SSL warning:
<img width="941" alt="image" src="https://github.com/user-attachments/assets/97e81699-1966-422e-bae5-c5eadacea64e">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui n
Could you check that there is a defined path to file here:
![image](https://github.com/user-attachments/assets/ccc2909b-2993-44ac-997f-dfcae893cd62)

?
And could you check if there are errors in the error_log file?
If there is no filepath, then could you add one in the php.ini config file and then re-do a test and check again the error_log file?

Thank you
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
> Could post a screenshot of the PHP settings?

Hello @tomolimo 

here is the log location, it is the same log i shared previously:
<img width="742" alt="image" src="https://github.com/user-attachments/assets/27c19cfd-84b7-4df5-8fc1-d81c368d4f33">

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 
Thank you
Could we check the PM plugin configuration? Could you post screenshots?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @adilbouazzaoui 

I think hte issue is from the fact that the default language of GLPI doesn't match the language used in PM for the process creation.
Could you check GLPI default language, and post it here?
![image](https://github.com/user-attachments/assets/6340e3ba-915b-491d-becc-42e865a59bd8)


Thank you
Regards,
Tomolimo

**Comment by adilbouazzaoui** [comment]
Hi @tomolimo 
here are the plugin screenshots:
<img width="787" alt="image" src="https://github.com/user-attachments/assets/809bac6f-e439-4623-82a4-732c63bde831">
<img width="656" alt="image" src="https://github.com/user-attachments/assets/21d4bced-d3b3-4346-b621-46bd1ac2a08b">

**Comment by adilbouazzaoui** [comment]
this is GLPI default language:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/6a9d2051-536e-44fe-bec3-46e9de02dbb9">

**Comment by adilbouazzaoui** [comment]
i changed the default language to english and now i'm able to sync tasks.
thank you so much @tomolimo for the great support.
<img width="723" alt="image" src="https://github.com/user-attachments/assets/cb02e9aa-a857-465a-a8d3-4f6bfac8897a">
