### ISSUE TITLE
The second task in processmaker cannot be executed by the glpi user

### ISSUE THREAD

**Issue by yxing-hub** [tomolimo/processmaker#190]
Hello, I followed the steps to install processmaker and processmaker server, and it seems that user synchronization is also normal
 The first of my two tasks in processmaker server can be executed in glpi, but when the flow goes to the second task, glpi cannot perform any operations and can only view them.
I am confident that the permission configuration follows the instructions in the tutorial.
Looking forward to your reply. Thank you very much！
![20241211171559](https://github.com/user-attachments/assets/e2df949b-ceca-43c3-8128-27371233ded3)
![20241211171613](https://github.com/user-attachments/assets/06f1f2be-6661-44d3-b132-b316ec5bce2c)

**Comment by tomolimo** [comment]
Hello @yxing-hub 
Something went wrong...
Could you check PHP error log, SQL error log for PHP of PM server and for PHP of GLPI?
Thank you,
Regards,
Tomolimo

**Comment by yxing-hub** [comment]
I am very happy that you have replied to me. Below are the relevant logs. I look forward to receiving further guidance from you. Thank you very much！

### pm  php  error_log:
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  A non-numeric value encountered in /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php on line 283
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php:283) in /opt/nginx/html/processmaker/framework/src/Maveriks/WebApplication.php on line 238
[11-Dec-2024 16:48:39 Asia/Shanghai] PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/nginx/html/processmaker/vendor/luracast/restler/vendor/Luracast/Restler/CommentParser.php:283) in /opt/nginx/html/processmaker/workflow/engine/src/ProcessMaker/Services/OAuth2/Server.php on line 358
[11-Dec-2024 17:50:56 Asia/Shanghai] PHP Notice:  Undefined index: workspaceSkin in /opt/nginx/html/processmaker/workflow/public_html/glpi/app.php on line 114
[11-Dec-2024 17:50:56 Asia/Shanghai] PHP Notice:  Undefined index: workspaceSkin in /opt/nginx/html/processmaker/workflow/public_html/glpi/app.php on line 114
[11-Dec-2024 17:52:13 Asia/Shanghai] PHP Notice:  Undefined property: WsResponse::$caseId in /opt/nginx/html/processmaker/workflow/engine/methods/services/soap2.php on line 681
[11-Dec-2024 18:12:52 Asia/Shanghai] PHP Notice:  Undefined index: workspaceSkin in /opt/nginx/html/processmaker/workflow/public_html/glpi/app.php on line 114


### glpi php error log:

[2024-12-11 16:55:42] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144
  Backtrace :
  src/RuleTicketCollection.php:144                   in_array()
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 16:55:42] glpiphplog.WARNING:   *** PHP Warning (2): Cannot use a scalar value as an array in /var/www/html/glpi/src/RuleTicketCollection.php at line 148
  Backtrace :
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 17:49:45] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144
  Backtrace :
  src/RuleTicketCollection.php:144                   in_array()
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 17:49:45] glpiphplog.WARNING:   *** PHP Warning (2): Cannot use a scalar value as an array in /var/www/html/glpi/src/RuleTicketCollection.php at line 148
  Backtrace :
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 17:53:31] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144
  Backtrace :
  src/RuleTicketCollection.php:144                   in_array()
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 17:53:31] glpiphplog.WARNING:   *** PHP Warning (2): Cannot use a scalar value as an array in /var/www/html/glpi/src/RuleTicketCollection.php at line 148
  Backtrace :
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 18:09:06] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144
  Backtrace :
  src/RuleTicketCollection.php:144                   in_array()
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 18:09:06] glpiphplog.WARNING:   *** PHP Warning (2): Cannot use a scalar value as an array in /var/www/html/glpi/src/RuleTicketCollection.php at line 148
  Backtrace :
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 18:30:58] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144
  Backtrace :
  src/RuleTicketCollection.php:144                   in_array()
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()
  
[2024-12-11 18:30:58] glpiphplog.WARNING:   *** PHP Warning (2): Cannot use a scalar value as an array in /var/www/html/glpi/src/RuleTicketCollection.php at line 148
  Backtrace :
  src/RuleCollection.php:1760                        RuleTicketCollection->prepareInputDataForProcess()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Ticket.php:1880                                RuleCollection->processAllRules()
  src/CommonDBTM.php:1255                            Ticket->prepareInputForAdd()
  front/ticket.form.php:74                           CommonDBTM->add()


glpi sql log

[2024-12-11 16:45:13] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `USERS` SET `USR_PASSWORD` = '6d69d9977f42ee8a3073beed4da38971' WHERE `USR_UID` = '5870503246757d4dd7176a8048314145'
  Error: Unknown database 'wf_glpi'
  Backtrace :
  src/DBmysql.php:1431                               
  ...ins/processmaker/inc/processmaker.class.php:298 DBmysql->update()
  plugins/processmaker/hook.php:337                  PluginProcessmakerProcessmaker->login()
  src/Plugin.php:1478                                plugin_processmaker_post_init()
  src/Plugin.php:245                                 Plugin::doHook()
  inc/includes.php:86                                Plugin->init()
  ajax/getDropdownUsers.php:43                       include()
  {"user":"2@glpi-15-18","mem_usage":"0.000\", 4.66Mio)"} 
[2024-12-11 16:45:22] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `RBAC_USERS` SET `USR_PASSWORD` = '540a2428468a21bd31b56533f71d7536' WHERE `USR_UID` = '5870503246757d4dd7176a8048314145'
  Error: Unknown database 'wf_glpi'
  Backtrace :
  src/DBmysql.php:1431                               
  ...ins/processmaker/inc/processmaker.class.php:297 DBmysql->update()
  plugins/processmaker/hook.php:337                  PluginProcessmakerProcessmaker->login()
  src/Plugin.php:1478                                plugin_processmaker_post_init()
  src/Plugin.php:245                                 Plugin::doHook()
  inc/includes.php:86                                Plugin->init()
  front/config.form.php:38                           include()
  {"user":"2@glpi-15-18"} 
[2024-12-11 16:45:22] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `USERS` SET `USR_PASSWORD` = '540a2428468a21bd31b56533f71d7536' WHERE `USR_UID` = '5870503246757d4dd7176a8048314145'
  Error: Unknown database 'wf_glpi'
  Backtrace :
  src/DBmysql.php:1431                               
  ...ins/processmaker/inc/processmaker.class.php:298 DBmysql->update()
  plugins/processmaker/hook.php:337                  PluginProcessmakerProcessmaker->login()
  src/Plugin.php:1478                                plugin_processmaker_post_init()
  src/Plugin.php:245                                 Plugin::doHook()
  inc/includes.php:86                                Plugin->init()
  front/config.form.php:38                           include()
  {"user":"2@glpi-15-18","mem_usage":"0.000\", 4.55Mio)"}

**Comment by yxing-hub** [comment]
glpi sql log Error: Unknown database 'wf_glpi'  ，   It's because I reinstalled the processmaker server and changed the workspace, so I think we can ignore this 。

**Comment by tomolimo** [comment]
Hello @yxing-hub 
Apart the unknown database error that is no longer relevant (as you said), I cannot see any error relaed to processmaker plugin in the GLPI PHP error log.
Could you post GLPI version, PM plugin version, PM server version?
Thank you,
Regards,
Tomolimo

**Comment by yxing-hub** [comment]
Hello  this is my message 
GLPI version 10.0.1
PM plugin version processmaker-5.0.2
 PM server version 3.3.0-RE-2.0 （I have tried the  3.3.0-RE-2.5 version before）

**Comment by tomolimo** [comment]
Of course, you MUST use the most recent versions for GLPI, for PM plugin and for PM server
GLPI: 10.0.17
PM plugin: 5.0.3
PM server: 3.3.0-RE-2.5

**Comment by yxing-hub** [comment]
I reinstalled these versions 
GLPI: 10.0.17
PM plugin: 5.0.3
PM server: 3.3.0-RE-2.5
Encountered a new problem，When I initiate a process, it prompts me "Error in entering dates. The starting date is later than the ending date" 
Can you give me some advice? Thank you very much for your help
![20241212135339](https://github.com/user-attachments/assets/5135ee3f-4b87-4a1d-828e-7dab9bf72f7b)

**Comment by yxing-hub** [comment]
![20241212135718](https://github.com/user-attachments/assets/bac3966e-8d6d-4446-8f61-44dfb120f04c)

**Comment by yxing-hub** [comment]
dear  tomolimo ,
 I created a process on processmaker with two tasks inside. Task 1 is completed by A, and task 2 is completed by B.
Then, in GLPI, user A creates a standard Tickets   using the process, After a is completed, use b to log in to glpi, and then there is no way to continue the process in glpi. But in processmaker, user B can be used to complete task 2. No matter how I switch between GLPI and PM versions
Is it my usage error in GLPI? Or is there a problem with the task created in the PM process?
I just got into this project, thank you for your patience

**Comment by tomolimo** [comment]
Hello @yxing-hub 
Could we concentrate on one issue at a time?
Let's start with the start/end date issue, if you agree?
Could you post screenshots of the timezone settings in GLPI and in PM?
Could you post screenshots of the MySQL timezone tables (it's in the mysql database, in time_zone_name table (I just want to be sure that TZ are correctly enabled)? I need that for the MySQL server used by GLPI and for the MySQL server used by ProcessMaker server.
For your information: if a process-case is started via GLPI, never touch it in PM server. You may view it in PM server, but never do any actions in PM server. The PM plugin works in only one direction (from GLPI to PM server), if you touch the process-case in PM server, it will never be reflected back into GLPI.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
FYI: the issue with dates is #183

**Comment by yxing-hub** [comment]
dear tomolimo
Of course, as you said, we should focus on one issue first.
For GLPI
MySQL uses system time and has set Asia/Shanghai in PHP.ini, but not on the GLPI page.
For PM
MySQL uses system time and sets Asia/Shanghai in PHP.ini, and the PM page also sets Asia/Shanghai
![微信图片_20241212215602](https://github.com/user-attachments/assets/065b0298-aa6b-4d06-b525-2f6526daf822)
![微信图片_20241212215612](https://github.com/user-attachments/assets/2fc9d4c2-263a-45b4-aa5b-188fa5c00ed2)
![微信图片_20241212215618](https://github.com/user-attachments/assets/cf273cb8-caeb-4375-95d1-54695b09ef29)
![微信图片_20241212215623](https://github.com/user-attachments/assets/fc5302cf-4212-413d-aa7c-8c6ccd22fe5c)
![微信图片_20241212215629](https://github.com/user-attachments/assets/4527c607-ebfc-4885-a8a5-8e83f782895c)
![微信图片_20241212215635](https://github.com/user-attachments/assets/df32329d-ee61-44be-a898-0053a2c8dc9e)

**Comment by tomolimo** [comment]
Hello @yxing-hub 
Thank you for your fast response :)
The time_zone_name cannot be empty: it should contain the time zone names, like for example:
![image](https://github.com/user-attachments/assets/59235f3a-d5d2-4a46-98ec-c80a0fc496b5)
Could you apply the following procedure to update the time zone tables in MySQL? https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html#time-zone-installation
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Could you post the screenshots after the update?

**Comment by tomolimo** [comment]
I mean only the time_zone_name table

**Comment by tomolimo** [comment]
not complete data, but the beginning will be ok (with row count)

**Comment by tomolimo** [comment]
Question, did you restart MySQL servers? As the timezone tables are taken into account only at MySQL start

**Comment by yxing-hub** [comment]
Of course, I have restarted MySQL 
Please refer to the screenshot ， this information needs further supplementation？
![11111_20241212224912](https://github.com/user-attachments/assets/a87bd9d5-4603-4c87-a1ef-473b762def15)
![22222_20241212225300](https://github.com/user-attachments/assets/663943eb-cdeb-4662-94ae-166a0204c0aa)

**Comment by tomolimo** [comment]
I don't understand why there is "posix/XXXXX" in the time zone names...

**Comment by yxing-hub** [comment]
The previous data seems to be missing posix
![666666666_20241212225852](https://github.com/user-attachments/assets/51f916c9-ab6c-48ef-8d0a-7c3e1d445970)

**Comment by yxing-hub** [comment]
I want to confirm if these versions are compatible?
GLPI: 10.0.17
PM plugin: 5.0.3
PM server: 3.3.0-RE-2.5

If the version adaptation is not a problem, I will check the time of MySQL PHP GLPI PM again, adjust it to be consistent, and check if there are any omissions.
Also, I plan to adjust the PHP version because there was a previous issue with PHP version 8.2. I will try adjusting it.
If there is any effect, I will synchronize here as soon as possible
Thanks!

**Comment by yxing-hub** [comment]
Mr. Tomolimo, may I ask if you are available.
Today I checked all the time zone settings, including glpi, processmaker, and MySQL
I changed the PHP version, but it still doesn't work
Can you tell me the version of glpi you are using, glpi_php version, glpi_maysql version, processmaker version, processmaker_php, processmaker_mysql, and plugin version
I want to make the following attempts again.
thanks!

**Comment by yxing-hub** [comment]
@tomolimo   Mr. Tomolimo, Excuse me, could you provide me with the version you are using and try again , Thanks

**Comment by tomolimo** [comment]
Hello @yxing-hub 
The date issue has been fixed by https://github.com/tomolimo/processmaker/issues/183#issuecomment-2557210253
Please check this and test.
Thank you,
Regards,
Tomolimo

**Comment by yxing-hub** [comment]
Verified~  Thank you very much!
