### ISSUE TITLE
Retrieving all fields from processmaker server into GLPI Interface

### ISSUE THREAD

**Issue by alogez** [tomolimo/processmaker#22]
Hello Tomolimo, 

GLPI (9_1_2), together with processmaker-3.1.4 and processmaker-server-3.0.1.8-RE-1.6 have been set properly.

![image](https://cloud.githubusercontent.com/assets/13637446/25996306/c84e1abe-3727-11e7-97c1-b056e479a4b4.png)

Some data from PM server are not visible from GLPI.

![image](https://cloud.githubusercontent.com/assets/13637446/25996199/2070364c-3727-11e7-851d-600337d63a93.png)

I have enclosed the log from the GLPI server.

[GLPI_php-errors.log.txt](https://github.com/tomolimo/processmaker/files/995966/GLPI_php-errors.log.txt)

Have I mismatched something?

Thanks in advance,
Alogez.

The test is an unique machine Windows 7.
Wamp Server : wampserver3.0.6_x86_apache2.4.23_mysql5.7.14_php5.6.25-7.0.10
GLPI (9_1_2)
Plugin  : processmaker-3.1.4 
Processmaker-server-3.0.1.8-RE-1.6

**Comment by tomolimo** [comment]
Hello,
Could you post a screen copy of the language definitions in PM?
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
I believe you did not respect this: https://github.com/tomolimo/processmaker-server/wiki/Languages#localization-internationalization-languages
regards,
Tomolimo

**Comment by alogez** [comment]
Hello,
Thank you. 
As mentioned, I downloaded "processmaker.fr.po" file for the languague. 
I forgot to erase the country value.
That is been done right now. The file has been reloaded.


![image](https://cloud.githubusercontent.com/assets/13637446/25999047/b6f9ea7e-3734-11e7-9060-f13795df9ff2.png)

![image](https://cloud.githubusercontent.com/assets/13637446/25999079/d4ec5d1e-3734-11e7-82be-4188bfd8b0f2.png)


The language version 
![image](https://cloud.githubusercontent.com/assets/13637446/25999128/00b6e6da-3735-11e7-97d1-9f2b46251c5c.png)


I have no more error in the GLPI php-errors.log.
The name of the process is still not displayed.


Thanks in advance.

Alogez.

**Comment by tomolimo** [comment]
Did you re-synch the 'Process list' itself?

**Comment by alogez** [comment]
Tomolimo,

I did it like this : 
- first time from the button "Process List".
- second time : I truncate the table then I press the button.
Both of these methods couldn't display any name (office machine).

On another machine, it works.
Thanks a lot.

Alogez.

**Comment by tomolimo** [comment]
Hello
I think it's a problem of language definition.
What's the default language in GLPI?
What's your own language?
I must investigate this, as there may be a bug in the plugin.
Thank you for your help,

Tomolimo

**Comment by alogez** [comment]
Tomolino,

Glpi is set to French on both machines (home - office computers), as well as Processmaker.
At office : the name of the process is not displayed.
On personal machine, the name appears.


![image](https://cloud.githubusercontent.com/assets/13637446/26043298/38bf43fa-394d-11e7-8a60-c0d0cfe5b826.png)

Alogez.

**Comment by tomolimo** [comment]
Thank you for this info,
I'll try to reproduce this, and I'll keep you informed,
thank you,
regards,
Tomolimo

**Comment by alogez** [comment]
Hi Tomolimo,
I am sorry; there is no mistake.
The process has no name in the processmaker web interface.
It is therefore logical that GLPI can not display it.

![image](https://cloud.githubusercontent.com/assets/13637446/26101783/6d67d1e8-3a43-11e7-8554-f93290d64f29.png)

Thanks.

Alogez.

**Comment by tomolimo** [comment]
Ok, no problem,
Thank you for your feedback,
Regards,
Tomolimo
