### ISSUE TITLE
Only "Admin" can see tasks

### ISSUE THREAD

**Issue by grvy** [tomolimo/processmaker#23]
Only the admin of all entities can see tasks in our GLPi. If we arent on admin profile we just get this: 

![afbeelding](https://cloud.githubusercontent.com/assets/5603820/26028340/d667bd1a-381e-11e7-8ac8-1a4936d8ca3b.png)
Without any tasks or followups already present.

**Comment by tomolimo** [comment]
Hello,
Did you start a case?
Thank you,
regards,
Tomolimo

**Comment by grvy** [comment]
Yes; a case is running and if I swtich to the GLPI admin profile I can see the followups and tasks.

**Comment by tomolimo** [comment]
Do you mean that other profiles don't have the rights to see tasks? 
Could you post a screen copy of the tasks?

**Comment by grvy** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/26050890/b928cdb4-3960-11e7-80a3-30ecc2f7399a.png)
This is under the admin accoumt. 
Under my own rights, you se the above. I can see taks I create on both, just not PM tasks.

**Comment by tomolimo** [comment]
Could you post complete screen copies?
As I really can't imagine where you got them exactly, I can't really help you...
Was the first one, on the 'Solution' tab? Do you still use the 'keep tabs replaced by the ticket timeline'?
Or else?
Thank you,
Regards,
Tomolimo

**Comment by grvy** [comment]
It is a complete screenshot. It's just under the processing tab. Its the timeline, It shows the tasks.

**Comment by tomolimo** [comment]
I was speaking bout the first screen shot :)

**Comment by tomolimo** [comment]
here is a complete screen shot:

![image](https://cloud.githubusercontent.com/assets/7569958/26105600/e2e32ec8-3a42-11e7-984e-abafdf7678a9.png)

**Comment by tomolimo** [comment]
or this one:
![image](https://cloud.githubusercontent.com/assets/7569958/26105648/0c2d7040-3a43-11e7-9d31-d24288256405.png)

**Comment by tomolimo** [comment]
Hello,
Sorry for being so late to comeback to you.
Do yo have any news?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Closed as I got no news, feel free to reopen if you need.
Thank you,
Regards,
Tomolimo
