### ISSUE TITLE
First task empty

### ISSUE THREAD

**Issue by grvy** [tomolimo/processmaker#24]
When starting "Tutorial 1" (follow it to the letter) i get this: 

![afbeelding](https://cloud.githubusercontent.com/assets/5603820/26028349/f824ea7c-381e-11e7-8e4f-5c12ff36bd51.png)
Withouut any dynaform on task 1. I set the permissions aswell.

**Comment by tomolimo** [comment]
Hello,
What's the processmaker configuration? (screencopy)
What's processmaker server configuration? (screencopy)
Could you post your process definition (export process and post PMX file)? 
Thank you
Regards,
Tomolimo

**Comment by grvy** [comment]
Plugin:
![afbeelding](https://cloud.githubusercontent.com/assets/5603820/26050947/e54af2be-3960-11e7-9b0e-c1a0b4e614bc.png)
Server config what do you need?
[Tutorial_1-1.zip](https://github.com/tomolimo/processmaker/files/1000625/Tutorial_1-1.zip)

**Comment by tomolimo** [comment]
Hello,
What's your browser? Browser version?
thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
I made a test with your process, and set my GLPI account into the 'GS-GLPI-IT-Servicedesk
' group, to be able to start a case from this process.
And then I started a case, and get the normal view.
And tried also to logout and login into GLPI with another account and saw the correct form, like below:

![image](https://cloud.githubusercontent.com/assets/7569958/26103901/f00d1764-3a3b-11e7-8fa1-8739e807599f.png)

**Comment by raregtp** [comment]
I'm actually experiencing this exact issue right now.  What do you need to assist troubleshooting this?  Thanks!!

**Comment by tomolimo** [comment]
Yes, please,
I welcome screencopies, log contents, and network traces from Chrome (or Fiddler if possible).
regards,
Thank you,
Tomolimo

**Comment by raregtp** [comment]
Ok, so this particular issue seems to be caused when portions of the setup are not followed.....specifically the Apache rewrite configuration as well as the dropdown translation and php-intl module.  Once I followed those pieces I got much further.  Still having an issue but I don't believe it's necessarily a bug.  Is there a "support channel" where I can ask you a couple questions??  Thanks!

**Comment by tomolimo** [comment]
Thank you for your feedback, 
There is no irc, but you may create issues one per question, and I'll be glad to assist you.

**Comment by tomolimo** [comment]
Hello,
I've just created a channel on freenode: #processmaker-glpi 
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
No news,
Feel free to reopen.
