### ISSUE TITLE
Missing in GLPI

### ISSUE THREAD

**Issue by alogez** [tomolimo/processmaker#25]
Tomolimo,

I am trying to practice, thanks to your tutorial ([url](https://github.com/tomolimo/processmaker/wiki/Tutorial-2)) .

I have implemented a workflow through processmaker interface.

In GLPI interface, an user opens a ticket. 
![image](https://cloud.githubusercontent.com/assets/13637446/26143764/5999b820-3af7-11e7-88eb-f15dec2a5be9.png)

The workflow is started manually (in this case); process - named Tutorial 1 is in fact your Tutorial 2.
_By the way, "Save as" in processmaker does not work in my case (processmaker RE)_ 
![image](https://cloud.githubusercontent.com/assets/13637446/26143857/c3f64ea4-3af7-11e7-99cc-155ca776f60b.png)

After filling the data, the assigned user is displayed.

![image](https://cloud.githubusercontent.com/assets/13637446/26144071/79915af6-3af8-11e7-8416-1b0f3c765781.png)

While connecting to GLPI, through this user, nothing appears.

![image](https://cloud.githubusercontent.com/assets/13637446/26144242/1fbc1948-3af9-11e7-8380-c5ef4ff5cf71.png)

The processs has been set to be used with this specified profile (eg. self service).
Process Server has been set to be available through this profile (Profile setting properties).

Have I mismatched anything?

Alogez.

**Comment by tomolimo** [comment]
Hello Alogez,
Could you post a screen copy of this ticket task tab?
thank you
regards,
Tomolimo

**Comment by alogez** [comment]
Hello Tomolimo, 


![image](https://cloud.githubusercontent.com/assets/13637446/26149810/cb5b32da-3b0c-11e7-9690-57ccd37db9a5.png)

Then, 

![image](https://cloud.githubusercontent.com/assets/13637446/26149874/0dfd6590-3b0d-11e7-8e29-025b6d8a792d.png)


In mysql, 2 records are displayed for this specific ticket :
![image](https://cloud.githubusercontent.com/assets/13637446/26149899/2e90052e-3b0d-11e7-9166-c8b6d3a38df4.png)

Thanks,
Alogez.

**Comment by alogez** [comment]
Tomolimo,

Let Aymeric and Chantal be two users (same profile : Self-Service, tightly tuned for processmaker purpose, and image copy also).
One of them (Chantal) is starting from ticket a workflow.
The second user, Aymeric, (processmaker in or out), can not see the Chantal's ticket.

Does the processmaker plugin allow the second user (Aymeric) to see his assigned task (through planning or somewhere else).
How could it be possible to get this?

Alogez.

**Comment by tomolimo** [comment]
Normally yes, but it could be that the GLPI configuration is missing something.
The plugin should add as 'watcher' any assigned person, when this person has no rights (via profile and entities) on the ticket., here is the 'post-only' (aka your self-service) profile:
![image](https://cloud.githubusercontent.com/assets/7569958/26151123/a244e96e-3b01-11e7-95d0-216f547593ff.png)

**Comment by alogez** [comment]
Tomolimo,
Thanks for your answer.

- My specific goal (from a particular profile Self Service)

My interface is lightly different from yours.

![image](https://cloud.githubusercontent.com/assets/13637446/26151502/3c5e69fa-3b14-11e7-97e6-6487a170c6f7.png)

Without success : nothing appears. I keep on changing properties for this profile.

- Record in database
In database, there is no record for "assigned person" for this specific ticket.

![image](https://cloud.githubusercontent.com/assets/13637446/26152211/112316b6-3b17-11e7-8e4d-a9fa2a5f1f09.png)

Thanks again.

Alogez.

**Comment by tomolimo** [comment]
Try with 'voir tous les tickets'

**Comment by alogez** [comment]
Tomolimo, 

Obviously, this setting works. Thanks!
All the tasks appear therefore in the planning view.
I keep on searching for a better setting. 
This kind of profile can not be able to see all the tickets.

Could you tell me a bit about "observer" field filled by processmaker plugin?
Why can't I get the new record in glpi_tickets_users?

Thanks in advance,

Alogez.

**Comment by tomolimo** [comment]
The task assigned user is added as observer when and only when there is no profile/entity which can be used by the assigned user to view the task/ticket.
In other words, imagine two users with self-service profiles one on entity A and the second on entity B. Then when ticket is in entity A, the second user doesn't have any profile/entity that will permit him to view the task/ticket, then the plugin will add the second user as observer to the ticket.

**Comment by alogez** [comment]
Tomolimo,
Thank you.
In my case, the root entity is dedicated to the company.
Then, sub-entities are defined for any department (marketing, accounting, IT support, and so on) that needs his own ticketing system to solve any request.

Any colleague has at least 1 profile (for request, ie. Self Service), at most 2 profiles (request and "solver" => technician or admin).
The solver profile is set within a specified entity.
Self-service is set within root entity to allow person to create ticket for any service.

In my case, Chantal and Aymeric are both simple users (1 profile : Self Service over root entity).
They both belong to the same entity (root one) but their profile disallow them to see each other tickets.

How could I proceed?

Thanks in advance, 

Alogez.

**Comment by alogez** [comment]
Tomolimo,
Thank you for your precious help.

I write it down to complete this issue.

To allow any assigned person to be quoted as observer for glpi ticket: 
From file  processmaker/inc/processmaker.class.php

`$user_entities = Profile_User::getUserEntities( $techId, true, true );`
`$user_can_view = in_array( $glpi_item->fields['entities_id'], $user_entities );`
`if (!$glpi_item->isUser( CommonITILActor::REQUESTER, $techId )`
 `              && !$glpi_item->isUser( CommonITILActor::OBSERVER, $techId )`
`               && !$glpi_item->isUser( CommonITILActor::ASSIGN, $techId )`
`              && !$user_can_view ) {`

Changes the lines as followed :
 
`        //$user_entities = Profile_User::getUserEntities( $techId, true, true );`
`         //$user_can_view = in_array( $glpi_item->fields['entities_id'], $user_entities );`
`         if (!$glpi_item->isUser( CommonITILActor::REQUESTER, $techId )`
`               && !$glpi_item->isUser( CommonITILActor::OBSERVER, $techId )`
`               && !$glpi_item->isUser( CommonITILActor::ASSIGN, $techId ) ) {`
`               //&& !$user_can_view ) {`

Thanks.

Alogez.
