### ISSUE TITLE
Can't connect to GLPI

### ISSUE THREAD

**Issue by nicolas62** [tomolimo/processmaker#28]
Hello,

I've got a problem to connect GLPI to Processmaker.
When I'm trying to add my mysql server, I have a "Test failed" error.

My login/pwd have been verified, everything is OK

Here is my configuration : 

![image](https://user-images.githubusercontent.com/25502814/29713873-ebda87ee-89a0-11e7-8552-f359365d4ce8.png)

I already tried to uninstall/drop/reinstall the plugin without success.

Do you have any idea ?

![image](https://user-images.githubusercontent.com/25502814/29714046-8a2da00c-89a1-11e7-8f20-42a780ea8ce6.png)

**Comment by tomolimo** [comment]
Hello @nicolas62 

1. Fix the trouble of the domain, otherwise, it will be able to show dynaforms into ticket tabs.
1. Could you check that the process user is a mysql user with an access to the workspace DB? DB name is composed like following wf_workspace

As a reference, here is the link to the configuration wiki part: https://github.com/tomolimo/processmaker/wiki/Plugin-configuration

regards,
Tomolimo

**Comment by nicolas62** [comment]
Hello @tomolino

With your help, my domain is now detected :

![image](https://user-images.githubusercontent.com/25502814/29763245-b1377208-8bd2-11e7-8028-5ec65a4d975a.png)

But, I still can't connect my database to processmaker.
I checked my login/pwd and it's working directly in mysql but not in GLPI.

I'm on version 9.1.6.
Do you have any idea ?

**Comment by tomolimo** [comment]
Hello @nicolas62 
For the PM workspace: did you use the default one (i.e.: 'wf_workflow') or else?
Could be that there is a bug in the code about accessing a db which is not the default one.
I'm going to check that.
regards,
Tomolimo

**Comment by nicolas62** [comment]
No, it's not de default workspace and db name.
Maybe that's the problem ?

**Comment by tomolimo** [comment]
Hello @nicolas62 
I made tests with a workspace named 'test', and it works correctly.
See my production settings:
![image](https://user-images.githubusercontent.com/7569958/29764456-75cce3e2-8bd7-11e7-909a-e1a2d52e33b6.png)

Could you check that the SQL user has the following rights on the pm workspace DB name wf_workspace (where workspace is the name of the workspace set above)?
![image](https://user-images.githubusercontent.com/7569958/29764592-0104f26a-8bd8-11e7-91b1-ba30e171aaa1.png)

**Comment by nicolas62** [comment]
Here is my configuration : 
 GRANT ALL PRIVILEGES ON `processmaker`.* TO 'process'@'localhost'

**Comment by tomolimo** [comment]
Do you mean that the DB of workspace is called 'processmaker'?
If yes, that's the root cause of the issue: it must be prefixed with 'wf_'

**Comment by nicolas62** [comment]
Yes my DB is called processmaker.
I need to change it like wf_processmaker ?

**Comment by tomolimo** [comment]
How did you change this name? Was it during the PM server installation?

**Comment by nicolas62** [comment]
Exactly.

**Comment by nicolas62** [comment]
I edited the db.class.php file like this : 
 $this->dbdefault = "processmaker";

It's working now :+1: 
Thank you for your support

**Comment by tomolimo** [comment]
Normally by convention, all PM DBs are prefixed with 'wf_', the PM plugin is using this convention.... then it will never be able to connect to the DB which has no wf_ prefix....
I'm not sure that even PM server will be ok with a DB name which is not prefixed by wf_

**Comment by tomolimo** [comment]
this fix you found will be ok for the plugin itself, but I'm not sure for PM server

**Comment by nicolas62** [comment]
What do you mean by the server will not be OK ?

I can create and manage a workflow for now.

How can I see if my configuration seems OK on the PM server ?

**Comment by tomolimo** [comment]
Check this: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check
and then create a new process, with some tasks, and so on. Create a case from it, if everything go ok, then it should be also ok with GLPI.

regards,
Tomolimo

**Comment by nicolas62** [comment]
My server configuration is the same as your link.
But I still can't synchronize my tasks :+ 
![image](https://user-images.githubusercontent.com/25502814/29923517-21187ee4-8e5a-11e7-9b86-06fe090611c6.png)
My process are synchronized but not my tasks.

**Comment by tomolimo** [comment]
Hello,
As this is not related to your initial question (which seems to be solved), could you this in another issue?
Thank you
Regards,
Tomolimo
