### ISSUE TITLE
I can't install plugin

### ISSUE THREAD

**Issue by erivaldofilho2** [tomolimo/processmaker#3]
When I install the plugin, the glpi screen turns white. I've tried to change the database url, removing '/', I tried the urls: http://localhost, http://localhost/glpi as the address of my glpi is http://localhost/glpi. There is another patch that I can do? When it will be available the new version of the plugin? Hug!

**Comment by erivaldofilho2** [comment]
![1](https://cloud.githubusercontent.com/assets/4555329/13744991/42848720-e9ca-11e5-8925-7f8003537c25.png)
![2](https://cloud.githubusercontent.com/assets/4555329/13744992/4556401a-e9ca-11e5-82d6-d9ec801c6a37.png)
![3](https://cloud.githubusercontent.com/assets/4555329/13744993/477ca69a-e9ca-11e5-9e1c-755cb813f052.png)

**Comment by tomolimo** [comment]
Hello,
could you  have a look into the GLPi log files?
thank you

**Comment by erivaldofilho2** [comment]
Hi, I looked at the log GLPI, and realized that he was trying to get the processmaker on my machine so I pointed the url in the database to the server where it installed my processmaker. When it will be available the new version of the plugin? Thank you!

log GLPI:

`[Faultstring] => SOAP-ERROR: Parsing WSDL: Could not load from 'http: // localhost / sysworkflow / en / classic / services / wsdl2': failed to load external entity "http: // localhost / sysworkflow / en / classic / services / wsdl2 "`

**Comment by tomolimo** [comment]
not before end of April

**Comment by tomolimo** [comment]
Regarding your problem could you test ProcessMaker server installation?
Go to the PM server URL in your example: http://localhost and you should be able to login into PM server. and report to me this, thank you

**Comment by erivaldofilho2** [comment]
I do not quite understand your question ... as I said my PM is another server not in my localhost. It occurred to me that I not informed the GLPI the user and password for PM, where do I do that?

**Comment by tomolimo** [comment]
Could you try to follow these comments?

**Comment by tomolimo** [comment]
Hello,
Sorry, but I didn't really realized that PM server WAS NOT on the same server than GLPi!
It took me some times to realize that.
So the answer is: as you didn't follow the Wiki for installation of the PM plugin: I cannot help so far. The current PM plugin doesn't support for PM server the use of a different server than the one of GLPi.
Please read the wiki: https://forge.glpi-project.org/projects/processmaker/wiki.
Thank you,
Regards,
Tomolimo
