### ISSUE TITLE
Error load ProcessMaker

### ISSUE THREAD

**Issue by raguzmi** [tomolimo/processmaker#30]
Hello.

I download process maker to install at glpi 9.1.1, my problem is in general-->ProcessMaker, it's imposible load information after first configure, all time see "login" to screen.
help me please
![error procesmaker](https://user-images.githubusercontent.com/32066327/30544011-5ed799e8-9c85-11e7-9d31-4ccc34a51e2b.png)

**Comment by tomolimo** [comment]
Hello
Which version of the plug-in did you download?
Which version of the PM server did you install?
Thank you
Regards
Tomolimo

**Comment by raguzmi** [comment]
Hello
Plugin:
![version plugin](https://user-images.githubusercontent.com/32066327/30696912-8684904a-9edd-11e7-96bd-eb1663e258ae.png)
Proessmaker:
![version procesmaker](https://user-images.githubusercontent.com/32066327/30696921-939b47ce-9edd-11e7-875e-f03b9a0744ef.png)
I try reparir this problem reinstalling plugin, but don't work.
Sorry for my english.
Thanks

**Comment by tomolimo** [comment]
Hello
The plugin is ok
The PM server isn't the correct version. You must install the version I'm providing on the wiki. Please read the wiki in details.
And keep me informed. 
Regards
Tomolimo

**Comment by tomolimo** [comment]
Close this issue as I got no news. Feel free to re-open.
