### ISSUE TITLE
glpi 9.2 compatibility

### ISSUE THREAD

**Issue by actikool** [tomolimo/processmaker#31]
hi, when i install the plugin 3.1.6 i've got this message 
This plugin requires GLPI 9.1 or higher

**Comment by tomolimo** [comment]
Hello,
The plugin is not yet updated to be compatible with GLPI 9.2
I'm going to work on that
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment]
Please see https://github.com/tomolimo/processmaker/releases/tag/3.2.0
