### ISSUE TITLE
Tasks creates in Processmaker (3.2.1 - community) don't appears in GLPI (9.1.6) - Plugin Processmaker (3.1.6)

### ISSUE THREAD

**Issue by ValouMark** [tomolimo/processmaker#33]
Hello,

I installed processmaker in a Debian 8.9 OS with Apache2.4.10 / php5.6 / Mysql5.5.57

I follow your instructions for the complete installation. And again after i have a problem when i Synchronize the list of Tasks in GLPI. A blank pages appears, and nothing...

So after some researches, i executed "apt-get install php5-intl" and the blank page don't appears now but nothing appears in the Process Tasks lists.
When i Click on Synchronize Tasks Lists - Opération failed message come up .

Maybe the problem become of the fact that i can't changed : 

"RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /app.php [QSA,L]

Into

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /glpi/app.php [QSA,L]"

in the documents : /etc/apache2/sites-available/pmos.conf

The workflow in Processmaker that i want to used in GLPI
[WorkFlow.zip](https://github.com/tomolimo/processmaker/files/1474335/WorkFlow.zip)

The configuration in GPLI for Processmaker
![glpi_conf](https://user-images.githubusercontent.com/33681881/32833220-6eeafc52-c9fe-11e7-8058-c0e1d0454f89.PNG)

Thanks for your Help,

Best Regards,

**Comment by tomolimo** [comment]
Hello,
Did you really installed Processmaker server 3.2.1?
If yes, then you didn't follow the installation wiki I provide here:  https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation

where it says:

> Notes
> 
> We are using a modified version of the ProcessMaker Community Edition which you can download from our repository.

So in a word: the plugin needs a special modified version of Processmaker server, you can not use the current Community edition.

You must use the one available here: https://github.com/tomolimo/processmaker-server/releases/tag/3.0.1.8-RE-1.6

Thank you uninstall the 3.2.1 release and to install the 3.0.1.8-RE-1.6 release

after that we may speak about the configuration.

waiting for your feedback,

thank you,
Regards,
Tomolimo

**Comment by ValouMark** [comment]
Thanks for your returns.

I read that but i am obstinate to install the last version, and i also forget this parameter --"

I will install the 3.0.1.8-RE-1.6 release

I will sent you a Feedback when my new installation will be complete.

Thank You,
Best Regards,
ValouMark

**Comment by tomolimo** [comment]
As an encouragement for you, on my config, I've been able to import your process, to synchronize it in GLPI and I've been able to synchronize the tasks also.
After, we will speak about the process itself.
just keep me informed

**Comment by ValouMark** [comment]
I reinstalled a Server with the version 3.0.1.8-RE-1.6 release and that's OK.

By the way, the old list of processes are always in GLPI, could you tell me how delete all that processes ?

Thank you so much for your help !
Regards,

ValouMark

**Comment by tomolimo** [comment]
Hello 
Thank you for the news. 
Currently there is no way to properly delete an unused process. You may create an issue for this. 
By the way tomorrow we should speak about the process you sent to me. 
Regards 
Tomolimo

**Comment by ValouMark** [comment]
Hello,

I create a new issue (#34) for the way to follow for properly delete an unused process in GLPI.
Did you have the time to see the process that i send to you ? What you want to said about it to me ? 

Thanks,
Regards,

ValouMark

**Comment by tomolimo** [comment]
Hello
Thank you for the new issue, yet it's a good idea to permit to delete/inactivate no longer available processes.
Regarding your process:
Currently the plugin **does** support only **one pool** (this restriction is only for viewing the map in a ticket). What you needed were lanes (and not new pools)? so you have to move your tasks into one pool and split them into lanes (something like following):
![image](https://user-images.githubusercontent.com/7569958/32885461-df34a7fa-cabd-11e7-97fb-1d63754b8903.png)

By the way the rest seems Ok.

regards
Tomolimo

**Comment by ValouMark** [comment]
You're Welcome ! I also encountered a problem for Cancel/Delete a case begin in a GPLI Ticket. 
Do you have a solution for that ?

Oh ok, I will make this modification in my process and try this one in a GLPI Ticket :)

Regards,
ValouMark

**Comment by tomolimo** [comment]
Sorry I don't understand the issue you've encountered. Could you send screen copies?
regards,
Tomolimo

**Comment by ValouMark** [comment]
I went to test the process in the GPLI Ticket, and after that delete it, but I can't...

When I click in the Button "Annuler / Cancel" or " Supprimer / Delete"
![glpi tickets error](https://user-images.githubusercontent.com/33681881/32888442-8d2623ee-cac7-11e7-8e6a-4f1c43aa0fcf.jpg)

Regards,
ValouMark

**Comment by tomolimo** [comment]
Could you check the error logs? You may have more information in them.
Thank you,
Tomolimo

**Comment by ValouMark** [comment]
Hello,
Sorry for the late answer ,

When I Want to Cancel or Delete a Processmaker Case in GLPI, I have this MySQL Error :  
_**" *** MySQL query error:
  SQL: DELETE from glpi_Tickettasks where id in (select items_id from glpi_plugin_processmaker_tasks where case_id=\'1197258585a1c0de5307958033921345\')
  Error: Table 'glpi.glpi_Tickettasks' doesn't exist
  Backtrace :
  plugins/processmaker/inc/case.class.php:557
  plugins/processmaker/inc/case.class.php:576        PluginProcessmakerCase->deleteTasks()
  ...ins/processmaker/front/processmaker.form.php:89 PluginProcessmakerCase->deleteCase()"**_

If i create a glpi_Tickettasks Table th problem will be fix or i must doing something else ?

Regards,
Valoumark

**Comment by tomolimo** [comment]
Hello
Thank you for the feedback, this is clearly a bug, due to the fact your OS is Linux based. On windows there is no trouble with case mix in table naming. I'll fix it asap. 
Thank you again 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
Fixed in release 3.1.7
