### ISSUE TITLE
How properly delete an unused process in GLPI ?

### ISSUE THREAD

**Issue by ValouMark** [tomolimo/processmaker#34]
Hello,

I have synchronized some process of processmaker with GLPI, but I don't need them at all, so i want to delete them from GLPI.

What's the way to follow to doing that properly ?

Thank you,
Regards,

ValouMark

**Comment by tomolimo** [comment]
Hello @ValouMark 

Fixed by 51a71c42895fe057cb825b9711406dd7a5e6c33f

You just need to delete them from PM server, and then at next 'Process refresh' the will be deleted from GLPI as soon as no cases are existing for them.

Regards,
Tomolimo
