### ISSUE TITLE
Problem in processmaker

### ISSUE THREAD

**Issue by grego1981** [tomolimo/processmaker#35]
Hello, I have installed processmaker as per the wiki instructions and followed it as best as I could. I have installed the 3.2 version of the plugin since I have a 9.2 GLPI installation. I have configured the plugin 

![config](https://user-images.githubusercontent.com/9021998/33361841-82c82ab2-d4e2-11e7-93a4-e2cdb58ba3bb.PNG)

and tried to create a process in the processmaker admin interface and I get the error below:

![error](https://user-images.githubusercontent.com/9021998/33361830-72fb6b58-d4e2-11e7-931c-f84cacabf4cb.PNG)

Also in the processmaker setting I see this error

![error2](https://user-images.githubusercontent.com/9021998/33361854-96107d7c-d4e2-11e7-9e73-3b22f74c7c84.PNG)

Also when I delete a process in processmaker the process is not deleted in GLPI..
What can I do to resolve these issues?

**Comment by tomolimo** [comment]
Hello,
I think you have several issues, so let's start first by trying to solve the one with ProcessMaker server.
1. What version of PM server did you install?
1. Could you post the screen copies like shown here: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check?

Thank you
Regards,
Tomolimo

PS: about deletion of process in GLPI, there is already an issue: #34

**Comment by grego1981** [comment]
1. I'm using the version from the [Wiki ](http://github.com/tomolimo/processmaker-server/releases/latest)
2. 

![error7](https://user-images.githubusercontent.com/9021998/33364392-f92c256e-d4ec-11e7-82e3-15dc68bba5ac.PNG)
![error2](https://user-images.githubusercontent.com/9021998/33364393-f94d2afc-d4ec-11e7-9d0c-1455edbd2b88.PNG)
![error3](https://user-images.githubusercontent.com/9021998/33364394-f96bfbb2-d4ec-11e7-98d4-a73297577873.PNG)
![error4](https://user-images.githubusercontent.com/9021998/33364395-f98b91fc-d4ec-11e7-8fa8-9f61a0af253d.PNG)
![error5](https://user-images.githubusercontent.com/9021998/33364396-f9aa9660-d4ec-11e7-91e9-642a1c825c0c.PNG)
![error6](https://user-images.githubusercontent.com/9021998/33364397-f9cc8d6a-d4ec-11e7-82ab-eaaa695d11b9.PNG)

Thank you!
Gregory

**Comment by tomolimo** [comment]
Hello,
Seems like something is wrong in the ProcessMaker server installation/configuration.
1. could you check if any errors are in the log files?
1. could you check if Apache configuration is done correctly: especially the rewrite rule? https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules
    
Thank you,
Regards,
Tomolimo

**Comment by grego1981** [comment]
1. The apache error log:
>
[Thu Nov 30 08:24:02.452004 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP Notice:  Undefined index: access_token in /var/www/processmaker/workflow/engine/controllers/designer.php on line 259, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452028 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP Stack trace:, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452036 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   1. {main}() /var/www/processmaker/workflow/public_html/glpi/app.php:0, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452040 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   2. include() /var/www/processmaker/workflow/public_html/glpi/app.php:143, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452043 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   3. include() /var/www/processmaker/workflow/public_html/app.php:61, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452048 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   4. Controller->call() /var/www/processmaker/workflow/public_html/sysGeneric.php:2020, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.452052 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   5. Designer->index() /var/www/processmaker/gulliver/system/class.controller.php:127, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453007 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP Warning:  Smarty error: unable to read resource: ".html" in /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php on line 1095, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453034 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP Stack trace:, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453040 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   1. {main}() /var/www/processmaker/workflow/public_html/glpi/app.php:0, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453045 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   2. include() /var/www/processmaker/workflow/public_html/glpi/app.php:143, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453048 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   3. include() /var/www/processmaker/workflow/public_html/app.php:61, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453052 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   4. Controller->call() /var/www/processmaker/workflow/public_html/sysGeneric.php:2020, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453056 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   5. Designer->index() /var/www/processmaker/gulliver/system/class.controller.php:127, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453059 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   6. Controller->render() /var/www/processmaker/workflow/engine/controllers/designer.php:293, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453062 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   7. G->RenderPage() /var/www/processmaker/gulliver/system/class.controller.php:293, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453066 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   8. SkinEngine->dispatch() /var/www/processmaker/gulliver/system/class.g.php:515, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453069 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP   9. SkinEngine->_mvc() /var/www/processmaker/workflow/engine/skinEngine/skinEngine.php:166, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453072 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  10. Smarty->display() /var/www/processmaker/workflow/engine/skinEngine/skinEngine.php:612, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453076 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  11. Smarty->fetch() /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php:1108, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453079 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  12. Smarty->_compile_resource() /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php:1256, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453083 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  13. Smarty->_fetch_resource_info() /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php:1417, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453086 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  14. Smarty->trigger_error() /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php:1591, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit
[Thu Nov 30 08:24:02.453089 2017] [:error] [pid 29458] [client 10.0.1.101:56542] PHP  15. trigger_error() /var/www/processmaker/gulliver/thirdparty/smarty/libs/Smarty.class.php:1095, referer: http://10.10.99.15:8888/sysworkflow/en/neoclassic/processes/mainInit

2.

The contents for processmaker

# Please change the IP address with your server IP address and
# the ServerName with your own subdomains.
# processmaker virtual host
<VirtualHost *:8888 >
ServerName "itsrv-01.central2.local"
DocumentRoot /var/www/processmaker/workflow/public_html

<Directory /var/www/processmaker/workflow/public_html>
        Options Indexes FollowSymLinks MultiViews
        AddDefaultCharset UTF-8
        AllowOverride All
        Require all granted
        ExpiresActive On

        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^.*/(.*)$ glpi/app.php [QSA,L,NC]
        </IfModule>

        #Deflate filter is optional. It reduces download size, but adds slightly more CPU processing:
        AddOutputFilterByType DEFLATE text/html

    </Directory>
</VirtualHost>

**Comment by grego1981** [comment]
Hi, I tried this: I uninstalled pmaker and reinstalled it using firefox instead of chrome. The installation was completed without issues and when I logged in the process editor and everything seem to work as they should! Also now it works in chrome apart from some rendering glitches.

Thank you for your efforts, I will come back to you if I have something more to report!

**Comment by tomolimo** [comment]
Hello
I close this issue, and if something else occurs then create a new issue. 
If it's the same, then feel free to re-open. 
Thank you 
Regards 
Tomolimo
