### ISSUE TITLE
Synchronize Task List

### ISSUE THREAD

**Issue by manoel-cristiano** [tomolimo/processmaker#36]
Hello Tomolimo, how are you? 
I'm facing a problem to synchronise my tasks in glpi. 
When I click in the button to synchronise nothing happens.
In the GLPI logs I received the follow error

*** MySQL query error:
  SQL: UPDATE rbac_users SET USR_DUE_DATE=\'2035-12-31\' WHERE USR_DUE_DATE<>\'2035-12-31\'; 
  Error: Table 'wf_workflow.rbac_users' doesn't exist
  Backtrace :
  ...ns/processmaker/inc/processmaker.class.php:1366 
  :                                                  PluginProcessmakerProcessmaker::cronPMUsers()
  inc/crontask.class.php:832                         call_user_func()
  front/crontask.form.php:50                         CronTask::launch()

Could you give me a hand about that?

Sincerely.. 

Soares, Manoel

**Comment by tomolimo** [comment]
Hello,
Could you give back the config of GLPI, ProcessMaker and plugins (version, ...)?
thank you,
Regards,
Tomolimo

**Comment by manoel-cristiano** [comment]
Thank you for the fast answer. Currently i'm using the GLPI ver. 9.1.6 and ProcessMaker ver. 3.2.1.

It is running in apache 2.4 and PHP 5.6

If you need more information about configuration just let me know. 

Sincerely.

**Comment by tomolimo** [comment]
And what's the version of ProcessMaker server?
Thank you

**Comment by manoel-cristiano** [comment]
The server Ver. and conf.

Ubuntu server 16.04
Mem: 1 GB
2vCPUs
Disk: 30 GB

**Comment by tomolimo** [comment]
Could you paste screen copies like shown here: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check#system-information? 
Thank you

**Comment by manoel-cristiano** [comment]
follow the screen.
I didn't define de current user.

**Comment by manoel-cristiano** [comment]
Follow the screen.

http://handson-ti.com.br/img/serverconf.png

**Comment by tomolimo** [comment]
I also need the screen copies following the one you sent,
thank you

**Comment by manoel-cristiano** [comment]
Sorry but I didn't understand very well which screen you need. This is the first time that i'm configuring the system. Could you please send me a example screen?

Thank you in advance.

**Comment by tomolimo** [comment]
You may send all the same screens than the one on this page: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check

**Comment by manoel-cristiano** [comment]
I left all screenshots at http://handson-ti.com.br/processmaker/

**Comment by tomolimo** [comment]
Thank you,
As I can see, you've installed Processmaker server 3.2.1, which cannot be currently used, see: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation#notes first note.
So please, uninstall your version and install the one which is dedicated to GLPI: https://github.com/tomolimo/processmaker-server/releases/latest
Thank you
Regards,
Tomolimo

**Comment by manoel-cristiano** [comment]
Thank you a lot. 
I going to uninstall the current version and install the proper one.

Sincerely.
