### ISSUE TITLE
unfortunately not updated for glpi 0.9

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker#4]
I expect this plugin is compatible, it would be very useful

**Comment by tomolimo** [comment]
Working on it ☺

**Comment by satyan01** [comment]
do you know when it will be finished

**Comment by satyan01** [comment]
do you have news about glpi new version ? they announce for spring

**Comment by tomolimo** [comment]
I hope for official 9.1 release

**Comment by satyan01** [comment]
thank you for your work !

**Comment by tomolimo** [comment]
For GLPi: not the right place to post 😐

**Comment by tomolimo** [comment]
I'm going to keep this post open to reflect the progress of the plugin.

**Comment by jstival** [comment]
Hello, any news about this project for glpi 0.90.5 or 0.9.1 ?

**Comment by tomolimo** [comment]
Hello,
Yes, I'm preparing the release 2.6 that will be compatible with ProcessMaker server 3.0.1.8 (but only for GLPi 0.83), and the 3.0 release that will be compatible with GLPi 9.1
These releases should be out in before end of year (probably in 1 or 2 months)
Regards,
Tomolimo

**Comment by satyan01** [comment]
Hello Tomolimo

Any news about this great plugin ? 

end of the year ?

**Comment by tomolimo** [comment]
In fact it's already available, but currently there is no wiki

**Comment by tomolimo** [comment]
Look into the 3.0.0 branch...
But BEWARE that it's still beta development,
And you must use the version of ProcessMaker server I'm maintaining here: https://github.com/tomolimo/processmaker-server otherwise you'll go into bugs and incompatibilities with GLPi.
Normally this PM server release can be used as is in IIS (this is my configuration)
regards,
Tomolimo

**Comment by satyan01** [comment]
Hello thank you

after doing the instructions I have this message
![image](https://cloud.githubusercontent.com/assets/15144026/20348864/fefc8d94-ac07-11e6-8dc2-8995e05736a4.png)


IIS 8.5 windows 2012r2 / php 5.6.19 /

**Comment by tomolimo** [comment]
could you open an issue instead of polluting the existing one?

**Comment by satyan01** [comment]
Sorry, I can't open issue on processmaker server page

**Comment by tomolimo** [comment]
you may now, i've set the feature

**Comment by Gambware** [comment]
This plugin will be available to GLPI 9.X.X versions ?

**Comment by tomolimo** [comment]
Yes, I already have a version running on my 9.1.2 GLPi test server. As soon as I'll do the migration to my production server, I'll release the new version of the plug-in. This migration is currently planned for the 11th of March. So we may be confident that end of March will see the new plugin version. 
Regards 
Tomolimo

**Comment by CCoruble** [comment]
Hi,
Sorry for asking the same question as everybody but I'm very interested on this plugin.
Do you have any idea when the GLPI 9.1.2 compatible version will be finished ? 

Another question : Will this plugin require external workflow server ( I read a certain ProcessMaker server)  or everything will be controlled IN glpi ? 
(Answer N*2 would be really nice by the way !)
Regards
CCoruble

**Comment by tomolimo** [comment]
Hello,
To give some news about this plugin:
We have just finished GLPI 9.1.2 migration in our company, the plugin is already running with this version. So now, I'm going to work on the official release of the plugin, and the wiki also.
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @CCoruble ,
Sorry for being so late to answer your question,

> Another question : Will this plugin require external workflow server ( I read a certain ProcessMaker server) or everything will be controlled IN glpi ?

You need 'ProcessMaker server' to run the workflows (= processes), but you don't need another server (= machine), you can use the same web server, but need to have Apache (or nginx, or IIS) virtual hosts in this case. One virtual host to host GLPI, and another virtual host to host 'ProcessMaker server'.
This is not not mandatory, but is the best way to install and configure these web applications (there is another way to install ProcessMaker and GLPI on the same virtual host, but really I do not recommend it).

regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,

Update to 9.1 is here!
Wikis are under construction.
for server: https://github.com/tomolimo/processmaker-server/wiki
for plugin: https://github.com/tomolimo/processmaker/wiki

thank you for your feedbacks,
regards,
Tomolimo

**Comment by mparlas** [comment]
hello tomolimo, my php version is 5.6.19 thats compitable with processmaker 3.0.18 but im getting this error:
PHP Version >= 5.5.33: 5.4.16x

**Comment by tomolimo** [comment]
Hello,
Sorry for not answering your comment, but:
1. I've been in holidays last week,
1. It's been posted into a closed issue and has no relation with it.

Could you post a new issue?

Thank you
Regards,
Tomolimo
