### ISSUE TITLE
Process completed still DRAFT

### ISSUE THREAD

**Issue by grego1981** [tomolimo/processmaker#47]
Hi @tomolimo !

I have created and tested a case in processmaker (Followed the tutorial in PM documentation) I have started the case from GLPI ticket I have completed it but it still appears as draft and I can see no way to close it. And I can see no way to edit the task as completed...

![capture](https://user-images.githubusercontent.com/9021998/35625340-a89f416e-069a-11e8-9666-821d50905188.PNG)

![capture2](https://user-images.githubusercontent.com/9021998/35625276-700fad02-069a-11e8-8d17-c07359252d0a.PNG)

I have no buttons above the process also when trying to view the case info , map and dynaforms the page will not expand.

**Comment by tomolimo** [comment]
hello @grego1981 
Could you tell me the versions of processmaker plugin and of processmaker server you are using?
Thank you
Tomolimo

**Comment by grego1981** [comment]
The plugin is 3.2.3 and I have installed the PM version 3.0.1.8-community provided and recommended by this plugin but installed a while ago

**Comment by tomolimo** [comment]
PM server version must be 3.0.1.8-community-RE-1.8, could you check if this is the release you've installed?

**Comment by grego1981** [comment]
This is the data from the PM server info:

![capture](https://user-images.githubusercontent.com/9021998/35626811-89aa39d0-069f-11e8-907b-9fabb2153d1d.PNG)

**Comment by tomolimo** [comment]
Then you don't have the right server, you must use the latest one from here: https://github.com/tomolimo/processmaker-server/releases/latest

**Comment by grego1981** [comment]
I have upgraded to the latest release and still have the same exact behaviour

Upgrade command output:

Upgrading workspaces (1/1): workflow
> Updating database...
-> 1 tables to alter
-> Nothing to change in the data base structure of RBAC
-> Row updated in DASHLET
-> Row updated in DASHLET
-> Row updated in DASHLET
-> Row updated in DASHLET
-> Verifying roles permissions in RBAC
    All roles permissions already updated
0 records where patched to use SELF_SERVICE feature.
<*>   Database Upgrade Process took 0.27960705757141 seconds.
> Verify enterprise old...
    Without changes...
<*>   Verify took 0.00013399124145508 seconds.
> Updating translations...
Updating database translations with processmaker.el.po
Updating XML form translations with processmaker.el.po
Updating database translations with processmaker.en.po
Updating XML form translations with processmaker.en.po
<*>   Updating Translations Process took 40.399249076843 seconds.
> Updating Content...
Rows Processed ---> 2698 .....
Rows Clustered ---> 2141 .....
Rows Unchanged ---> 1114 .....
Rows Inserted  ---> 1584 .....
Rows Total     ---> 4282 .....
<*>   Updating Content Process took 1.6127190589905 seconds.
> Check Mafe Requirements...
<*>   Check Mafe Requirements Process took 0.0024368762969971 seconds.
> Updating cache view...
-> Creating tables
-> Update DEL_LAST_INDEX field in APP_DELEGATION table
-> Creating triggers
<*>   Updating cache view Process took 0.075966119766235 seconds.
> Backup log files...
<*>   Backup log files Process took 8.9883804321289E-5 seconds.
> Migrate new lists...
<*>   Migrate new lists Process took 2.0813910961151 seconds.
> Updating Files Manager...
<*>   Updating Files Manager took 0.0092620849609375 seconds.

Safe upgrade for files cached by the browser

Upgrade successful


Info page on PM

![capture](https://user-images.githubusercontent.com/9021998/35628109-923eba04-06a3-11e8-8312-a5f1b678cffd.PNG)

**Comment by tomolimo** [comment]
thank you,
Could you also screen copy the Procesmaker plugin configuration?
And give also the URL of GLPI you are using (screen copy of the browser)?
thank you
Tomolimo

**Comment by tomolimo** [comment]
anyway, the case in GLPI will never be updated as somewhere the code has died and the case has not been updated in GLPI tables. But what I can see is that you can't see the whole page in the 'Processmaker tab' this shows me that there is a problem with the domains between GLPI and PM.

**Comment by grego1981** [comment]
You were right the display problem resolves if I use the FQDN of the GLPI server instead of IP. But still even if it completed it shows up as draft...
![capture](https://user-images.githubusercontent.com/9021998/35628749-880c3ac8-06a5-11e8-854b-ada1ec71cc25.PNG)

**Comment by tomolimo** [comment]
The info in the tab (draft) is coming from a GLPI table. The status is currently only updated during update of the case. So if for any reason the code dies, then it may not be updated
It can happen with the problem of the domains that were not in synch.
Could you do another test?

**Comment by grego1981** [comment]
I deleted the case from the database and from the PM. Started the case with correct domain and completed it. When I returned to GLPI after completing the task, it was still Draft....

**Comment by tomolimo** [comment]
Oups
Let's have a look into the logs! 
Could you post them? 
Thank you 
Regards 
Tomolimo

**Comment by grego1981** [comment]
There is nothing in php_errors log or sql_errors log. In the processmaker installation in apache error log I find these errors:

[Wed Jan 31 18:34:08.190625 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP Notice:  Undefined index: TAS_UID in /var/www/processmaker/workflow/engine/methods/cases/cases_Open.php on line 85, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882
[Wed Jan 31 18:34:08.190647 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP Stack trace:, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882
[Wed Jan 31 18:34:08.190654 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP   1. {main}() /var/www/processmaker/workflow/public_html/glpi/app.php:0, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882
[Wed Jan 31 18:34:08.190658 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP   2. include() /var/www/processmaker/workflow/public_html/glpi/app.php:261, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882
[Wed Jan 31 18:34:08.190661 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP   3. include() /var/www/processmaker/workflow/public_html/app.php:61, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882
[Wed Jan 31 18:34:08.190665 2018] [:error] [pid 10593] [client 25.25.25.3:56477] PHP   4. require_once() /var/www/processmaker/workflow/public_html/sysGeneric.php:2028, referer: http://10.10.99.12/glpi/front/ticket.form.php?id=2882

**Comment by grego1981** [comment]
Correction! The only log entry in error is 
[Wed Jan 31 20:39:18.119418 2018] [:error] [pid 25644] [client 10.10.99.12:41284] PHP Notice:  Trying to get property of non-object in /var/www/processmaker/workflow/engine/methods/services/soap2.php on line 756
Fatal Python error: PyEval_AcquireThread: NULL new thread state

**Comment by tomolimo** [comment]
Hello,
Could you check where the PM server logs are?
If not set (I know for some OS, PHP error log is not set by default), could you set it to the php-error.log file of GLPI, so that we'll get all PHP errors in the same file?
see https://github.com/tomolimo/processmaker/issues/39#issuecomment-354281483
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @grego1981 
To go forward on this issue, and as I can't reproduce this behavior, I propose that you prepare a VM (a vmdk HDD file: either VMWare or either VirtualBox) this VM should include GLPI and PM server and reproduce the behavior. Then you may send it to me via https://wetransfer.com/
and you may post here the link, or send it to my professional email address (tell me I'll post my email if you want so).
Thank you
Regards,
Tomolimo

**Comment by grego1981** [comment]
Hi,

I'm on a bussiness trip, as soon as I'll be back I will try to prepeare them. Just to clarify, the pmaker and glpi servers are on different machines.

**Comment by tomolimo** [comment]
ok, then you may prepare two VMs if you want or try both servers on only one VM.

**Comment by grego1981** [comment]
Hi @tomolimo, 

I'm back, and trying to figure out if it is possible to send you the VMs. The problem is they're big about 60GBs each and one of them is running other services as well... 
The GLPI server rund on a machine running php 7.0 and that is the reason I cannot run both servers on the same machine. If you want I can discuss other options (eg. controlled remote access )
For me it seems that the problem is when PM is trying to update the GLPI DB... Hope I can be of assistance.

Thank you!

**Comment by tomolimo** [comment]
Hello,
My ideas were to either make two VM from the running servers or either to prepare one new VM on which you would have installed GLPI and PM server, and on which you would have reproduced the issue. 
Another possibility is to remote to your computer in order to try to troubleshoot this issue.
Just tell me what you prefer. 
Thank you 
Regards 
Tomolimo

**Comment by grego1981** [comment]
Hi @tomolimo,

We can arrange for remote access whenever you want. 

BR
Gregory

**Comment by tomolimo** [comment]
Hello @grego1981,
Current week is not possible for me. Would it be OK for you next week on Monday (2018-02-07), let's say at 13:00 UTC+1 CET?
regards,
Tomolimo

**Comment by grego1981** [comment]
No problem, I'm available! Thank you!

**Comment by tomolimo** [comment]
Hello @grego1981,
Here is my professional email address: olivier.moron@araymond.com

**Comment by grego1981** [comment]
I want to publicly thank you @tomolimo ! You've really helpful pointing me out my errors! For anybody with the same problem the solution lies within the wiki, concerning the Submit button if in PM.

Thank you again!! great work and even better support!!

**Comment by tomolimo** [comment]
Dear @grego1981 ,

After investigations, it appears that the ID of the submit button of the dynaforms is not named the right way, like written here: https://github.com/tomolimo/processmaker/wiki/Tutorial-1 it must be named `btnGLPISendRequest`

Thank you,
Regards,
Tomolimo
