### ISSUE TITLE
"Drag and drop your file here, or" => Bug on the accent and Required fields no work

### ISSUE THREAD

**Issue by juveboss** [tomolimo/processmaker#48]
Hello Tomolimo,

I have two problem : 

1) Required fields are not taken into account:
     => The user can do "Send the request" without having a reminder that the fields are mandatory ...

2) "Drag and drop your file here, or" => Bug on the accent 

![image](https://user-images.githubusercontent.com/31047406/35694936-337910ec-0783-11e8-98a4-aadb2b2e9e6d.png)

Plugin : Release 3.2.4
Server : Release 3.0.1.8-RE-1.8

Thanks

**Comment by tomolimo** [comment]
Hello @juveboss ,

Here are the answers to your issues:

1. The process doesn't respect what is explained about selfservice interface (simplified interface): see [Tutorial 2](https://github.com/tomolimo/processmaker/wiki/Tutorial-2). Anyway I can see that this mechanism is really complex, and that I must rewrite this part of the plugin see: https://github.com/tomolimo/processmaker/issues/49
1. Wait for coming new release ([3.2.5](https://github.com/tomolimo/processmaker/commit/c5589795df311ed791a37e723e70a990805d1177)) :smiley: 

Thank you,
Regards,
Tomolimo
