### ISSUE TITLE
Rewrite of interface between GLPI and Processmaker server

### ISSUE THREAD

**Issue by tomolimo** [tomolimo/processmaker#49]
Hello,

Currently this mechanism must be rewritten to insure better integration, better maintenance, and and better evolution possibilities.

This concerns central interface, and simplified interface (selfservice).
This should be a way to cancel the use of the so-called 'common domain' between GLPI  and PM server, and such simplify integration.
It should be also a way to minimize PM server customization.

Regards,
Tomolimo

**Comment by rohit-ambre-uno** [comment]
Yes this would really help a lot to configure GLPI with Processmaker.
Hope it comes out soon

**Comment by rohit-ambre** [comment]
Hi,
Any update on this

How you have thought of doing it?

and Can we use Processmaker REST APIs?
How can we use GLPI in APP with processmaker, GLPI has REST apis but how to integrate processmaker?
This is just for suggestion I'm not posting it as a requirement

Thank You

**Comment by tomolimo** [comment]
Hello @rohit-ambre 
Currently no updates :(
But one thing: I remember to have read something on the REST API definition that it was mono-user (no possibility to have several users logged-in at the same time)... This restriction (if still actual) will be a showstopper to use the REST API.

But anyway, the original issue was not about the use of the REST API (even if I'm also looking at it), but about the interface used for the Dynaforms...

regards,
Tomolimo

**Comment by tomolimo** [comment]
Fixed by 4.4.0 for GLPI 9.5 (or 5.0.0 for GLPI 10.0)
