### ISSUE TITLE
News about 9.2 compat

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker#5]
Hello Tomolimo

Have you planned to update this plugin to glpi 9.2 or 9.1 ?

If yes when ?

software, materials dependencies in glpi are missing.

I saw in itop ITSM software it is very useful.

Thank you for your answer

Yannick

**Comment by tomolimo** [comment]
Hello satyan01,

Yes, of course, it is planned to be compatible to 9.2, as it is already running with 9.1.2
When? when 9.2 will be available **and** used in our company.

> software, materials dependencies in glpi are missing.
> 
> I saw in itop ITSM software it is very useful.

I don't understand what you would like about this, could you explain?

thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue as I got no answer, feel free to re-open if you need.
