### ISSUE TITLE
Add configuration option for DBDefault

### ISSUE THREAD

**Issue by orouet** [tomolimo/processmaker#50]
My database doesn't conform to default naming scheme so i must edit db.class.php to connect to my db.
Could you add a field in the config form to set the database used by the Mysql User ?

**Comment by tomolimo** [comment]
Hello,
Could you please post a screen copy to explain what you would like? 
Thank you 
Regards 
Tomolimo

**Comment by orouet** [comment]
You are selecting the processmaker db based on a naming scheme (db.inc.php line 21 : $this->dbdefault = "wf_".$config->fields['pm_workspace']);
In my case, the processmaker database name is processmaker30 so the config form never connect to the database.

**Comment by tomolimo** [comment]
Yes the wf_ is used as a prefix.
And I'm not sure that if you don't respect it you may use processmaker in a good way. 
I'll check it this afternoon and keep you updated.

**Comment by tomolimo** [comment]
Hello @orouet 
I've checked, and I'm still not sure that PM server will work in a good way if you don't respect the `wf_` prefix (as there is plenty of code in PM server that uses the prefix).
See the example in the PM server wiki: http://wiki.processmaker.com/3.0/ProcessMaker_Generic_Installation#Step_4:_Installation_Wizard where the name of the DB is changed to something else than wf_workflow, but still using the prefix.

I'm going to do an evolution to the plugin to be able to configure the database name
But in the meantime, you may change the `db.class.php`.

Thank you
Regards,
Tomolimo
