### ISSUE TITLE
Add configuration option for SoapClient

### ISSUE THREAD

**Issue by orouet** [tomolimo/processmaker#52]
We are using a local CA so we must set a local certificate for SoapClient or we must entirely disable SSL checks.
We do so on editing openSoap function in processmaker.inc.php
Could you add an option in the configuration form to disable SSL checks ?

**Comment by tomolimo** [comment]
Hello @orouet 
I'm sure to understand you when you speak about CA?
What would you like to do with SSL?
Thank you,
Regards,
Tomolimo

**Comment by orouet** [comment]
Yes SSL/TLS
You could also add an option to set the public Base URL of PM which can be different from the private Base URL used by the SoapClient.

**Comment by tomolimo** [comment]
> You could also add an option to set the public Base URL of PM which can be different from the private Base URL used by the SoapClient.

No it cannot be different, otherwise the server will not be able to work with HTTP_REFERER information.

**Comment by orouet** [comment]
Yes SSL on the PM server and on the GLPI server. If we don't use SSL on PM server, we have Mixed Content Error

**Comment by tomolimo** [comment]
Hello @orouet 
I didn't forget you, but I'm working in a company and I've also other topics to manage.

So to come back to your request, and especially:

> You could also add an option to set the public Base URL of PM which can be different from the private Base URL used by the SoapClient.

Could you give me more details about this sentence?

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
> We do so on editing openSoap function in processmaker.inc.php

Hello @orouet,
I'm in the process of adding this feature, to help me doing that, could you post your code?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Fixed in https://github.com/tomolimo/processmaker/releases/tag/3.3.8
and in https://github.com/tomolimo/processmaker/releases/tag/3.4.5
