### ISSUE TITLE
Incorrectly Escaped strings

### ISSUE THREAD

**Issue by orouet** [tomolimo/processmaker#53]
When we activate the plugin, newly created tickets show escaped characters with backslashes

**Comment by tomolimo** [comment]
Hello,
Could you give steps to reproduce the issue? And my be also screen copies?
Thank you,
Regards,
Tomolimo

**Comment by orouet** [comment]
![2018-02-13 15_10_20-glpi - tickets - 2094](https://user-images.githubusercontent.com/6570165/36153939-28b588d8-10d0-11e8-9c7e-3fe36be65772.png)

**Comment by tomolimo** [comment]
Thank you,
But I would like to have steps to be able to reproduce this issue.

> Could you give steps to reproduce the issue?

Thank you,
Regards,
Tomolimo

**Comment by orouet** [comment]
New ticket in simplified interface. All special chars are escaped with backslashes
![image](https://user-images.githubusercontent.com/6570165/36154903-24a9c396-10d3-11e8-8eee-206c3e72fc98.png)

**Comment by tomolimo** [comment]
Hello
Thank you, but I still don't understand how you can create such ticket.
Could you give the steps to reproduce this?
Thank you,
Regards,
Tomolimo

**Comment by orouet** [comment]
We are writing a ticket using the simplified interface.
The PM process is active and associated to a catagory
When we submit the request (or change the category), the description is recorded by GLPI in such form.
When we disable the plugin we can't reproduced this prob.

**Comment by tomolimo** [comment]
Thank you,
but I really need more information in order to reproduce this issue.
I need the configuration of the PM plugin, I need the configuration of GLPI 
I need the steps with screen copies to reproduce the steps.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @orouet 
Any news?
Thank you
Regards,
Tomolimo
