### ISSUE TITLE
Can't modify and log in users

### ISSUE THREAD

**Issue by BlackxRyan** [tomolimo/processmaker#57]
Hi tomolino.

Using the automatic action "pmusers", I synchronized the users I created on GLPI with Processmaker.

![image](https://user-images.githubusercontent.com/36700904/39189171-e5dfcb0c-47d1-11e8-8c19-6e9e079501b3.png)

But when I try to edit these users by clicking on "Edit", I have a blank screen. 

![image](https://user-images.githubusercontent.com/36700904/39189247-13a77580-47d2-11e8-8725-dfc010f17f05.png)

And I can't log in into Processmaker with these accounts too. I can only log in with them in GLPI.

![image](https://user-images.githubusercontent.com/36700904/39189680-17cf89f8-47d3-11e8-96b8-f7f1288d3fa5.png)

Is there a thing to do I missed ?

Thanks in advance.

**Comment by tomolimo** [comment]
Hello
1. For security reasons, you cannot log into PM server with these accounts.
1. But anyway you should be able to view the users form. Could you look at the log files?
Thank you 
Regards 
Tomolimo

**Comment by BlackxRyan** [comment]
Hi.

Here are the browser logs (there is nothing in processmaker logs) : 

![image](https://user-images.githubusercontent.com/36700904/39231023-f4a7a76c-4868-11e8-9b64-d1f511332f5e.png)

**Comment by tomolimo** [comment]
and in GLPI logs?

**Comment by BlackxRyan** [comment]
![image](https://user-images.githubusercontent.com/36700904/39234246-033dcafe-4873-11e8-8c59-a3d85b118482.png)

![image](https://user-images.githubusercontent.com/36700904/39234386-67aabc18-4873-11e8-978d-73cc2edf459a.png)

**Comment by tomolimo** [comment]
Hello
What I expected were the PHP log files. 
Thank you 
Regards 
Tomolimo

**Comment by BlackxRyan** [comment]
Where I can find them ?

**Comment by tomolimo** [comment]
in your glpi folder, in files/_log

**Comment by BlackxRyan** [comment]
![image](https://user-images.githubusercontent.com/36700904/39245671-b5c50950-4894-11e8-836b-ed6b7e775eb3.png)

![image](https://user-images.githubusercontent.com/36700904/39245703-c5b03fd8-4894-11e8-9960-9ebfb530dd26.png)

**Comment by tomolimo** [comment]
Oups, sorry, I didn't pay attention to the date...the errors were before you installed the right version (3.0.1.8-RE-1.8)?

Could you try to get the logs of the PM server? To know where they are you should go to the PM server PHP Information, and then on the php_info page, you shoul dbe able to search for the error log path.

Thank you
Regards,
Tomolimo

**Comment by BlackxRyan** [comment]
No, the errors were after I installed the right version.

I looked several times at the php info page but I can't find the error log path.

**Comment by tomolimo** [comment]
> No, the errors were after I installed the right version. 

do you mean the $status errors?


> I looked several times at the php info page but I can't find the error log path.

search for "error_log" like shown below:
![image](https://user-images.githubusercontent.com/7569958/39247282-400aaa1c-4899-11e8-885b-669e087cca5d.png)

**Comment by BlackxRyan** [comment]
The errors in cron.log and php-errors.log.
-----
That's why I couldn't find, there is "no value".

![image](https://user-images.githubusercontent.com/36700904/39247484-d536c350-4899-11e8-8c89-239430a60288.png)

**Comment by tomolimo** [comment]
then it's a good practice to set this in your php.ini file, and then restart your web server, and then retest in order to get errors (if any).

**Comment by BlackxRyan** [comment]
I have the path now.

![image](https://user-images.githubusercontent.com/36700904/39248613-ddcc81d2-489c-11e8-95b4-c42880e987bc.png)

I restarted my web server and retested but the file is empty.

**Comment by tomolimo** [comment]
And do you still have the $status error in the GLPI logs?

**Comment by BlackxRyan** [comment]
No accroding to the dates.

![image](https://user-images.githubusercontent.com/36700904/39248919-afd39698-489d-11e8-8591-451fc99a8a5c.png)

**Comment by tomolimo** [comment]
Which version of GLPI are you using?

**Comment by BlackxRyan** [comment]
9.2.2

**Comment by tomolimo** [comment]
really, I can't see what's going on :sob: 

the ultimate idea: I may remotely connect to your machine and I can try to find the issue.

**Comment by BlackxRyan** [comment]
There's no problem but I'm using VirtualBox so I don't know if you can.

I could give you the virtual HDD of my VM but his size is 4.5Go.

**Comment by tomolimo** [comment]
on last idea: could post a screen copy of the PM plugin config?
What's the PM server URL and the GLPI URL?

**Comment by BlackxRyan** [comment]
PM plugin config

![image](https://user-images.githubusercontent.com/36700904/39251949-d5fe0b1c-48a4-11e8-8f6e-4178a79d024d.png)

PM server URL (Home) : 10.0.2.15:8080/sysworkflow/fr-FR/neoclassic/cases/main

GLPI URL : 10.0.2.15/glpi

**Comment by BlackxRyan** [comment]
If these info can't help more, give me your email to send you my VM's HDD.

**Comment by tomolimo** [comment]
I think that you should try with FQDN server names instead of ip addresses.
Like for GLPI: http://glpi.test.com/ and for PM server http://pm.test.com/ using two virtual hosts in your web server configuration.

Another idea: did you install PM server "workflow" workspace in one DB or in 3 DBs?

**Comment by BlackxRyan** [comment]
Ok, I'll try it.

> Another idea: did you install PM server "workflow" workspace in one DB or in 3 DBs?

In one DB I think (wf_workflow).

**Comment by tomolimo** [comment]
> In one DB I think (wf_workflow).

could you check it?

**Comment by BlackxRyan** [comment]
Yes, one DB 

![image](https://user-images.githubusercontent.com/36700904/39253161-8088e258-48a7-11e8-87ad-155561d8700d.png)

**Comment by BlackxRyan** [comment]
So I created FQDN server name "glpi.com" for GLPI but I can't login and the URL shows "?error=2".

![image](https://user-images.githubusercontent.com/36700904/39255318-856ee1f0-48ac-11e8-9665-6678e8b241a8.png)

**Comment by BlackxRyan** [comment]
I created 2 FQDN Server names "glpi.com" and "processmakertest.com" and it solved the issue !

![image](https://user-images.githubusercontent.com/36700904/39256720-e5d28be8-48af-11e8-91b9-4d54b4da6188.png)

Maybe it was because they weren't using the same port.

Thanks for all the time you spent helping me.

**Comment by tomolimo** [comment]
normally not, but who knows?

**Comment by tomolimo** [comment]
thank you for your feedback.

**Comment by BlackxRyan** [comment]
You're welcome, I'll tell you if I have an other issue.
