### ISSUE TITLE
Blank screen when trying to sync tasks

### ISSUE THREAD

**Issue by BlackxRyan** [tomolimo/processmaker#58]
Hi Tomolino.

I created tasks on Processmaker and then cases (by the way, I don't really understand how it works).

![image](https://user-images.githubusercontent.com/36700904/39296529-70e26d16-4941-11e8-84e4-5e2b057b7777.png)

![image](https://user-images.githubusercontent.com/36700904/39296888-647c73e0-4942-11e8-930c-4be23c45bd64.png)

And when I try to sync the task list on the GLPI plugin, I have a blank page.

![image](https://user-images.githubusercontent.com/36700904/39296961-94357ea6-4942-11e8-9970-0c13a6bca6aa.png)

![image](https://user-images.githubusercontent.com/36700904/39296983-a25f25ae-4942-11e8-9f56-339269380e6b.png)

**Comment by tomolimo** [comment]
Hello @BlackxRyan 
1. You may find valuable explanations on the wikis: https://github.com/tomolimo/processmaker/wiki and http://wiki.processmaker.com/index.php/ProcessMakerDocumentation3_0
1. The blank task page is due to a problem of language definition in PM, see: https://github.com/tomolimo/processmaker-server/wiki/Languages

regards,
Tomolimo

**Comment by BlackxRyan** [comment]
They both use the same language and I downloaded the PM one on sourceforge but I still have this blank page.

![image](https://user-images.githubusercontent.com/36700904/39306478-9955b072-4960-11e8-911c-822f9bcd9a29.png)

![image](https://user-images.githubusercontent.com/36700904/39306544-bcc05ae4-4960-11e8-833b-a501c7534896.png)

**Comment by tomolimo** [comment]
You have installed fr-FR, and that's not respecting what is written here: https://github.com/tomolimo/processmaker-server/wiki/Languages

**Comment by tomolimo** [comment]
you have to modify the content of the po file like explained in the wiki

**Comment by BlackxRyan** [comment]
Just saw it. It's now good.

![image](https://user-images.githubusercontent.com/36700904/39313692-e42087fa-4972-11e8-83ab-ea5a0ef56c51.png)

I'm going to try again.

**Comment by BlackxRyan** [comment]
I still have a blank screen...

**Comment by tomolimo** [comment]
what do you have in the log files?

**Comment by BlackxRyan** [comment]
![image](https://user-images.githubusercontent.com/36700904/39315466-0273efae-4977-11e8-8a26-7ba5bed50c49.png)

**Comment by tomolimo** [comment]
So nothing interesting for us

I'll check that when I get home

**Comment by tomolimo** [comment]
Hello @BlackxRyan 

Several questions:
1. What language did you set for the main language in GLPI? 
1. What language did you use to create your process in PM?
1. Could you check the table CONTENT from the WF_WORKFLOW DB in MySQL? Use `SELECT * FROM CONTENT WHERE CON_CATEGORY = 'TAS_TITLE'` to select all the task titles of all processes in PM. You should be able to find for which languages the tasks have been defined, please post the result.

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @BlackxRyan 
Thank you

> And despite creating processes and tasks with fr language, the table CONTENT has task in english, that's strange. 

That's perfectly normal, as you may have users who will use English for their UI, then PM server needs translations (which by default are the identical to the language you used to create the process).

At the end I need your VM to be able to debug the task refresh. Could you upload it to any cloud service (like onedrive, or else)?

Thank you,
Regards,
Tomolimo

**Comment by BlackxRyan** [comment]
Here it is : https://www.reep.io/d/weaajpfnwn

**Comment by tomolimo** [comment]
Can't get it, it shows the following screen:
![image](https://user-images.githubusercontent.com/7569958/39350876-cd4a7c10-49ff-11e8-8dae-02f0f58b07fc.png)

**Comment by BlackxRyan** [comment]
Retry it, it should be ok.

**Comment by tomolimo** [comment]
that will not work for us as it is using a port that's not open in our proxy:
![image](https://user-images.githubusercontent.com/7569958/39351081-9de569e8-4a00-11e8-80d0-fb785fa1de74.png)

**Comment by BlackxRyan** [comment]
I'm going to upload it on Google Drive, I'll give you the link.

**Comment by tomolimo** [comment]
ok, thank you

**Comment by BlackxRyan** [comment]
I uploaded the whole VM file just in case, here it is : https://drive.google.com/drive/folders/1Gnc08_UnXL2gIo7G3jLwBxkwdCz1qWVH?usp=sharing

**Comment by tomolimo** [comment]
I'm currently downloading it

**Comment by BlackxRyan** [comment]
Just thought about something. You may need my login and my password to log in my VM. Where can I send you these ?

**Comment by BlackxRyan** [comment]
Also is your plugin compatible with the new version of GLPI (9.2.3) ?

**Comment by tomolimo** [comment]
Hello @BlackxRyan 

> Just thought about something. You may need my login and my password to log in my VM. Where can I send you these ?

Yes, please send them to olivier.moron@araymond.com

> Also is your plugin compatible with the new version of GLPI (9.2.3) ?

it should be, but to be tested, as it was compatible with 9.2.2


regards,
Tomolimo

**Comment by BlackxRyan** [comment]
Your plugin seems to be working on GLPI 9.2.3 as it syncs the processes correctly.

I sent you the IDs.

**Comment by BlackxRyan** [comment]
Problem solved, the "intl" module (for language) was missing.

Just have to do "apt-get install php5-intl".

Thanks a lot for your help tomolino.

**Comment by tomolimo** [comment]
You're welcome,
Regards 
Tomolimo
