### ISSUE TITLE
Problem starting a PM task in a GLPI ticket

### ISSUE THREAD

**Issue by BlackxRyan** [tomolimo/processmaker#59]
Hi tomolino.

I followed your [Tutorial](https://github.com/tomolimo/processmaker/wiki/Tutorial-1) but when I try to start a case :

![image](https://user-images.githubusercontent.com/36700904/40354143-80c4c144-5db3-11e8-8e86-d1ebcc99e525.png)

It shows this message.

![image](https://user-images.githubusercontent.com/36700904/40354106-68dfffd0-5db3-11e8-9def-5b6875ee60b4.png)

It looks like I missed something but I don't know where it is.

**Comment by tomolimo** [comment]
Hello @BlackxRyan 
Check these:
1. Did you assigned a group or a user to the first task? Or is the assigned group empty? Or which users are in the assigned group? Are they in GLPI?
1. Did you synchronized the GLPI users with the PM users using the pmusers 'automatic action'?

Regards,
Tomolimo

**Comment by BlackxRyan** [comment]
1. Yes : 
![image](https://user-images.githubusercontent.com/36700904/40354992-95a0d89e-5db5-11e8-9822-a18a7abc640b.png)
![image](https://user-images.githubusercontent.com/36700904/40355051-bde75ada-5db5-11e8-8471-d020fd1b8a45.png)

2. Yes, I used pmusers and they are synchronized.

**Comment by tomolimo** [comment]
Are your current GLPI user in this group?

**Comment by tomolimo** [comment]
Let's say that your current GLPI user doesn't have the right to start this new case.

**Comment by BlackxRyan** [comment]
That was it, the "glpi" user didn't had the rights. I had to add him in the Assigned users list in the PM case.

Thanks again.
