### ISSUE TITLE
Wiki Improvment

### ISSUE THREAD

**Issue by Pihdit** [tomolimo/processmaker#6]
Hi,

I would like to ask if it possible to improve Wiki about this plugin?
I'm interested to use it on test server but I failed to install/configure it (Debian/Apache).
Process flow in GLPI it's exactly what I need :)
Thank you for your effort.

**Comment by tomolimo** [comment]
Yes, it's planned

**Comment by zidex** [comment]
+1
Need more documentation

**Comment by tomolimo** [comment]
Hello,

Wiki for server is currently under construction, but you may do some tests if you want.
https://github.com/tomolimo/processmaker-server/wiki
Thank you for your feedbacks,

regards,
Tomolimo

**Comment by tomolimo** [comment]
Done, https://github.com/tomolimo/processmaker/wiki
regards,
Tomolimo
