### ISSUE TITLE
Can't connect to SQL server

### ISSUE THREAD

**Issue by BlackxRyan** [tomolimo/processmaker#60]
Hi tomolino.

I'm now trying to work on the society domain with two separate virtual machines : 

172.17.255.2 : pm.1fogenie.fr
172.17.255.138 : glpitest.1fogenie.fr

These two domain names are registered in the DNS server.

The processmaker setup is ok : 

![image](https://user-images.githubusercontent.com/36700904/40667118-a64c00ea-6361-11e8-95db-e028b9278f50.png)

But I can't connect to the SQL server and I'm sure the logins are the correct ones.

![image](https://user-images.githubusercontent.com/36700904/40667206-d8f8c8b6-6361-11e8-83b9-8b67e530d3cc.png)

The database is named wf_workflow : 

![image](https://user-images.githubusercontent.com/36700904/40667244-efd9d552-6361-11e8-935a-5fd4565c2526.png)

And my user has all privileges : 

![image](https://user-images.githubusercontent.com/36700904/40667269-0c340d44-6362-11e8-9399-2733dc36d2f5.png)

**Comment by tomolimo** [comment]
Hello @BlackxRyan 

Where is the mysql server? On the GLPI machine or on the PM machine?

Regards,
Tomolimo

**Comment by BlackxRyan** [comment]
On both. Which one I have to use ?

**Comment by tomolimo** [comment]
the one which hosts PM DB.
and the 'SQL server' must contains the server name of the server hosting the PM DB

**Comment by BlackxRyan** [comment]
Where can I check that ?

**Comment by tomolimo** [comment]
in PHPmyadmin

**Comment by tomolimo** [comment]
Seems like your root user has only the localhost access, and not the remote '%'

**Comment by tomolimo** [comment]
or any host that is valid. In your case, you may use glpitest.1fogenie.fr

**Comment by BlackxRyan** [comment]
Here are the users : 

![image](https://user-images.githubusercontent.com/36700904/40668750-958d1f56-6365-11e8-81c9-a39bfd14f1b5.png)

**Comment by tomolimo** [comment]
then you may use the root as it has the % and also the glpitest.1fognie.fr in its client field.
Note: that only one of both is necessary.

**Comment by tomolimo** [comment]
ah, sorry I didn't see the Grant: 'non' for 'glpitest....' so anyway the root has the client % so there is no restriction to us it from glpi server.

**Comment by BlackxRyan** [comment]
It just updated 

![image](https://user-images.githubusercontent.com/36700904/40669027-436528a8-6366-11e8-973f-c5e11a899afc.png)

So what do I put in the SQL server field ?

![image](https://user-images.githubusercontent.com/36700904/40669061-5508d104-6366-11e8-8696-9da9d53f0a85.png)

**Comment by tomolimo** [comment]
pm.1fogenie.fr
wf_workflow
root
root password

**Comment by BlackxRyan** [comment]
Still not works 

![image](https://user-images.githubusercontent.com/36700904/40669253-cd813784-6366-11e8-89d0-fe4bff6fdbb3.png)

And it takes a while to load.

**Comment by tomolimo** [comment]
try with IP address instead of pm.1fogenie.fr

**Comment by BlackxRyan** [comment]
Doesn't work too.

**Comment by tomolimo** [comment]
Could it be possible that something prevents network traffic from glpitest.1fogenie.fr to pm.1fogenie.fr?

**Comment by BlackxRyan** [comment]
Each machine can ping the other, and the PM configuration worked...

**Comment by BlackxRyan** [comment]
Solved, I used what was told here : https://stackoverflow.com/a/14779244/9590095

I used the IP address for MySQL configuration (and created a user pm too).

![image](https://user-images.githubusercontent.com/36700904/40706058-e8b9f5dc-63ec-11e8-9b94-f3b319f7dbba.png)

It works correctly now.

![image](https://user-images.githubusercontent.com/36700904/40706026-d1b3304c-63ec-11e8-8130-39b5f161cd7d.png)

Thanks for your help
