### ISSUE TITLE
GLPI configuration not saving

### ISSUE THREAD

**Issue by BlackxRyan** [tomolimo/processmaker#61]
Hi tomolino.

I'm now installing the plugin on the enterprise's GLPI.

But when I put the data in the configuration page.

![image](https://user-images.githubusercontent.com/36700904/40963187-06c328e0-68a8-11e8-84f8-9174d444dfc7.png)

It doesn't do anything and the data disappears.

![image](https://user-images.githubusercontent.com/36700904/40963256-3b0271a6-68a8-11e8-9b40-4276ea77c74d.png)

And the strange thing is that it automatically put the domain even before I put it and the Processmaker tab stays in GLPI even when the plugin is uninstalled.

This is a GLPI 9.1.7.1 installed on a Debian 9 with MariaDB (so it's maybe simply not compatible with MariaDB).

Also, a previous version of your plugin (3.2.5) was installed before (I uninstalled it of course but I maybe have to delete the previous data from this version).

**Comment by tomolimo** [comment]
Hello @BlackxRyan,
I'm a little bit surprise with these screen copies: they seem to be outdated and not compliant with your version...
Which version of plugin do you use?

Thank you
Regards,
Tomolio

**Comment by BlackxRyan** [comment]
The last version, 3.2.8.

**Comment by tomolimo** [comment]
Could you have a look into the log files?

**Comment by BlackxRyan** [comment]
Which one(s) ?

**Comment by tomolimo** [comment]
GLPI and PM server

**Comment by BlackxRyan** [comment]
Ok, I'll watch as soon as I can.

**Comment by BlackxRyan** [comment]
Looks like there is a problem with the rights.

![image](https://user-images.githubusercontent.com/36700904/41086216-9e5a6370-6a39-11e8-9433-6b8c87d9cbe3.png)

**Comment by tomolimo** [comment]
Then this is very easy to fix, isn't it?
Just add the rights on the PM DB server for admin from machine 'glpi.1fogenie.fr'

**Comment by BlackxRyan** [comment]
I added the rights but it still doesn't work, and there is no more php errors.

**Comment by BlackxRyan** [comment]
I noticed something strange in the database. The password is not the one I used.

![image](https://user-images.githubusercontent.com/36700904/41088034-aedc3a34-6a3e-11e8-8964-77e2b2edeb24.png)

**Comment by tomolimo** [comment]
the password is encrypted in the config table

**Comment by BlackxRyan** [comment]
Ok I see

**Comment by tomolimo** [comment]
regarding the issue: I've never saw that before, I believe I must connect to your installation in order to check.
could it be possible this evening?

**Comment by BlackxRyan** [comment]
Sadly, it's a GLPI used everyday by the enterprise and this is a 500GB machine so I can't have a copy...

In my opinion, it's either an incompability with MariaDB or a conflict with an other plugin as they have many.

![image](https://user-images.githubusercontent.com/36700904/41088865-d65ae55e-6a40-11e8-9550-2f71e3e11305.png)
(They restored the snapshot so it's normal there is an old version of your plugin)

**Comment by tomolimo** [comment]
Best practice is to have a test server which should be a copy of the prod server, so that you may do real tests.
But anyway what is the size of the GLPI DB? Could it be possible for you to build a test server with the same DB?

**Comment by BlackxRyan** [comment]
The DB size is around 15MB, I could do a copy but how can I retrieve the copy after ?

**Comment by tomolimo** [comment]
Do a dump, then copy the file on another machine (test machine VM) and do a restore on this machine.
On this test machine, install GLPI, install PM, and so on... and try as most as possible to match production serve setting: same OS, same PHP version, same GLPI version, same PM version, and so on.

**Comment by BlackxRyan** [comment]
Ok, I'll see with my superior.

**Comment by BlackxRyan** [comment]
My internship ends tomorrow, I will sadly not have enough time to solve this.

Anyway, thanks for all.

**Comment by tomolimo** [comment]
You're welcome, keep in touch anyway, if you need.

**Comment by BlackxRyan** [comment]
No problem, I'll tell you :)
