### ISSUE TITLE
Facing issues while attaching process case to ticket 

### ISSUE THREAD

**Issue by vikijha** [tomolimo/processmaker#62]
*** PHP Notice(8): Undefined index: pm_users_id
  Backtrace :
  ...ins/processmaker/inc/processmaker.class.php:202 
  ...ins/processmaker/front/processmaker.form.php:26 PluginProcessmakerProcessmaker->login()
  ...ins/processmaker/front/tracking.injector.php:43 include()
2018-06-23 06:19:34 [7@vikass-MacBook-Pro.local]
  *** PHP Notice(8): Undefined index: pm_users_id
  Backtrace :
  ...ins/processmaker/inc/processmaker.class.php:203 
  ...ins/processmaker/front/processmaker.form.php:26 PluginProcessmakerProcessmaker->login()
  ...ins/processmaker/front/tracking.injector.php:43 include()
2018-06-23 06:19:34 [7@vikass-MacBook-Pro.local]
  *** PHP Notice(8): Undefined index: password
  Backtrace :
  ...ins/processmaker/inc/processmaker.class.php:205 
  ...ins/processmaker/front/processmaker.form.php:26 PluginProcessmakerProcessmaker->login()
  ...ins/processmaker/front/tracking.injector.php:43 include()
2018-06-23 06:19:35 [7@vikass-MacBook-Pro.local]
  From PluginProcessmakerProcessmaker::login() in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/processmaker/inc/processmaker.class.php line 220
  Processmaker Plugin:  - Soap problem: stdClass Object
(
    [status_code] => 4
    [message] => Wrong password
    [version] => 2.0
    [timestamp] => 2018-06-23 02:19:35
)

**Comment by tomolimo** [comment]
Hello,
Could you please send me the processmaker server configuration, the processmaker plugin configuration and GLPI configuration?
Thank you 
Regards 
Tomolimo

**Comment by vikijha** [comment]
<img width="903" alt="glpi config" src="https://user-images.githubusercontent.com/22476101/41809505-712e8de2-770c-11e8-9f86-b9bc099f1f52.png">
<img width="1351" alt="pm groups" src="https://user-images.githubusercontent.com/22476101/41809507-7225d94e-770c-11e8-91b3-b2a1b1ae6296.png">
<img width="1323" alt="pm users" src="https://user-images.githubusercontent.com/22476101/41809508-72af929c-770c-11e8-89f0-f70e017c2122.png">
<img width="1346" alt="skin-config" src="https://user-images.githubusercontent.com/22476101/41809509-73c8e278-770c-11e8-893c-2447e6f1dfe9.png">
<img width="1011" alt="glpi" src="https://user-images.githubusercontent.com/22476101/41809528-c97bf32c-770c-11e8-9e15-16d747cbbcf3.png">

**Comment by tomolimo** [comment]
Hello,
Thank you for the screencopies. 
Could you also send the processmaker system configuration and the plug-in configuration and GLPI system configuration? 
Thank you 
Regards 
Tomolimo

**Comment by vikijha** [comment]
Hi Tomolimo  , 

Fixed this issue , this issues was occurring because sync between gulp_users and plugin_users was not happening. 

Thanks for quick response

**Comment by tomolimo** [comment]
You're welcome,
Regards 
Tomolimo
