### ISSUE TITLE
Sub-process management 

### ISSUE THREAD

**Issue by tomolimo** [tomolimo/processmaker#64]
Sub-process management

**Comment by rohit-ambre-uno** [comment]
Good Idea!
Looking forward to it.

**Comment by tomolimo** [comment]
Already available as a beta in the master branch :)
This beta has been running on my test server for almost 1 month and has been tested with several processes and sub-processes

**Comment by tomolimo** [comment]
Fixed by 60beb4cca00d4d160e1af42233a8b35ccc2b9fb1
