### ISSUE TITLE
stdClass Object error while configuring.

### ISSUE THREAD

**Issue by shraddharsh** [tomolimo/processmaker#65]
While I try to configure
everything seems to work fine other than server administrator password. It gives me an error of stdClass object.
The message being pretty vague, neither there are any httpd logs that I could figure out what exactly and where is the error.
Please provide a proper response to resolve the issue.

**Comment by tomolimo** [comment]
Hello,
Could you post your GLPI, ProcessMaker server and plugin configurations? 
Thank you 
Regards 
Tomolimo

**Comment by shraddharsh** [comment]
Hi @tomolimo 
I was only trying to configure processmaker and that's when I encountered this issue.
Please find below the screenshot of my processmaker configuration.
![Configuration](https://user-images.githubusercontent.com/5519861/42130980-94bab26a-7d13-11e8-8eba-2f06aad2909f.png)

**Comment by tomolimo** [comment]
Hello @shraddharsh 

Could you follow the wiki?
Main page here: https://github.com/tomolimo/processmaker/wiki
Plugin configuration here: https://github.com/tomolimo/processmaker/wiki/Plugin-configuration

Thank you,
Regards,
Tomolimo

**Comment by shraddharsh** [comment]
Hi @tomolimo ,
I resolved the issue by entering the correct credentials.
Previously I tried configuring entering credentials of GLPI and then tried using credentials of processmaker and it worked.

But apart of this I've been having issue regarding **cross-origin frames** which at the moment I'm going through using the **--disable-web-security** mode.

**Comment by tomolimo** [comment]
Hello @shraddharsh 
For the cross-origin-frames, you must use a domain for GLPI and a domain for PM, and these domain must have a common root, for exemple:
GLPI: glpi.mydomain.com
PM: pm.mydomain.com
or
GLPI: myserver.mydomain.com
PM: myserver.mydomain.com:8000

Note 1: localhost cannot be used, as it doesn't define any domain.
Note 2: the common domain must have at least two parts, like 'mydomain.com'. For exemple: '.com' is not enough.

Try this and it will solve the issue.

regards,
Tomolimo
