### ISSUE TITLE
Facing issues while running pmusers  automatic action script 

### ISSUE THREAD

**Issue by vikijha** [tomolimo/processmaker#66]
Fatal error: Call to a member function login() on null in processmaker.class.php on line 1153

**Comment by tomolimo** [comment]
Hello @vikijha 
Could you copy/paste your Processmaker plugin configuration?
And give version of plugin and version of GLPI?
It looks like plugin is not initialized correctly.
Thank you
regards,
Tomolimo

**Comment by vikijha** [comment]
**correct  I did config changes and now its showing following error** 

PHP Notice: Undefined index: pm_users_id in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/processmaker/inc/processmaker.class.php at line 215
PHP Notice: Undefined index: pm_users_id in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/processmaker/inc/processmaker.class.php at line 216

Fatal error: Cannot redeclare plugin_init_processmaker() (previously declared in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/processmaker/setup.php:6) in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/Processmaker/setup.php on line 120

<img width="905" alt="image" src="https://user-images.githubusercontent.com/22476101/42309366-f759207e-8055-11e8-8fc0-aa105c8f6bf1.png">

**Comment by tomolimo** [comment]
Hello @vikijha 

I think that you have a problem with the ProcessMaker server configuration itself.
Are you using the server I've provided? See: https://github.com/tomolimo/processmaker/wiki/Introduction

> This plugin is dedicated to provide a process management linked to tickets. This goal is achieved using a customized ProcessMaker server (https://github.com/tomolimo/processmaker-server). 

Could copy/paste the configuration screen shots of the ProcessMaker server configuration? See: https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check

Thank you
Regards,
Tomolimo

**Comment by vikijha** [comment]
Yes let me download updated one i merged your yesterday code. Let me download full code.

**Comment by tomolimo** [comment]
???

**Comment by tomolimo** [comment]
Which version of ProcessMaker server did you use?

**Comment by vikijha** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/22476101/42312087-0ba6f61c-805d-11e8-9c0d-c36de607fedf.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/22476101/42312099-127e6740-805d-11e8-98c3-82d1579d9479.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/22476101/42312104-18af1bf0-805d-11e8-94dd-cb807b1584f6.png">

**Comment by tomolimo** [comment]
Thank you
Do you still have the issue?

**Comment by vikijha** [comment]
yes still I am not able to execute pmusers script

**Comment by tomolimo** [comment]
Could you copy/paste the ProcessMaker server PHP error logs?
To find this file, you have to look at the php_config() results: see https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check#php-information

**Comment by vikijha** [comment]
in process maker I am not finding any error but in glpi following message is appearing 

2018-07-05 09:09:49 [2@vikass-MacBook-Pro.local]
  *** PHP Notice(8): Undefined index: pm_users_id
  Backtrace :
  ...ins/processmaker/inc/processmaker.class.php:216 
  plugins/processmaker/hook.php:382                  PluginProcessmakerProcessmaker->login()
  :                                                  plugin_processmaker_post_init()
  inc/plugin.class.php:1272                          call_user_func()
  inc/includes.php:123                               Plugin::doHook()
  front/crontask.form.php:37                         include()
2018-07-05 09:09:50 [2@vikass-MacBook-Pro.local]
  From PluginProcessmakerProcessmaker::login() in /Applications/XAMPP/xamppfiles/htdocs/glpi-9.2/plugins/processmaker/inc/processmaker.class.php line 234
  Processmaker Plugin:  - Soap problem: stdClass Object
(
    [status_code] => 3
    [message] => User not registered!
    [version] => 2.0
    [timestamp] => 2018-07-05 05:09:50
)

**Comment by vikijha** [comment]
processmaker.class.php - there is line which is commented 1152 . I uncommented this and working fine 

// start a processmaker session
1152       $PM_SOAP = new PluginProcessmakerProcessmaker();
1153       if (!$PM_SOAP->login( true )) {
1154          $task->log( "Error PM: '".print_r($PM_SOAP->lasterror, true)."'" );
1155          return -1;
1156       }

**Comment by tomolimo** [comment]
Ok I understand the issue...
By default I try to login the current GLPI user, but if the current user is not in glpi_plugin_processmaker_users table then login crashes and when in a cron, there is no current user...

**Comment by tomolimo** [comment]
Thank you for you post-back.
I believe there is a side effect between login and post_init which tries to log current user...
Thank you for your feedback, I'll check this in details.

**Comment by vikijha** [comment]
when I am attaching process to ticket getting following error 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/22476101/42316158-c00c4be4-8066-11e8-8347-b8e4e5f45d29.png">

**Comment by tomolimo** [comment]
In your profile setting, you should check the rights to view the cases

**Comment by tomolimo** [comment]
![image](https://user-images.githubusercontent.com/7569958/42316364-d8011ff8-8049-11e8-8913-e69d7e7a3d28.png)

**Comment by vikijha** [comment]
Getting following error when attaching process in ticket 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/22476101/42317014-f0f4bc94-8068-11e8-9011-2c64d8d33967.png">

**Comment by tomolimo** [comment]
I advise you to change the default session timeout and set it to 10hours, or at least to the same value than for GLPI
![image](https://user-images.githubusercontent.com/7569958/42317349-72f601de-804c-11e8-8a65-787aa998191f.png)

**Comment by tomolimo** [comment]
to workaround this: logout from GLPI and login again

**Comment by tomolimo** [comment]
Any news? or workaround for this issue?

**Comment by vikijha** [comment]
Hi Tomolimo , 

Sorry I was out yes issues resolved but setting cookie  parameter 👍
