### ISSUE TITLE
Task addition in GLPI after assignment of processmaker task

### ISSUE THREAD

**Issue by rohit-ambre-uno** [tomolimo/processmaker#67]
I want to add task in GLPI for that user after assigning task of Processmaker, so that user can understand he has some task to work on
Now, only initial task of process creation is getting created with first user and it is not getting updated after every task of processmaker 
I am using GLPI 9.2.4 with your version of Processmaker-server from your repository and processmaker plugin 3.2.8

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 

What you are describing is how the plugin is working! :smiley: 

But may be you are missing something in the configuration of the plugin or in the process definition by itself.

Could you give more information about plugin configuration?

Could you give more information about the process you are using?

Did you try the tutorials? Here: https://github.com/tomolimo/processmaker/wiki/Tutorials

Thank you 
Regards,
Tomolimo

**Comment by rohit-ambre-uno** [comment]
Hi,
This is my Plug-in configuration
![glpi setup](https://user-images.githubusercontent.com/31683834/42634188-2baf3d9a-8600-11e8-9e25-bbecddb9c964.png)


and when i tried to run a case which has SQL query it throws following error
`PHP Fatal error:  Call to undefined function glpi_savePHP2File() in /opt/processmaker/workflow/engine/classes/class.pmScript.php on line 209,`

`PHP Fatal error:  Uncaught exception 'PropelException' with message ' [wrapped: No database selected]' in /opt/processmaker/gulliver/thirdparty/propel/util/BasePeer.php:473`

and it also throws an error while saving trigger

` PHP Fatal error:  Call to undefined function glpi_saveTrigger2File() in /opt/processmaker/workflow/engine/classes/model/Triggers.php on line 222`

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 
Could you show me the URL rewrite rule that should be defined in your web server?
See https://github.com/tomolimo/processmaker-server/wiki/Inbound-rewrite-rules
By the way is this related to the current issue? If not, could please open a new one.
Thank you
Regards,
Tomolimo

**Comment by rohit-ambre-uno** [comment]
Hi,
URL Rewrite rule did solved my errors with those function calls.

But i am still not able to assign glpi task to user

this is my process configuration
![glpi processmaker 2](https://user-images.githubusercontent.com/31683834/42695831-198e12b0-86d4-11e8-8bba-5d29114b94cc.png)

Can you guide me about this

**Comment by tomolimo** [comment]
Hello
Did you read and test the tutorials already? 
Regards 
Tomolimo

**Comment by rohit-ambre-uno** [comment]
Hi,
I Figured that I was not using 'btnGLPISendRequest' id for submit button which was caused this issue.
Thank you for your support.

But I have one small doubt, how do I change the State of ticket after any task completion, as per the documentation, I created a trigger as follows and set it to run after routing
`@@GLPI_ITEM_SET_STATUS = 'Pending';`
It is not working, can u suggest something here

Also for auto attachment of PM Task we have to put a specific regex given in documentation with Process UID but can we use some other method and have it configurable from the front-end
for eg. if ticket is of type _incident_ and some field is set to some value then 'PM1' process is getting attached and different process for different values of that field.

**Comment by tomolimo** [comment]
Hello
As mentioned in the wiki @@GLPI_ITEM_SET_STATUS accepts a number in the range 1 to 12. This number corresponds to the internal values of the ticket statuses.

For your suggestion for starting a new case with specific field values: it's a good idea, could you create a new issue for that?

Thank you 
Regards 
Tomolimo

**Comment by rohit-ambre-uno** [comment]
Hi @tomolimo ,
I apologise if being too repetitive with my questions.
I have been coming across this issue long time and have being trying to come over that.
I'm trying to change state of the ticket on the basis of a trigger, but the thing is I've tried testing it with at least 40 to 50 tickets but have been unsuccessful with it.
What I tried is 
added a glpi variable i.e. @@GLPI_ITEM_SET_STATUS and setting it a value for example
`@@GLPI_ITEM_SET_STATUS=2` also `@%GLPI_ITEM_SET_STATUS=2` (Which is the correct representation for an integer)
I'd appreciate if you could give me an example for setting this variable.
Thank you.
