### ISSUE TITLE
Processmaker Login screen in GLPI Process-Case tab

### ISSUE THREAD

**Issue by rohit-ambre-uno** [tomolimo/processmaker#71]
Hi @tomolimo ,
I have been testing the plugin functionalities and while doing so I came across a bug where in at times processmaker (server) login screen appears all of a sudden for certain actions i.e. the user gets logged out from processmaker.
I myself am going through this bug and trying to figure out what might be causing the issue. Just so you know it beforehand I'm posting this issue even before my debugging.
This bug appears on the following pages..
1. Process-case tab
I tried refreshing it did not go away
so I had to logout and log back in GLPI to solve it.

![pmlogininglpi](https://user-images.githubusercontent.com/31683834/42990140-7f99871a-8c1f-11e8-8fa1-8ebc431b2cd5.png)

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 
The way to workaround this issue is to increase the "Cookie lifetime" in processmaker server, and to set it to 36000 seconds.
See https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check#system

Thank you,
Regards,
Tomolimo
