### ISSUE TITLE
This plugin requires GLPI >= 9.1 and 9.3

### ISSUE THREAD

**Issue by GaneshKudikala** [tomolimo/processmaker#73]
Kindly update the plugin to use the latest version of GLPI

**Comment by tomolimo** [comment]
Hello @GaneshKudikala 
The plugin is already compatible with 9.2.x, and is planned to be migrated to 9.3 during next autumn.
Thank you,
Regards,
Tomolimo

**Comment by henriqueferraz86** [comment]
> Olá @GaneshKudikala
> O plugin já é compatível com o 9.2.x, e está planejado para ser migrado para 9.3 durante o próximo outono. 
> Obrigado, 
> Atenciosamente, 
> Tomolimo


hello when are we going to version 9.3?

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/processmaker/releases/tag/3.5.1
Thank you
Regards,
Tomolimo

**Comment by henriqueferraz86** [comment]
Hello, when do we go to version 9.4?

**Comment by tomolimo** [comment]
please, when an issue is closed, create a new one...
