### ISSUE TITLE
manual assignment rule

### ISSUE THREAD

**Issue by shahmilan34** [tomolimo/processmaker#79]
I tried using Manual assignment rule but it is not working in GLPI it redirects to same dynaform and gives following error in logs
```
From PluginProcessmakerProcessmaker::routeCase() in /var/www/html/glpi/plugins/processmaker/inc/processmaker.class.php line 306
  routeCase res: stdClass Object
  (
      [status_code] => 15
      [message] => The task is defined for Manual assignment
      [timestamp] => 2018-08-13 13:50:51
  )
```

manual assignment is working in processmaker server but not in GLPI

I am using 
processmaker-server : Release 3.0.1.8-RE-1.8
processmaker-plugin : 3.2.8
GLPI: 9.2.4

Kindly suggest

**Comment by tomolimo** [comment]
Hello @shahmilan34 

'Manual assignment' is not directly supported. 
But you may implement it:
1. Add a dynaform in the steps of your task
1. This dynaform will propose a list of users via a dropdown, a suggest or else (checkbox, checkgroup, radio).
1. This dropdown is assigned to a variable, 
1. This variable is to be used for the next task assignment value selecting 'Value Based Assignment'.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @shahmilan34 
Here is a process sample of what I explained above:
[test_manual_assignment-1.pmx.zip](https://github.com/tomolimo/processmaker/files/2282746/test_manual_assignment-1.pmx.zip)

Thank you
Regards,
Tomolimo

**Comment by shahmilan34** [comment]
Yeah, I know this method.
Thank you for providing an example

**Comment by tomolimo** [comment]
You're welcome
