### ISSUE TITLE
PM tablenames in lowercase

### ISSUE THREAD

**Issue by zidex** [tomolimo/processmaker#8]
Often the PM tablenames in SQL queries are used in lowercase, which creates a problem with MySQL on Linux.
MySQL on Linux is case sensitive.

**Comment by tomolimo** [comment]
Hello, 
In GLPI, table names are lower case... 
An option exists in mysql to workaround this issue. 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
Do you have any error message?

**Comment by zidex** [comment]
After using **lower_case_table_name = 1**, some errors were resolved
But the plugin does not work properly
When I click Start on the Process-Case tab in the Ticket, I get an error of 404
![default](https://cloud.githubusercontent.com/assets/28188353/25560536/6870a4f8-2d5f-11e7-8147-0e8ce91410ce.png)
At this time in the log:
127.0.0.1 - - [30/Apr/2017:04:21:27 +0300] "GET /sysworkflow/en/glpi_classic/cases/cases_open?sid=72729100059053c160d8c77032425377&APP_UID=95787720759053c16366995062240925&DEL_INDEX=1&action=TO_DO&rand=1131200075 HTTP/1.1" 302 - "http://glpi.znet.local/front/ticket.form.php?id=9" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [30/Apr/2017:04:21:28 +0300] "GET /errors/error404.php?url=%2Fsysworkflow%2Fen%2Fglpi_classic%2Fcases%2Fcases_open%3Fsid%3D72729100059053c160d8c77032425377%26APP_UID%3D95787720759053c16366995062240925%26DEL_INDEX%3D1%26action%3DTO_DO%26rand%3D1131200075 HTTP/1.1" 404 2901 "http://glpi.znet.local/front/ticket.form.php?id=9" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

pm.znet.local (127.0.0.1) - ProcessMaker Apache2 vhost on my local machine
glpi.znet.local (127.0.0.1) - GLPI Apache2 vhost on my local machine

**Comment by tomolimo** [comment]
Hello, 
Did you install the PM server that I released in processmaker-server github site (version 3.0.1.8-RE-1.2)? Or did you use the standard PM server? 
To help you, I need to have your configuration of GLPI, and of PM server, and of PM plugin. 
Thank you 
Tomolimo

**Comment by zidex** [comment]
I use PM version 3.0.1.8-RE-1.2 from your github repo
What conf files should I provide?

**Comment by zidex** [comment]
GLPI version 9.1.3

**Comment by tomolimo** [comment]
Hello 
Not yet tested with 9.1.3
Configuration of the plug-in itself (screen copy of the config) 
Configuration of PM server 
Thank you 
Regards 
Tomolimo

**Comment by zidex** [comment]
![pmsetup](https://cloud.githubusercontent.com/assets/28188353/25567733/146472ba-2dfd-11e7-8466-90f783b1165e.png)
What information is needed about PM server?

**Comment by tomolimo** [comment]
Did you do some tests? 
Like process creation, case start? 
Anyway I'm going to prepare a complete wiki about configuration, tests, guidelines and a sample of a running process from creation to execution in GLPi. 
Please wait some days for it to be completed. 
Thank you 
Regards 
Tomolimo

**Comment by zidex** [comment]
Ок. I will wait for information on the wiki.

**Comment by tomolimo** [comment]
Hello,

Wiki for server is currently under construction, but you may do some tests if you want.
https://github.com/tomolimo/processmaker-server/wiki
Thank you for your feedbacks,

regards,
Tomolimo
