### ISSUE TITLE
Modified Attachment code for 3.2.8

### ISSUE THREAD

**Issue by rohit-ambre-uno** [tomolimo/processmaker#81]
Dear @tomolimo ,
This Discussion is referenced with issue #78  regarding file upload.
Modified plugin code for attaching files from **file** web control and **grid** is only compatible with the new version of processmaker i.e. 3.3.2 and processmaker-server RE-1.9.
And processmaker 3.3.2 has subprocess which allows multiple processes to run on single GLPI ticket which we dont want to allow in GLPI. So can we have that attachment code compatible with old version of processmaker plugin 3.2.8 and server RE-1.8.
So GLPI users can see only one process running directly in Process-case tab and can start working on it and he doesn't have to choose which one to work on.

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 

To come back on this question: for me the main way to work with a process in a ticket is not via the Process-case tab, but via the 'Processing ticket' tab of the ticket in which all the tasks are grouped.

I can add an option to prevent process start  when already one (or more) is (are) already started. I mean an option for a maximum processes.

regards,
Tomolimo

**Comment by rohit-ambre-uno** [comment]
My concern here was regarding file attachment code you provided in #78 which you said is compatible with processmaker 3.3.2 and processamaker-server 1.9 but it actually works for processmaker 3.2.8 and I cannot use processmaker 3.3.2 because it enables multiple processes but if you can provide option to choose number of processes then I can give it a try.
For now I have modified file attachment code as mentioned in #78 in last comment. and it is working fine for me.

**Comment by tomolimo** [comment]
Hello @rohit-ambre-uno 
As you proposed me to help developing new features, could you provide a pull request with this evolution?
I really don't have times currently to develop features that are not requested by my company.
Thank you
Regards,
Tomolimo*

**Comment by tomolimo** [comment]
Merged into release https://github.com/tomolimo/processmaker/releases/tag/3.4.9 and https://github.com/tomolimo/processmaker/releases/tag/3.5.1
