### ISSUE TITLE
No view Dynaform in GLPI

### ISSUE THREAD

**Issue by mickaelccc** [tomolimo/processmaker#83]
Hello,

First thx for your work and for this plugin 

All seems to be good but i cant see dynaform in GLPI (Everything works perfectly in processmaker)

I installed processmaker-server-3.0.1.8-RE-1.9 on Centos 7 with Apache 2.4.6 / php 5.6.38 / MySQL 5.5.50 / GLPI 9.2 (with Plugin Processmaker 3.3.1)

I Disabled / cleaned all plugins
![processmaker2](https://user-images.githubusercontent.com/45623827/49529661-cead4b80-f8b6-11e8-87bb-7ba6883d2364.jpg)

![processmaker1](https://user-images.githubusercontent.com/45623827/49524505-285c4880-f8ac-11e8-876a-30f6a6d25502.jpg)

I added the process example "Remplacement materiel non standard" (i replaced group "Employé" with "GLPI users" i did the change in processmaker "Designer" )

I was able to:

sync process
![image](https://user-images.githubusercontent.com/45623827/49528587-7ecd8500-f8b4-11e8-9de4-86180fe9ddca.png)

sync tasks list
![image](https://user-images.githubusercontent.com/45623827/49528607-88ef8380-f8b4-11e8-96f4-d8c61126fe78.png)

add process 
![image](https://user-images.githubusercontent.com/45623827/49526406-082e8880-f8b0-11e8-92bd-839e06ece2cf.png)

The Map view is really small i dont know why...
![image](https://user-images.githubusercontent.com/45623827/49525920-116b2580-f8af-11e8-8883-e4cdff653cc3.png)

There is my problem... :(
![image](https://user-images.githubusercontent.com/45623827/49525155-686ffb00-f8ad-11e8-9095-a81cdba06b59.png)

I dont have any error in PHP information "No value"
![image](https://user-images.githubusercontent.com/45623827/49528512-58a7e500-f8b4-11e8-8c27-f7d35bd3b458.png)

Sync group "GLPI Users" : OK
![image](https://user-images.githubusercontent.com/45623827/49526641-8ab74800-f8b0-11e8-9429-43ba37ca1ba7.png)

Permission in Processmaker(Admin & Operator) : OK 
![image](https://user-images.githubusercontent.com/45623827/49526683-a3276280-f8b0-11e8-9a0c-c951bf6d815b.png)

Permissions (in processmaker) : OK
![image](https://user-images.githubusercontent.com/45623827/49528124-a2440000-f8b3-11e8-96b7-b90428341557.png)

Rules of affectations : OK
![image](https://user-images.githubusercontent.com/45623827/49528217-d5868f00-f8b3-11e8-9685-b360d9cb45f2.png)

Add lang : I think its okay but i'm not really sure 
![image](https://user-images.githubusercontent.com/45623827/49526738-c18d5e00-f8b0-11e8-8c29-1a5f1210c8ca.png)

Add skins : OK
![image](https://user-images.githubusercontent.com/45623827/49526768-d4a02e00-f8b0-11e8-9f05-06d46702eab4.png)

PM requirements : OK 
![image](https://user-images.githubusercontent.com/45623827/49526996-40829680-f8b1-11e8-893c-a1ba2968c38e.png)

Informations systeme :
![processmaker3_](https://user-images.githubusercontent.com/45623827/49527177-9d7e4c80-f8b1-11e8-9805-5e95fc8dcb70.jpg)

Log GLPI:
sql-errors.log : no error

php-errors.log : i have this 

" Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/processmaker/inc/case.class.php:605        _e()
  plugins/processmaker/inc/case.class.php:731        PluginProcessmakerCase::showForItem()
  inc/commonglpi.class.php:482                       PluginProcessmakerCase::displayTabContentForItem()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab() "

I have tried almost everyting you provide  in the issue "[Tutorial 1] No view dynaform #39" 

Thanks you for your help & time

**Comment by tomolimo** [comment]
Hello @mickaelccc 

Thank you for all of these screen shots.

I think your problem is that you have installed PM server `3.0.1.8-community-RE-1.9`, but I can guarantee you that you are not using it. Unfortunately you are using the `3.0.1.8-community` version

I can be so sure, because, of the version number here in your screenshots:
![image](https://user-images.githubusercontent.com/7569958/49568695-02798700-f932-11e8-99d9-12f42f4b5255.png)

It should be `3.0.1.8-community-RE-1.9` and not `3.0.1.8-community` (which is the version from ProcessMaker)

So please check your installation, and keep me informed.

Thank you
Regards,
Tomolimo

**Comment by mickaelccc** [comment]
Hello Tomolimo,

Thank you for your anwser 

So i'll try new a installation asap

Thank you

**Comment by mickaelccc** [comment]
Hello Tomolino

I reinstall processmaker and i've the same issue with the dynaform :(
![2018_12_10_14_40_12_glpi_configuration](https://user-images.githubusercontent.com/45623827/49736306-0ab32880-fc8a-11e8-9584-764908b67857.png)

Thank you

**Comment by tomolimo** [comment]
Hello @mickaelccc 
This kind of error is usually linked to the so-called common domain between GLPI and PM.
Could check if there are errors in the php error-logs, and in your browser console (press F12 and reload your pages)? 
Thank you
Regards,
Tomolimo

**Comment by mickaelccc** [comment]
There is no error in my browser ( all status < 302 )
and in the php error logs the only thing i have :

Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/processmaker/inc/case.class.php:605        _e()
  plugins/processmaker/inc/case.class.php:731        PluginProcessmakerCase::showForItem()
  inc/commonglpi.class.php:482                       PluginProcessmakerCase::displayTabContentForItem()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()

i really dont understand what's happening...

thank you

**Comment by tomolimo** [comment]
Hello @mickaelccc,

Regarding the error on _e(: it's only a deprecated (will be fixed in next release).

but for the "common domain" issue:
What I can propose to you is that I can connect to your system (using for example Teamviewer, Jitsimeet or else) and then I can help you troubleshooting this.
It's up to you to propose a date and time, but I'll prefer to do it during evenings (around 20:30 UTC+1).
Regards,
Tomolimo

**Comment by mickaelccc** [comment]
Hello Tomolimo, 

I know you trying to help but I cant do that 
Do you have any check list i can use ?

Thank you

**Comment by tomolimo** [comment]
Hello @mickaelccc 

> I know you trying to help but I cant do that

What's the problem? Is it a question of time? or a question of security? If it's a question of time, I can do it also during your working hours, just tell me.

> Do you have any check list i can use ?

Here is a list of questions/things to do that can help to troubleshoot the issue:

1. Could you check and post the Apache config?
1. Could you check and post the hostname (=FQDN) of the GLPI server and of the PM server?
1. Could you post the GLPI url configuration? In menu Setup > General > General setup: field _URL of the application_.
1. The so-called _common sub-domain_ must at least be composed of two members, examples: `com` is wrong, `mydomain.com` is OK.
1. Hostname (=FQDN) of PM server must be ping-able from the GLPI server itself (if not installed on the same server). Means Hostname (=FQDN) of PM server must be in the DNS.
1. You may do a check in your browser using the developer tools (F12), but this time using the console to see javascript errors (and not only the network errors like you did already). I believe there is a javascript error with the `document.domain` property, or with something like `window.parent`. 

The advise I can give you is to re-read the Wiki regarding the installation of the PM server, especially the Apache2.4 configuration and inbound rewrite rule. See: [PM server installation](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-installation)

Regards,
Tomolimo

**Comment by tomolimo** [comment]
Closed as I got no answer for last comment.
Feel free to re-open if something is new on your side.
