### ISSUE TITLE
Error message on task derivation

### ISSUE THREAD

**Issue by rohit-ambre-uno** [tomolimo/processmaker#84]
I'm testing processmaker-3.3.2 and 3.4.5 with GLPI 9.2 and processmaker-server 3.3-RE-1.0.
after the current task is completed processmaker 3.3.2 onward it shows Error box like below
![screenshot from 2019-01-11 10-19-53](https://user-images.githubusercontent.com/31683834/51248353-d7189c00-19b5-11e9-9bb2-69a8ca0b65f8.png)

Which actually is not the error right? It is showing that because current task is not accessible to logged in user but then it shouldn't show such Error message as it seems like something is breaking.

Can't we use  same way like used in processmaker-3.2.8 and processmaker-server-3.0-RE-1.8
example:
![felicity ticket overview 600](https://user-images.githubusercontent.com/31683834/51248780-3cb95800-19b7-11e9-8ba9-6bf954047538.png)

As it also gives all information about the case and current state of case.

Can we change that page?

**Comment by tomolimo** [comment]
What are the steps to reproduce this behavior?
Could it be that you missed some authorizations in PM server for all operators?
See: https://github.com/tomolimo/processmaker-server/wiki/Roles#processmaker_operator

**Comment by rohit-ambre-uno** [comment]
Yeah, My bad.
I thought it would be something like this but I was not able to find this documentation so went through a code and changed the permissions.
There is no link for this documentations on Wiki page, is there?

Thank you for the documentations.
