### ISSUE TITLE
Error php-errors.log 

### ISSUE THREAD

**Issue by juveboss** [tomolimo/processmaker#86]
Hello,

I have a problem in files php-errors.log : 

![image](https://user-images.githubusercontent.com/31047406/51834580-0eaf0e80-22fb-11e9-805f-86c8e637df8c.png)

I used GLPI 9.2 / plugin processmaker 3.4.5 / Processmaker 3.3.0 and HTTPS

--

**Comment by tomolimo** [comment]
Hello @juveboss 
These kind of warnings:

> Headers and client library minor version mismatch

are from a problem in your version of PHP and version of MySQL, see https://stackoverflow.com/questions/10759334/headers-and-client-library-minor-version-mismatch 

Could you first fix this warning, and then we'll have a look at the other Notice.

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello again,

Could you also check that in your DB in table glpi_plugin_processmaker_configs the ssl_verify column exists?

Thank you

**Comment by tomolimo** [comment]
And also check that in this table the field db_version contains: 3.3.8?

**Comment by juveboss** [comment]
Hello Tomolimo.

iN GLPI_plugin_processmaker_configs  => No exist=> ssl_verify

i remove plugin in glpi and remove tables => ok work

You can close.
Thanks tomolimo
