### ISSUE TITLE
Can't add a new task on processmaker

### ISSUE THREAD

**Issue by mateusbays** [tomolimo/processmaker#89]
Hello Tomolimo,

Now i cannot add a new task, i follow all your tutorial guides but... it still not working....

**Comment by mateusbays** [comment]
when i use glpi on debug mode it says for me:
The requested URL /ajax/process.form.php was not found on this server.

**Comment by tomolimo** [comment]
Hello @mateusbays 
Could you give GLPI and ProcessMaker plugin versions?
Could you look into the log files and paste here any  logged errors?
Could you also copy/paste screen shots of your GLPI configuration and of the ProcessMaker plugin configuration?
Thank you,
Regards,
Tomolimo

**Comment by mateusbays** [comment]
Hello Buddy,
GLPI version: 9.3.1 
ProcessMaker Plugin Version: 3.5.1

http://prntscr.com/o3ywmo 
PM configurations.

http://prntscr.com/o3ywwn
https://prnt.sc/o3yxpk
http://prntscr.com/o3yxyc
http://prntscr.com/o3yya6
http://prntscr.com/o3yyey
http://prntscr.com/o3yylc

It doesn't work...
http://prntscr.com/o3yxfd

**Comment by tomolimo** [comment]
Hello @mateusbays
Could you look into the log files and paste here any logged errors?
Could you also copy/paste screen shots of your GLPI configuration?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I also need the configuration of the ProcessMaker  server

**Comment by mateusbays** [comment]
The instalation configuration of the PM server was the default mode instalation.

**Comment by tomolimo** [comment]
Hello @mateusbays 
Did you follow the wiki like shown here: [PM server config](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration), and checked the config like explained here: [PM server config check](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check)?
Thank you to provide the screen shots of the configuration, especially the language configuration.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Also could you tell me which language is used in GLPI by default?

**Comment by mateusbays** [comment]
We are using Portuguese(BRAZIL) language.

**Comment by tomolimo** [comment]
Hello @mateusbays,

Thank you, but if you don't answer to all my requests, I will not be able to help you,

Reminder of the requests:

1. Did you follow the wiki like shown here: [PM server config](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration), and checked the config like explained here: [PM server config check](https://github.com/tomolimo/processmaker-server/wiki/ProcessMaker-server-configuration-check)?
2. Thank you to provide the screen shots of the configuration, especially the language configuration.

Regards,
Tomolimo

**Comment by mateusbays** [comment]
Buddy,
 I started a VM to test processmaker, but I am with another issue... see the pic. thx
![pmissue](https://user-images.githubusercontent.com/49691726/60292537-bc970700-98f3-11e9-84f3-b0744eb2d9cf.JPG)

**Comment by tomolimo** [comment]
Hello @mateusbays 
1. Regarding your first issue: I'm sorry, but I cannot help you if you don't answer my questions. Hint: you have not correctly added the language in PM server. see [Language settings in PM server](https://github.com/tomolimo/processmaker-server/wiki/Languages)
1. if there is another problem, please open another issue.
Thank you

**Comment by mateusbays** [comment]
Hello Buddy, i found a new log error on glpi, maybe it should help us to solve the problem.

When i click in synchronize task list, the glpi debug mode shows me that error:
http://prntscr.com/orrpvl
http://prntscr.com/orrq8r

**Comment by tomolimo** [comment]
See my previous answer: [comment Jun 28](https://github.com/tomolimo/processmaker/issues/89#issuecomment-506629749) you have not set correctly the PM URL, and the GLPI URL in the settings.

**Comment by tomolimo** [comment]
Please note that URL looks like "http://sub.domain.ext/", and only "domain.com"

**Comment by tomolimo** [comment]
I close this issue as there is no feedback, please feel free to re-open if you want to add something.
