### ISSUE TITLE
designer impossible to drag and drop 

### ISSUE THREAD

**Issue by satyan01** [tomolimo/processmaker#9]
Hello, I have freshly installed processmaker, but I can't create process in designer

![image](https://cloud.githubusercontent.com/assets/15144026/25617810/690ef59a-2f44-11e7-99ec-0853a49571b3.png)

I noted in script src is /js/maborak/core/maborak.loader.js"></script>

I don't have this folder in process maker folder

**Comment by tomolimo** [comment]
Hello Satyan01,

Which version of ProcessMaker do you use?
Did you download the one here: [Lastest Release](https://github.com/tomolimo/processmaker-server/releases/latest)?

Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
Also, I believe this should post on the server issue list, not on the plugin issue list!

**Comment by satyan01** [comment]
Hello,

I tried this morning with your last version but same issue, I am going to post on your link
