### ISSUE TITLE
Processmaker GLPI 9.4

### ISSUE THREAD

**Issue by henriqueferraz86** [tomolimo/processmaker#90]
Hello when processmark is going to be available for version 9.4 of glpi.

This plugin is very important for workflow to help them.

Thank you very much.

**Comment by tomolimo** [comment]
Hello @henriqueferraz86 
Work is in progress ...

**Comment by mecmav** [comment]
that's good. we are waiting for that

**Comment by tomolimo** [comment]
Fixed by release 3.6.2: https://github.com/tomolimo/processmaker/releases/tag/3.6.2

**Comment by mecmav** [comment]
I Will test . Thx for now
