### ISSUE TITLE
Can't synchronise task list

### ISSUE THREAD

**Issue by ashkurin** [tomolimo/processmaker#91]
Hi Tomolimo!
First of all thank you for your work!

And about my problem - i can't synchronise task list for process in GLPi, .
I'm already read https://github.com/tomolimo/processmaker/issues/38 - problem not solved

Versions and other info:
PM server 3.3.0-community-RE-1.6
GLPi 9.4.3
PM Plugin for GLPi 3.6.4
MySql (Version 5.6.45)
Web Server nginx/1.16.1
PHP Version 7.1.32 for PM
php71-php-fpm-7.1.32 for PM
PHP parameter error_log = /var/opt/remi/php71/log/php-fpm/www-error.log, there no such file

PHP Version 7.3.9 for GLPi
php-fpm-7.3.9 for GLPi

Languages:
PM = English (en)
GLPi = English
I tried to use both English - English and English US in GLPi - not worked.

Thank you!

**Comment by ashkurin** [comment]
In GLPi in debug mode after trying sync task list i get such info:
Fatal error: Uncaught Error: Call to undefined function locale_get_primary_language() in /var/www/html/glpi/plugins/processmaker/inc/process.class.php:85 Stack trace: #0 /var/www/html/glpi/plugins/processmaker/front/process.form.php(22): PluginProcessmakerProcess->refreshTasks(Array) #1 {main} thrown in /var/www/html/glpi/plugins/processmaker/inc/process.class.php on line 85

**Comment by tomolimo** [comment]
Hello @ashkurin, 
Did you install intl PHP module (like required here: [Plugin Requirements](https://github.com/tomolimo/processmaker/wiki/Requirements))?
Thank you to check this,
Regards,
Tomolimo

**Comment by ashkurin** [comment]
>>Did you install intl PHP module
Yes, php-intl installed:
[root@sd nginx]# rpm -qa | grep intl
php73-php-intl-7.3.9-1.el7.remi.x86_64
php71-php-intl-7.1.32-1.el7.remi.x86_64

"Translation of dropdowns" is set to "Yes"

**Comment by tomolimo** [comment]
Hello @ashkurin 

> Fatal error: Uncaught Error: Call to undefined function locale_get_primary_language()

This means that PHP itself doesn't find the function locale_get_primary_language() which is from intl module: see: https://www.php.net/manual/en/locale.getprimarylanguage.php

You may do a small test in a PHP script: 
```
<?php
echo locale_get_primary_language('en-GB');
?>
```
to see if this error occurs with a simple code.

Another info is: could you coty/paste the information that are in the GLPI > Setup > System between the [code]...[/code]?

Thank you,
Regards,
Tomolimo

**Comment by ashkurin** [comment]
>could you copy/paste the information that are in the GLPI > Setup > System between the [code]...[/code]?

Information about system installation and configuration
[code]
 
GLPI 9.4.3 ( => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux sd.mof.local 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64
PHP 7.3.9 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cassandra, cgi-fcgi,
	crypto, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, json, ldap, libxml,
	mbstring, mcrypt, memcached, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap,
	sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.16.1
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.45
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.6.45) - Perfect!Database version seems correct (5.6.45) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.7 in (/usr/share/pear)

LDAP directories
 
SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP ()

Mails receivers
 
Name: '' Active: Yes
	Server: '{}INBOX' Login: 'support' Password: Yes

Plugins list
 
	appliances           Name: Appliances                     Version: 2.5.0      State: Enabled
	archisw              Name: Apps structures                Version: 2.1.2      State: Enabled
	impacts              Name: Asset impacts                  Version: 1.3.2      State: Enabled
	childticketmanager   Name: Child ticket manager           Version: 2.1.3      State: Enabled
	dashboard            Name: Dashboard                      Version: 0.9.6      State: Enabled
	manageentities       Name: Entities portal                Version: 3.1.0      State: Enabled
	escalation           Name: Escalation ticket              Version: 0.90+1.2   State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled
	genericobject        Name: Objects management             Version: 2.7.0      State: Enabled
	processmaker         Name: Process Maker                  Version: 3.6.4      State: Enabled
	reports              Name: Reports                        Version: 1.12.0     State: Enabled
	tasklists            Name: Tasks list                     Version: 1.5.0      State: Enabled
	databases            Name: Бази даних                     Version: 2.2.1      State: Enabled
	fields               Name: Дополнительные поля    Version: 1.10.1     State: Enabled
	moreticket           Name: Еще заявка                     Version: 1.5.0      State: Enabled
	positions            Name: Картография                   Version: 4.6.0      State: Enabled
	racks                Name: Конфигурация стойки    Version: 1.8.0      State: Enabled
	environment          Name: Окружение                      Version: 2.3.0      State: Enabled
	escalade             Name: Переназначение             Version: 2.4.3      State: Enabled
	behaviors            Name: Поведения                      Version: 2.2.1      State: Enabled
	mreporting           Name: Подробные отчеты          Version: 1.6.1      State: Enabled
	archires             Name: Сетевые архитектуры    Version: 2.6.0      State: Enabled

[/code]

Tomolimo, thank you!

**Comment by ashkurin** [comment]
>You may do a small test in a PHP script:
- no errors

**Comment by tomolimo** [comment]
As far as I can see, intl module is not in the list of modules of the PHP running GLPI...
Could you please check using the simple script I provided into a page in GLPI folder?
Name it test.php (for example), and call it via the GLPI url: http://myglpiserver/test.php

Thank you 
Regards 
Tomolimo

**Comment by ashkurin** [comment]
Tomolimo, afetr reinstalling php-intl there is no errors.

Thank you! Have a nice time!

**Comment by tomolimo** [comment]
You too
