### ISSUE TITLE
Synchronise task list trows exception on new install (trying to follow the tut)

### ISSUE THREAD

**Issue by Geo-Ron** [tomolimo/processmaker#93]
Current install:
-GLPI 9.4.3 on IIS with PHP7 and MariaDB
-Processmaker on the same server, IIS site with PHP 5.6.30 and the same MariaDB
-Processmaker 3.3.0-community-RE-1.6
-Processmaker plugin 3.6.5

Synchronise Process List works
for a process to start the task synchronisation the following exceptions shows in my screen:

```
Fatal error: Uncaught Error: Call to undefined function locale_get_primary_language() in D:\WebApplications\GLPI\plugins\processmaker\inc\process.class.php:85 Stack trace: #0 D:\WebApplications\GLPI\plugins\processmaker\front\process.form.php(22): PluginProcessmakerProcess->refreshTasks(Array) #1 {main} thrown in D:\WebApplications\GLPI\plugins\processmaker\inc\process.class.php on line 85
PHP Fatal error: Uncaught Error: Call to undefined function locale_get_primary_language() in D:\WebApplications\GLPI\plugins\processmaker\inc\process.class.php:85 Stack trace: #0 D:\WebApplications\GLPI\plugins\processmaker\front\process.form.php(22): PluginProcessmakerProcess->refreshTasks(Array) #1 {main} thrown in D:\WebApplications\GLPI\plugins\processmaker\inc\process.class.php on line 85
```

**Comment by Geo-Ron** [comment]
https://www.php.net/manual/en/locale.getprimarylanguage.php shows both PHP versions should have it...

**Comment by tomolimo** [comment]
Hello,
The Intl module is missing. 
Try `php -m `to have a list of the activated modules in your php.ini
Thank you
Regards,
Tomolimo

**Comment by Geo-Ron** [comment]
Hi tomolimo,

It was indeed disabled.

But enabling it, does not resolve my issue. The exception remains the same...
![image](https://user-images.githubusercontent.com/23144316/65221149-b1034880-dabc-11e9-9de7-55a6a8f63d53.png)


PHP -m output
![image](https://user-images.githubusercontent.com/23144316/65221197-d1cb9e00-dabc-11e9-995d-eff75b48f9a4.png)

**Comment by tomolimo** [comment]
Hello @Geo-Ron 
The Intl module is needed on the GLPI side, not on the ProcessMaker server side.
Is the module activated for GLPI?
Thank you,
Regards,
Tomolimo

**Comment by Geo-Ron** [comment]
![image](https://user-images.githubusercontent.com/23144316/65232059-d13d0280-dad0-11e9-8e73-7df1b8c7d571.png)

**Comment by Geo-Ron** [comment]
Thank you! My issue is resolved!

**Comment by tomolimo** [comment]
you're welcome
