### ISSUE TITLE
GLPI 9.3 processmaker plugin error 500 

### ISSUE THREAD

**Issue by momohamed770** [tomolimo/processmaker#95]
Hi,
I’ve installed processmaker 3.3 as per the documentation you provided and it is up and working, i’m trying to install the plugin for GLPI version 3.5 and once enabled the GLPI page get error 500 and i roll back by disable the plugin using DB query only.

**Comment by tomolimo** [comment]
Hello,
Could you check the error log files?
When an error 500 occurs, generally it means that something is wrong in the PHP modules (a missing module, or a function that is used in the code is not in the PHP modules).
Thank you,
Regards,
Tomolimo

**Comment by momohamed770** [comment]
Is there any required specific PHP modules for processmaker plugin to be installed?

**Comment by tomolimo** [comment]
Hello,
At my current knowledge the only module that is needed is the Intl (and it is explained in the wiki).
But could you look into the log files?
Thank you
Regards,
Tomolimo

**Comment by momohamed770** [comment]
I've installed intl module but the same result i found this in the log but i can't understand what should i do.

[2019-10-21 10:41:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\GLPI\inc\toolbox.class.php line 657
  *** PHP Warning(2): Use of undefined constant SOAP_COMPRESSION_GZIP - assumed 'SOAP_COMPRESSION_GZIP' (this will throw an Error in a future version of PHP)
  Backtrace :
  ...ins\processmaker\inc\processmaker.class.php:193 
  ...ins\processmaker\inc\processmaker.class.php:233 PluginProcessmakerProcessmaker->openSoap()
  plugins\processmaker\hook.php:204                  PluginProcessmakerProcessmaker->login()
  inc\plugin.class.php:1284                          plugin_processmaker_post_init()
  inc\includes.php:119                               Plugin::doHook()
  front\plugin.php:33                                include()
  {"user":"10@STG-GLPI","mem_usage":"0.000\", 1.26Mio)"}

**Comment by momohamed770** [comment]
I solved this issue and i'm trying to connect GLPI with PM but I've the following issue, I've checked all similar issues and tried all of them but with the same error.

all the versions are compatible and the PM server is downloaded and installed as per the wiki.

![image](https://user-images.githubusercontent.com/56794498/67208056-1bd5d580-f415-11e9-88fd-d25118d3038d.png)

**Comment by momohamed770** [comment]
Please ignore i finally resolved the issue by using port 8080
Listen 8080
<VirtualHost *:8080>

**Comment by tomolimo** [comment]
Hello @momohamed770 
Could you detail the root cause for both issues, and the way to solve them?
It may help for others, and for me to adjust the Wiki accordingly.
Thank you
Regards,
Tomolimo

**Comment by momohamed770** [comment]
Hi,
The 1st issue was unable to enable the PM plugin from GLPI giving me error 500, after checking the log i found the below.

[2019-10-21 10:41:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\GLPI\inc\toolbox.class.php line 657
*** PHP Warning(2): Use of undefined constant SOAP_COMPRESSION_GZIP - assumed 'SOAP_COMPRESSION_GZIP' (this will throw an Error in a future version of PHP)
Backtrace :
...ins\processmaker\inc\processmaker.class.php:193
...ins\processmaker\inc\processmaker.class.php:233 PluginProcessmakerProcessmaker->openSoap()
plugins\processmaker\hook.php:204 PluginProcessmakerProcessmaker->login()
inc\plugin.class.php:1284 plugin_processmaker_post_init()
inc\includes.php:119 Plugin::doHook()
front\plugin.php:33 include()

the solution is 
Adding the following modules to the GLPI PHP.ini file as i'm using a different PHP version for GLPI other than PM
extension=php_curl.dll
extension=php_gd2.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_mysql.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_soap.dll

The 2nd issue was after installing the plugin is that i'm unable to connect to the PM server and the solution was to edit the Apache24\conf\extra\pmos.conf
change server name and IP to be like

Listen 8080
<VirtualHost *:8080>

and add the PMserverFQDN:8080 in the GLPI general>processmaker Server URL

**Comment by tomolimo** [comment]
Hello @momohamed770 
Thank you very much for these explanations.
For you information, I don't use Apache, but IIS.
Regards,
Tomolimo
