### ISSUE TITLE
GLPI PM user import data missing

### ISSUE THREAD

**Issue by momohamed770** [tomolimo/processmaker#97]
Hi,
I've some issue between GLPI and PM such as users imported through GLPI automatic actions have wrong emails in PM (ex. mohamedd@donotreply.com instead of the correct domain found in GLPI) also they aren't able to login to PM (do i need to add an LDAP authentication for them).
Also if i need to get a manager approval inside a PM task (using report to field) how PM will know my organization structure?

**Comment by tomolimo** [comment]
Hello @momohamed770 
To understand the philosophy of the plugin (below is an extract of the [wiki](https://github.com/tomolimo/processmaker/wiki/Concept#basics-between-pm-and-glpi)):
1. GLPI is the pilot (or the driver, or the master) of the processes. In current plugin version, the ProcessMaker server scheduled tasks can't be used in the processes.
1. PM server is then a slave: the 'cases' can't evolve by themselves. Only users assigned to a PM task can run a case and make it evolve in a GLPI item.
1. GLPI groups and users are mapped into PM groups and users
1. To insure security and confidentiality, passwords of users mapped into PM are not known and are randomly generated by the plugin and are regularly reset. This to prevent that one person will approve something that should be approved by someone else.
1. Notifications are managed by the task notifications in GLPI. But it is possible to use dedicated notifications that are linked to a task and an event (task add, task re-assign, and task close). Also it is possible to send spontaneous emails. To get more information about notifications and emails, see: [Notifications](https://github.com/tomolimo/processmaker/wiki/Notifications).

And to add to these:
1. One of the principles of the PM server integration into GLPI is that it must be hidden from the end-users. It means the end-user must not have any interaction with PM server, but only with GLPI.
1. another principle is that no emails are sent from PM server, but all emails must be sent from GLPI see [Notifications](https://github.com/tomolimo/processmaker/wiki/Notifications). if you need to sent dedicated specifications or spontaneous emails.

To answer your hierarchy question: you may use, like we are doing here, the managers of the groups.
In a process, you may request (via a SQL query) the manager of a user, and then assign the next task to this manager.

We have developed manager validations for several processes, and these are used in my company.  

Thank you
Regards,
Tomolimo

**Comment by momohamed770** [comment]
Thanks for your answer but i'm still can't understand how i'll be able to assign the 2nd task to my direct manager, i'm able to get my direct manager from AD and insert in GLPI database and then make a query through PM SQL connection inside a workflow and store it in a variable.

The task should have the assignment administered using PM task assignment or must be assigned using GLPI only?

**Comment by tomolimo** [comment]
Hello @momohamed770 
The task assignment in a process are managed by the process only.
The manager task 'rule assignement' must be of type 'Value Based Assignment', and in a trigger you must assign a value to this @@REQUEST_VALIDATOR. Beware that the value must be the guid of the manager (guid that you can get from the table glpi_plugin_processmaker_users).
to be noted that the manager in @@REQUEST_VALIDATOR must have the right to execute the task: for this it must be in the groupe that is authorized to execute this task (here in my sample, it is the  'GLPI Users' group).
![image](https://user-images.githubusercontent.com/7569958/68277912-8b340200-0070-11ea-914e-af7d831f5c99.png)

Thank you
Regards,
Tomolimo

**Comment by momohamed770** [comment]
I've created a new variable @@PM_assign and inserted the value coming from the below query

Is it a must to create a trigger?

select pm_users_id from
(select id from glpi_db.glpi_users where user_dn = (select comment from glpi_db.glpi_users where id = @@GLPI_ITEM_REQUESTER_GLPI_ID))x
join
(SELECT * FROM glpi_db.glpi_plugin_processmaker_users) y
on x.id  = y.id



[cid:image001.png@01D5948D.19BA7F90]

**Comment by momohamed770** [comment]
OK fine i got it now how i can see the form of the 2nd step in the workflow to proceed with the task through the GLPI interface instead of logging to the PM server.

**Comment by tomolimo** [comment]
Cool :)

**Comment by momohamed770** [comment]
how i can see the form of the 2nd step in the workflow to proceed with the task through the GLPI interface instead of logging to the PM server?

**Comment by tomolimo** [comment]
Did you read and apply the tutorials?
https://github.com/tomolimo/processmaker/wiki/Tutorials

**Comment by momohamed770** [comment]
I've found something missing in the synchronization of steps and the 2nd user now can seen the form normally, but I've something wrong when submitting the 1st form 
![image](https://user-images.githubusercontent.com/56794498/68300100-cc92d480-00a5-11ea-8677-9e396bc56da3.png)

**Comment by tomolimo** [comment]
@momohamed770 did you try the tutorials?

**Comment by momohamed770** [comment]
Yes I've checked it but I'm doing changes not tickets and I'm trying different flow, I've reviewed it to make sure I'm not doing anything wrong.

Thanks & Regards,
Mohamed Osama Ibrahim

**Comment by tomolimo** [comment]
But my question was did you try them (means did you follow the processes like explained in the tutorials)?
And not only checked them :)

**Comment by tomolimo** [comment]
And anyway you are doing Changes or Tickets or Problems, it's working the same way

**Comment by momohamed770** [comment]
Hi,
I've did the tutorials and it is working fine, now i got back to my project which is a change management workflow.
The issue know is that after i finish the 1st task which is a form should be filled by the requester after pressing submit, GLPI is trying to access the 2nd task which shouldn't be authorized for the users it should be authorized only for the managers.
How i can end the 1st task without trying to access the 2nd task?

These processes is working normally when trying using PM only without GLPI.

**Comment by tomolimo** [comment]
Hello @momohamed770 
Thank you for the feedback.
To try to answer your question about next task: you may use a special group in which you set all the managers and assigned the task to the manager of the user.
In this case, the 2nd task will be assigned to the manager of the user, and the end-user will not be able to re-assign the task to him/her.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue, as there is no feedback. Fell free to re-open it if you want to add something.
