### ISSUE TITLE
Error adding process case to ticket

### ISSUE THREAD

**Issue by unvsual** [tomolimo/processmaker#98]
When adding a process case to a ticket in GLPI, I get an error about a USER UID or TASK UID.

To reproduce the behavior:
1. Go to Assistance > Tickets
2. Select a ticket, then select process case
3. Select the process to attribute

![image](https://user-images.githubusercontent.com/45260376/69536479-f12bef00-0f75-11ea-8ad6-4e8b50b0f19e.png)

System info:
 - OS: CentOS 7
 - Browser: Google Chrome
 - Version: 3.3.0-community-RE-1.6

Process diagram:
![image](https://user-images.githubusercontent.com/45260376/69536720-6e576400-0f76-11ea-9368-e1ab7d4810f0.png)

In GLPI:
![image](https://user-images.githubusercontent.com/45260376/69536808-a1015c80-0f76-11ea-820d-abd68d11f474.png)

![image](https://user-images.githubusercontent.com/45260376/69536824-aced1e80-0f76-11ea-97fc-1b8ccd021e05.png)

![image](https://user-images.githubusercontent.com/45260376/69536843-b7a7b380-0f76-11ea-8647-5c049bed41c4.png)

Thanks in advance.

**Comment by tomolimo** [comment]
Hello @unvsual 
Did you set assignment rule to the first task? 
See Tutorial 1: https://github.com/tomolimo/processmaker/wiki/Tutorial-1
Regards,
Tomolimo

**Comment by unvsual** [comment]
Hello @tomolimo, thank you for the quick reply. I have managed to test it with assignment rules and was able to surpass the problem, but now when I enter the process case I get the following error:
![image](https://user-images.githubusercontent.com/45260376/69550600-30b50400-0f93-11ea-8614-823aaef7a671.png)

Any idea what it could be? Thanks again.

**Comment by tomolimo** [comment]
Hello,
Which version of mysql are you using?
Typically, this error message is due to the strict mode taht is not supported by ProcessMaker server.
See: https://wiki.processmaker.com/3.3/ProcessMaker_Installation_Requirements

**Comment by unvsual** [comment]
I was able to find out the problem, it was SQL related, I had to add the following lines to <processmaker home dir>/config/database.php

`'modes'  => [
            'ONLY_FULL_GROUP_BY',
            'STRICT_TRANS_TABLES',
            'NO_ZERO_IN_DATE',
            'NO_ZERO_DATE',
            'ERROR_FOR_DIVISION_BY_ZERO',
            'NO_ENGINE_SUBSTITUTION',
        ]`

I will be doing some tests after this to better understand if the resolution, I'm not sure but doesn't there need to be some sort of content when entering this step? As per the documentation.
![image](https://user-images.githubusercontent.com/45260376/69551941-7b378000-0f95-11ea-9b9f-ccda1a48d33c.png)
![image](https://user-images.githubusercontent.com/45260376/69551980-8db1b980-0f95-11ea-9642-3c9b31c32b2f.png)
![image](https://user-images.githubusercontent.com/45260376/69552020-a15d2000-0f95-11ea-850a-d2349aa7a8fc.png)

**Comment by tomolimo** [comment]
If so, I think you are not using the right version of MySQL.
Are you using the version 8?

**Comment by unvsual** [comment]
Yes, I am using version 8.0.15.

**Comment by tomolimo** [comment]
Hello @unvsual 
That's the problem, currently ProcessMaker server doesn't support this version, see: https://wiki.processmaker.com/3.3/ProcessMaker_Installation_Requirements
I already made some tests, and I saw that some modifications have to be done in several locations in the code (apart of the one you've found)...
Could you respect the recommandations mentioned in the link above?
Thank you,
Regards,
Tomolimo

**Comment by sofiammm** [comment]
Hello @tomolimo ,

Is it  necessary to remove  version 8.0.15 and install another one? Is it enough to follow the instructions of the link?

thnks a lot,
S.

**Comment by tomolimo** [comment]
Depending on your OS, you may need to uninstall version 8, and to install version 5.7 (this version is ok I'm using it).

**Comment by sofiammm** [comment]
OS: CentOS 7

**Comment by tomolimo** [comment]
Hello @sofiammm, ,

I'm sorry, but I don't know this OS...

Anyway and moreover, you have to follow the wiki to install and configure PM server and PM plugin.
At the end you'll find two tutorials that you MUST follow to be sure that the server and the plugin are correctly installed and configured.

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I close this issue as there is no feedback, Feel free to re-open if you want to add something.
